package com.fidypay.repo;

import java.util.List;

import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.fidypay.entity.CoreTransactions;

@Repository
public interface CoreTransactionsRepository extends JpaRepository<CoreTransactions, Long> {

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME  FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1  AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndStartDateToEndDate(Long merchantId, String startDate, String endDate, Pageable pageable);

	@Query(value = "SELECT count(*) FROM  CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  WHERE  mt.MERCHANT_ID=?1  AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3))", nativeQuery = true)
	int countByMerchantIdAndStartDateToEndDate(Long merchantId, String startDate, String endDate);

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME  FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND si.SERVICE_ID=?2  AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndSeriveIdAndStartDateToEndDate(Long merchantId, Long serviceId, String startDate,
			String endDate, Pageable pageable);

	@Query(value = "SELECT count(*) FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND ct.SERVICE_ID=?2  AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4))", nativeQuery = true)
	int countByMerchantIdAndSeriveIdAndStartDateToEndDate(Long merchantId, Long serviceId, String startDate,
			String endDate);

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME,spt.RESPONSE_MESSAGE,mt.IS_SETTLED,ct.TRANSACTION_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  WHERE  mt.MERCHANT_ID=?1  AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndStartDateToEndDate2(Long merchantId, String startDate, String endDate);

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME,spt.RESPONSE_MESSAGE,mt.IS_SETTLED,ct.TRANSACTION_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID WHERE mt.MERCHANT_ID=?1 AND si.SERVICE_ID=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndSeriveIdAndStartDateToEndDate2(Long merchantId, Long serviceId, String startDate,
			String endDate);

	@Query(value = "SELECT EXTRACT(month FROM ct.TRXN_DATE) AS month,SUM(ct.TRXN_AMOUNT) AS amount FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID  WHERE ct.TRANSACTION_STATUS_ID !='2' AND mt.MERCHANT_ID=?1 AND year(ct.TRXN_DATE)=?2 GROUP BY EXTRACT(month FROM ct.TRXN_DATE)", nativeQuery = true)
	List<?> getAllYearWiseData(Long merchantId, String year);

	@Query(value = "SELECT ct.TRANSACTION_ID,ct.TRXN_AMOUNT FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID  WHERE ct.TRANSACTION_STATUS_ID !='2'  AND mt.MERCHANT_ID=?1 AND year(ct.TRXN_DATE)=?2 AND month(ct.TRXN_DATE)=?3", nativeQuery = true)
	List<?> getAllYearWiseData2(Long merchantId, String year, String month);

	@Query(value = "SELECT EXTRACT(week FROM ct.TRXN_DATE) AS week,SUM(ct.TRXN_AMOUNT) AS amount FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID  WHERE ct.TRANSACTION_STATUS_ID !='2' AND mt.MERCHANT_ID=?1 AND year(ct.TRXN_DATE)=?2 AND month(ct.TRXN_DATE)=?3 GROUP BY EXTRACT(week FROM ct.TRXN_DATE)", nativeQuery = true)
	List<?> getWeekDataByYearAndMonth(Long merchantId, String year, String month);

	@Query(value = "SELECT ct.TRANSACTION_ID,ct.TRXN_AMOUNT FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID  WHERE ct.TRANSACTION_STATUS_ID !='2'  AND mt.MERCHANT_ID=?1 AND year(ct.TRXN_DATE)=?2 AND month(ct.TRXN_DATE)=?3 AND week(ct.TRXN_DATE)=?4", nativeQuery = true)
	List<?> getWeekDataByYearAndMonth2(Long merchantId, String year, String month, String week);

	@Query(value = "SELECT EXTRACT(day FROM ct.TRXN_DATE) AS day,SUM(ct.TRXN_AMOUNT) AS amount FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID  WHERE ct.TRANSACTION_STATUS_ID !='2' AND mt.MERCHANT_ID=?1 AND year(ct.TRXN_DATE)=?2 AND month(ct.TRXN_DATE)=?3 GROUP BY EXTRACT(day FROM ct.TRXN_DATE)", nativeQuery = true)
	List<?> getDayDataByYearAndMonth(Long merchantId, String year, String month);

	@Query(value = "SELECT ct.TRANSACTION_ID,ct.TRXN_AMOUNT FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID  WHERE ct.TRANSACTION_STATUS_ID !='2'  AND mt.MERCHANT_ID=?1 AND year(ct.TRXN_DATE)=?2 AND month(ct.TRXN_DATE)=?3 AND day(ct.TRXN_DATE)=?4", nativeQuery = true)
	List<?> getDayDataByYearAndMonth2(Long merchantId, String year, String month, String day);

	@Query(value = "SELECT EXTRACT(month FROM ct.TRXN_DATE) AS month,SUM(ct.TRXN_AMOUNT) AS amount,si.SERVICE_NAME AS servicename,count(ct.TRANSACTION_ID) AS transaction  FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID WHERE ct.TRANSACTION_STATUS_ID !='2' AND mt.MERCHANT_ID=?1 AND year(ct.TRXN_DATE)=?2 AND month(ct.TRXN_DATE)=?3 GROUP BY EXTRACT(month FROM ct.TRXN_DATE),servicename", nativeQuery = true)
	List<?> getPiChartWeekDataByYearAndMonth(Long merchantId, String year, String month);

	@Query(value = "SELECT ct.TRANSACTION_ID,ct.TRXN_AMOUNT,si.SERVICE_NAME FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID INNER JOIN MERCHANTS m ON m.MERCHANT_ID=mt.MERCHANT_ID INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID WHERE ct.TRANSACTION_STATUS_ID !='2'  AND mt.MERCHANT_ID=?1 AND year(ct.TRXN_DATE)=?2 AND month(ct.TRXN_DATE)=?3 AND week(ct.TRXN_DATE)=?4", nativeQuery = true)
	List<?> getPiChartWeekDataByYearAndMonth2(Long merchantId, String year, String month, String week);

	
	// new trxnStatusId
	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1  AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) AND  ts.TRANSACTION_STATUS_ID=?4 ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndStartDateToEndDateAndTrxnStatusId(Long merchantId, String startDate, String endDate,
			Long trxnStatusId, Pageable pageable);

	@Query(value = "SELECT count(*) FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  WHERE  mt.MERCHANT_ID=?1  AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) AND  ct.TRANSACTION_STATUS_ID=?4", nativeQuery = true)
	int countByMerchantIdAndStartDateToEndDateAndTrxnStatusId(Long merchantId, String startDate, String endDate,
			Long trxnStatusId);

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME  FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND si.SERVICE_ID=?2  AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND  ts.TRANSACTION_STATUS_ID=?5 ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndSeriveIdAndStartDateToEndDateAndTrxnStatusId(Long merchantId, Long serviceId,
			String startDate, String endDate, Long trxnStatusId, Pageable pageable);

	@Query(value = "SELECT count(*) FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  WHERE  mt.MERCHANT_ID=?1 AND ct.SERVICE_ID=?2  AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND  ct.TRANSACTION_STATUS_ID=?5", nativeQuery = true)
	int countByMerchantIdAndSeriveIdAndStartDateToEndDateAndTrxnStatusId(Long merchantId, Long serviceId,
			String startDate, String endDate, Long trxnStatusId);

	// new trxnStatusId2
	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME,spt.RESPONSE_MESSAGE,mt.IS_SETTLED,ct.TRANSACTION_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1  AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) AND  ts.TRANSACTION_STATUS_ID=?4 ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndStartDateToEndDateAndTrxnStatusId2(Long merchantId, String startDate, String endDate,
			Long trxnStatusId);

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME,spt.RESPONSE_MESSAGE,mt.IS_SETTLED,ct.TRANSACTION_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND si.SERVICE_ID=?2  AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND  ts.TRANSACTION_STATUS_ID=?5 ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndSeriveIdAndStartDateToEndDateAndTrxnStatusId2(Long merchantId, Long serviceId,
			String startDate, String endDate, Long trxnStatusId);
	
	//Created by Arpan 29-4-2022
	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME,spt.RESPONSE_MESSAGE FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND si.SERVICE_ID=?2  AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND  ts.TRANSACTION_STATUS_ID=?5 ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndSeriveIdAndStartDateToEndDateAndTrxnStatusId2New(Long merchantId, Long serviceId,
			String startDate, String endDate, Long trxnStatusId);

	@Query(value = "SELECT * FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND si.SERVICE_ID=?2  AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND  ts.TRANSACTION_STATUS_ID=?5 ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	double getServiceTotalTransactionForTotalAmount(Long merchantId, String startDate, String endDate);

	@Query(value = "Select spt.SP_REFERENCE_ID,ct.TRXN_REF_ID from CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID where mt.MERCHANT_TRXN_REF_ID=?1 and mt.MERCHANT_ID=?2", nativeQuery = true)
	List<?> findByMerchantTrxnRefId(String merchantTrxnRefId, long merchantId);

	@Query(value = "Select spt.SP_REFERENCE_ID,ct.TRXN_REF_ID from CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID where mt.MERCHANT_ID=?1 and ct.TRXN_REF_ID=?2", nativeQuery = true)
	List<?> findByTrxnRefId(long merchantId, String trxnRefId);

	@Query(value = "SELECT SUM(ct.TRXN_AMOUNT) AS amount,si.SERVICE_NAME AS servicename,count(ct.TRANSACTION_ID) AS transaction  FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID WHERE ct.TRANSACTION_STATUS_ID !='2' AND mt.MERCHANT_ID=?1 AND year(ct.TRXN_DATE)=?2 AND month(ct.TRXN_DATE)=?3 GROUP BY servicename", nativeQuery = true)
	List<?> getTrxnAmountPiChartWeekDataByYearAndMonth(Long merchantId, String year, String month);

	@Query(value = "SELECT ct.TRXN_AMOUNT FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID WHERE TRANSACTION_STATUS_ID !='2' AND mt.MERCHANT_ID=?1 AND year(ct.TRXN_DATE)=?2 AND month(ct.TRXN_DATE)=?3 AND si.SERVICE_NAME=?4", nativeQuery = true)
	List<Double> getTrxnAmountPiChartWeekDataByYearAndMonth2(Long merchantId, String year, String month,
			String serviceName);

	@Query(value = "Select spt.SP_REFERENCE_ID,pct.PC_TRAN_PARAMETER,ct.TRXN_REF_ID,mt.MERCHANT_TRXN_REF_ID from CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID where mt.MERCHANT_TRXN_REF_ID=?1 and mt.MERCHANT_ID=?2", nativeQuery = true)
	List<?> findByMerchantTrxnRefIdForUpi(String merchantTrxnRefId, long merchantId);

	@Query(value = "Select spt.SP_REFERENCE_ID,pct.PC_TRAN_PARAMETER,ct.TRXN_REF_ID,mt.MERCHANT_TRXN_REF_ID from CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID where mt.MERCHANT_ID=?1 and spt.OPERATOR_REF_NO=?2 or spt.SP_REFERENCE_ID=?2", nativeQuery = true)
	List<?> findByOperatorRefNo(long merchantId, String UTR);

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRANSACTION_ID,ct.TRXN_DATE,spt.RESPONSE_MESSAGE, mt.IS_SETTLED, spt.OPERATOR_REF_NO, mt.MERCHANT_TRXN_REF_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE mt.MERCHANT_ID=?1 AND ct.TRANSACTION_STATUS_ID=1 AND si.SERVICE_NAME=?2 AND pct.PC_TRAN_PARAMETER=?3 AND ((ct.TRXN_DATE>=?4) and (ct.TRXN_DATE<=?5)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndSeriveIdAndVpaAndStartDateToEndDateForSettlement(Long merchantId, String serviceName,
			String vpa, String startDate, String endDate);

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME  FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2  AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndVpaAndStartDateToEndDate(Long merchantId, String vpa, String startDate, String endDate,
			Pageable pageable);

	@Query(value = "SELECT count(*)  FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2  AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	int countByMerchantIdAndVpaAndStartDateToEndDate(Long merchantId, String vpa, String startDate, String endDate);

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME  FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 And si.SERVICE_ID=?2 AND pct.PC_TRAN_PARAMETER=?3  AND ((ct.TRXN_DATE>=?4) and (ct.TRXN_DATE<=?5)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndSeriveIdAndVpaAndStartDateToEndDate(Long merchantId, Long serviceId, String vpa,
			String startDate, String endDate, Pageable pageable);

	@Query(value = "SELECT count(*)  FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 And si.SERVICE_ID=?2 AND pct.PC_TRAN_PARAMETER=?3  AND ((ct.TRXN_DATE>=?4) and (ct.TRXN_DATE<=?5)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	int countByMerchantIdAndSeriveIdAndVpaAndStartDateToEndDate(Long merchantId, Long serviceId, String vpa,
			String startDate, String endDate);

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME  FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1  AND pct.PC_TRAN_PARAMETER=?2 AND ts.TRANSACTION_STATUS_ID=?3   AND ((ct.TRXN_DATE>=?4) and (ct.TRXN_DATE<=?5)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndVpaAndTrxnStatusIdAndStartDateToEndDate(Long merchantId, String vpa, Long trxnStatusId,
			String startDate, String endDate, Pageable pageable);

	@Query(value = "SELECT count(*)  FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1  AND pct.PC_TRAN_PARAMETER=?2 AND ts.TRANSACTION_STATUS_ID=?3   AND ((ct.TRXN_DATE>=?4) and (ct.TRXN_DATE<=?5)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	int countByMerchantIdAndVpaAndTrxnStatusIdAndStartDateToEndDate(Long merchantId, String vpa, Long trxnStatusId,
			String startDate, String endDate);

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME  FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1  AND pct.PC_TRAN_PARAMETER=?2 AND ts.TRANSACTION_STATUS_ID=?3 AND si.SERVICE_ID=?4  AND ((ct.TRXN_DATE>=?5) and (ct.TRXN_DATE<=?6)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndVpaAndTrxnStatusIdAndServiceIdAndStartDateToEndDate(Long merchantId, String vpa,
			Long trxnStatusId, Long serviceId, String startDate, String endDate, Pageable pageable);

	@Query(value = "SELECT count(*)  FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1  AND pct.PC_TRAN_PARAMETER=?2 AND ts.TRANSACTION_STATUS_ID=?3 AND si.SERVICE_ID=?4  AND ((ct.TRXN_DATE>=?5) and (ct.TRXN_DATE<=?6)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	int countByMerchantIdAndVpaAndTrxnStatusIdAndServiceIdAndStartDateToEndDate(Long merchantId, String vpa,
			Long trxnStatusId, Long serviceId, String startDate, String endDate);

//	------------------------------------for vpa----------------------------------------------------------------------

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME,spt.RESPONSE_MESSAGE,mt.IS_SETTLED,ct.TRANSACTION_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID  WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndStartDateToEndDate2AndVpa(Long merchantId, String vpa, String startDate, String endDate);

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME,spt.RESPONSE_MESSAGE,mt.IS_SETTLED,ct.TRANSACTION_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND si.SERVICE_ID=?3 AND ((ct.TRXN_DATE>=?4) and (ct.TRXN_DATE<=?5)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndSeriveIdAndStartDateToEndDate2AndVpa(Long merchantId, String vpa, Long serviceId,
			String startDate, String endDate);

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME,spt.RESPONSE_MESSAGE,mt.IS_SETTLED,ct.TRANSACTION_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2  AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND  ts.TRANSACTION_STATUS_ID=?5 ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndStartDateToEndDateAndTrxnStatusId2AndVpa(Long merchantId, String vpa, String startDate,
			String endDate, Long trxnStatusId);

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME,spt.RESPONSE_MESSAGE,mt.IS_SETTLED,ct.TRANSACTION_ID  FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND si.SERVICE_ID=?3  AND ((ct.TRXN_DATE>=?4) and (ct.TRXN_DATE<=?5)) AND  ts.TRANSACTION_STATUS_ID=?6 ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndSeriveIdAndStartDateToEndDateAndTrxnStatusId2AndVpa(Long merchantId, String vpa,
			Long serviceId, String startDate, String endDate, Long trxnStatusId);

	@Query(value = "SELECT ct.TRANSACTION_ID,ct.TRXN_AMOUNT,ct.TRXN_DATE,ms.SETTLEMENT_DETAILS,spt.OPERATOR_REF_NO,spt.RESPONSE_MESSAGE FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON pct.TRANSACTION_ID=ct.TRANSACTION_ID INNER JOIN MERCHANT_SETTLEMENTS ms On mt.MERCHANT_ID=ms.MERCHANT_ID WHERE mt.MERCHANT_ID=?1 AND ct.TRANSACTION_STATUS_ID=1 AND si.SERVICE_NAME=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndSeriveIdAndStartDateToEndDateForSettlement(Long merchantId, String serviceName,
			String startDate, String endDate);

	
	@Query(value = "SELECT COUNT(*) FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE ct.TRANSACTION_STATUS_ID=1 AND mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4))", nativeQuery = true)
	long findByMerchantIdAndVpaAndStartDateToEndDateForSettelement(Long merchantId, String vpa, String startDate,
	String endDate);

	@Query(value = "SELECT ct.TRXN_AMOUNT,ct.TRXN_DATE,ct.TRXN_REF_ID,ct.TRXN_SERVICE_IDENTIFIER,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID,spt.OPERATOR_REF_NO,si.SERVICE_NAME,ts.STATUS_NAME,ct.TRANSACTION_ID,pct.PC_TRAN_MSG,spt.RESPONSE_MESSAGE  FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE si.SERVICE_NAME=?1 AND mt.MERCHANT_ID=?2  AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> findByMerchantIdAndStartDateToEndDateForFastag(String serviceName,Long merchantId, String startDate, String endDate,
			Pageable pageable);
	
	@Query(value = "SELECT count(*) FROM   CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si  ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID  WHERE si.SERVICE_NAME=?1 AND  mt.MERCHANT_ID=?2  AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4))", nativeQuery = true)
	int countByMerchantIdAndStartDateToEndDateForFastag(String serviceName,Long merchantId, String startDate, String endDate);

	@Query(value = "SELECT ct.TRANSACTION_ID,ts.STATUS_NAME  FROM CORE_TRANSACTIONS ct INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ct.TRANSACTION_STATUS_ID=ts.TRANSACTION_STATUS_ID WHERE spt.SP_REFERENCE_ID=?1", nativeQuery = true)
	List<?> checkTransactionstatus(String spRefId);
}
