package com.fidypay.repo;

import java.math.BigInteger;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.fidypay.entity.ServiceInfo;

@Repository
public interface ServiceInfoRepository extends JpaRepository<ServiceInfo, Long> {

	@Query(value = "SELECT si.SERVICE_ID,si.SERVICE_NAME From CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID WHERE mt.MERCHANT_ID=?1 GROUP BY si.SERVICE_ID,si.SERVICE_NAME ORDER BY si.SERVICE_NAME ASC", nativeQuery = true)
	List<?> getServiceByMerchantId(long merchantId);

	@Query(value = "SELECT COUNT(ct.TRANSACTION_ID),SUM(ct.TRXN_AMOUNT)  FROM CORE_TRANSACTIONS ct  INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID inner join SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID WHERE ct.TRANSACTION_STATUS_ID !='2'  AND mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3))", nativeQuery = true)
	List<?> getTotalTrxnDetail(long merchantId, String date1, String date2);

	@Query(value = "SELECT ct.TRANSACTION_ID,ct.TRXN_AMOUNT  FROM CORE_TRANSACTIONS ct  INNER JOIN MERCHANT_TRANSACTIONS mt ON ct.TRANSACTION_ID=mt.TRANSACTION_ID INNER JOIN MERCHANTS m ON m.MERCHANT_ID=mt.MERCHANT_ID INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID WHERE ct.TRANSACTION_STATUS_ID !='2'  AND mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3))", nativeQuery = true)
	List<?> getTotalTrxnDetail2(long merchantId, String date1, String date2);

	@Query(value = "SELECT ct.TRXN_REF_ID,date_format(ct.TRXN_DATE,'%d-%m-%Y %H:%i:%S') as TRXN_DATE,si.SERVICE_NAME,ct.TRXN_AMOUNT,ct.TRXN_SERVICE_IDENTIFIER,ts.STATUS_NAME, spt.OPERATOR_REF_NO,mt.MERCHANT_TRXN_REF_ID,spt.SP_REFERENCE_ID FROM CORE_TRANSACTIONS ct  INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID inner join SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) ORDER BY ct.TRXN_DATE DESC", nativeQuery = true)
	List<?> getServiceTotalTransactionInDetails(String start, String end, long merchantId);

	@Query(value = "SELECT si.SERVICE_ID,si.SERVICE_NAME, COUNT(ct.TRANSACTION_ID),SUM(ct.TRXN_AMOUNT) FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID WHERE mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) GROUP BY si.SERVICE_ID,si.SERVICE_NAME ORDER BY si.SERVICE_NAME ASC", nativeQuery = true)
	List<?> getServiceTotalTransaction1(long merchantId, String start, String end);

	@Query(value = "SELECT si.SERVICE_ID,si.SERVICE_NAME, COUNT(ct.transaction_id),SUM(ct.trxn_amount) FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID WHERE mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) and si.SERVICE_ID=?4 GROUP BY si.SERVICE_ID,si.SERVICE_NAME ORDER BY si.SERVICE_NAME ASC", nativeQuery = true)
	List<?> getServiceTotalTransaction1New(long merchantId, String start, String end, Long serviceId);

	@Query(value = "SELECT ct.TRANSACTION_ID,ct.TRXN_AMOUNT FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID   INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID WHERE  mt.MERCHANT_ID=?1 AND si.SERVICE_ID=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4))", nativeQuery = true)
	List<?> getServiceTotalTransaction2(long merchantId, BigInteger serviceId, String start, String end);

	@Query(value = "SELECT ct.TRANSACTION_ID,ct.TRXN_AMOUNT FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID   INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID WHERE  mt.MERCHANT_ID=?1 AND si.SERVICE_ID=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4))", nativeQuery = true)
	List<?> getServiceTotalTransaction22(long merchantId, Long serviceId, String start, String end);

	@Query(value = "SELECT ts.STATUS_NAME,SUM(ct.TRXN_AMOUNT),COUNT(ct.TRANSACTION_ID),ts.TRANSACTION_STATUS_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID   INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID  WHERE  mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) AND si.SERVICE_ID=?4 GROUP BY si.SERVICE_ID, ts.STATUS_NAME, si.SERVICE_NAME, ts.TRANSACTION_STATUS_ID ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List<?> getServiceTotalTransactio3(long merchantId, String start, String end, BigInteger serviceId);

	@Query(value = "SELECT ts.STATUS_NAME,SUM(ct.TRXN_AMOUNT),COUNT(ct.TRANSACTION_ID),ts.TRANSACTION_STATUS_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID  WHERE  mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) AND si.SERVICE_ID=?4 GROUP BY si.SERVICE_ID, ts.STATUS_NAME, si.SERVICE_NAME, ts.TRANSACTION_STATUS_ID ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List<?> getServiceTotalTransactio33(long merchantId, String start, String end, Long serviceId);

	@Query(value = "SELECT ts.STATUS_NAME,ct.TRXN_AMOUNT, ct.TRANSACTION_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID WHERE  mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) AND ts.TRANSACTION_STATUS_ID=?4 AND si.SERVICE_ID=?5 ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List<?> getServiceTotalTransactio4(long merchantId, String start, String end, BigInteger transactionStatus,
			BigInteger serviceId);

	@Query(value = "SELECT ts.STATUS_NAME,ct.TRXN_AMOUNT, ct.TRANSACTION_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID WHERE  mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) AND ts.TRANSACTION_STATUS_ID=?4 AND si.SERVICE_ID=?5 ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List<?> getServiceTotalTransactio44(long merchantId, String start, String end, BigInteger transactionStatus,
			Long serviceId);

	@Query(value = "SELECT si.SERVICE_ID,si.SERVICE_NAME, COUNT(ct.transaction_id),SUM(ct.trxn_amount) FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID WHERE mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) AND ct.TRANSACTION_STATUS_ID=?4 GROUP BY si.SERVICE_ID,si.SERVICE_NAME ORDER BY si.SERVICE_NAME ASC", nativeQuery = true)
	List<?> getServiceTotalTransactionAndTrxnStatusId1(Long merchantId, String startDate, String endDate,
			Long trxnStatusId);

	@Query(value = "SELECT si.SERVICE_ID,si.SERVICE_NAME, COUNT(ct.transaction_id),SUM(ct.trxn_amount) FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID WHERE mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) AND ct.TRANSACTION_STATUS_ID=?4 GROUP BY si.SERVICE_ID,si.SERVICE_NAME ORDER BY si.SERVICE_NAME ASC", nativeQuery = true)
	List<?> getServiceTotalTransactionAndTrxnStatusId2(Long merchantId, BigInteger bigInteger, String startDate,
			String endDate, Long trxnStatusId);

	@Query(value = "SELECT ts.STATUS_NAME,SUM(ct.TRXN_AMOUNT),COUNT(ct.TRANSACTION_ID),ts.TRANSACTION_STATUS_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID  WHERE  mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) AND si.SERVICE_ID=?4 AND ct.TRANSACTION_STATUS_ID=?5 GROUP BY si.SERVICE_ID, ts.STATUS_NAME, si.SERVICE_NAME, ts.TRANSACTION_STATUS_ID ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List<?> getServiceTotalTransactioAndTrxnStatusId3(Long merchantId, String startDate, String endDate,
			BigInteger bigInteger, Long trxnStatusId);

	@Query(value = "SELECT ts.STATUS_NAME,ct.TRXN_AMOUNT, ct.TRANSACTION_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID WHERE  mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) AND ts.TRANSACTION_STATUS_ID=?4 AND si.SERVICE_ID=?5  ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List<?> getServiceTotalTransactioAndTrxnStatusId4(Long merchantId, String startDate, String endDate,
			Long trxnStatusId, BigInteger bigInteger2);

	@Query(value = "SELECT si.SERVICE_ID,si.SERVICE_NAME, COUNT(ct.transaction_id),SUM(ct.trxn_amount) FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID WHERE mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) and si.SERVICE_ID=?4 AND ct.TRANSACTION_STATUS_ID=?5 GROUP BY si.SERVICE_ID,si.SERVICE_NAME ORDER BY si.SERVICE_NAME ASC", nativeQuery = true)
	List<?> getServiceTotalTransactionAndTrxnStatusId1New(Long merchantId, String startDate, String endDate,
			Long serviceId, Long trxnStatusId);

	@Query(value = "SELECT ct.TRANSACTION_ID,ct.TRXN_AMOUNT FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID WHERE  mt.MERCHANT_ID=?1 AND si.SERVICE_ID=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND ct.TRANSACTION_STATUS_ID=?5 ", nativeQuery = true)
	List<?> getServiceTotalTransactionAndTrxnStatusId22(Long merchantId, Long serviceId, String startDate,
			String endDate, Long trxnStatusId);

	@Query(value = "SELECT ts.STATUS_NAME,SUM(ct.TRXN_AMOUNT),COUNT(ct.TRANSACTION_ID),ts.TRANSACTION_STATUS_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID  WHERE  mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) AND si.SERVICE_ID=?4 AND ct.TRANSACTION_STATUS_ID=?5 GROUP BY si.SERVICE_ID, ts.STATUS_NAME, si.SERVICE_NAME, ts.TRANSACTION_STATUS_ID ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List<?> getServiceTotalTransactioAndTrxnStatusId33(Long merchantId, String startDate, String endDate,
			Long serviceId, Long trxnStatusId);

	@Query(value = "SELECT ts.STATUS_NAME,ct.TRXN_AMOUNT, ct.TRANSACTION_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID WHERE  mt.MERCHANT_ID=?1 AND ((ct.TRXN_DATE>=?2) and (ct.TRXN_DATE<=?3)) AND ts.TRANSACTION_STATUS_ID=?4 AND si.SERVICE_ID=?5 ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List<?> getServiceTotalTransactioAndTrxnStatusId44(long merchantId, String start, String end,
			Long transactionStatus, Long serviceId);

	@Query(value = "SELECT * FROM SERVICE_INFO SI WHERE SI.IS_WALLET_SERVICE='0' AND SI.IS_CLIENT_SERVICE='0' AND SI.IS_SERVICE_DELETED='1'", nativeQuery = true)
	List<ServiceInfo> findByService();

	// -------------------------------------VPA--------------------------------------------------------

	@Query(value = "SELECT si.SERVICE_ID,si.SERVICE_NAME, COUNT(ct.TRANSACTION_ID),SUM(ct.TRXN_AMOUNT) FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) GROUP BY si.SERVICE_ID,si.SERVICE_NAME ORDER BY si.SERVICE_NAME ASC", nativeQuery = true)
	List getServiceTotalTransaction1AndVpa(Long merchantId, String vpa, String startDate, String endDate);

	@Query(value = "SELECT ct.TRANSACTION_ID,ct.TRXN_AMOUNT FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID   INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND si.SERVICE_ID=?3 AND ((ct.TRXN_DATE>=?4) and (ct.TRXN_DATE<=?5))", nativeQuery = true)
	List getServiceTotalTransaction2AndVpa(Long merchantId, String vpa, BigInteger bigInteger, String startDate,
			String endDate);

	@Query(value = "SELECT ts.STATUS_NAME,SUM(ct.TRXN_AMOUNT),COUNT(ct.TRANSACTION_ID),ts.TRANSACTION_STATUS_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID   INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID  WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND si.SERVICE_ID=?5 GROUP BY si.SERVICE_ID, ts.STATUS_NAME, si.SERVICE_NAME, ts.TRANSACTION_STATUS_ID ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List getServiceTotalTransactio3AndVpa(Long merchantId, String vpa, String startDate, String endDate,
			BigInteger bigInteger);

	@Query(value = "SELECT ts.STATUS_NAME,ct.TRXN_AMOUNT, ct.TRANSACTION_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID  INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND ts.TRANSACTION_STATUS_ID=?5 AND si.SERVICE_ID=?6 ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List getServiceTotalTransactio4AndVpa(Long merchantId, String vpa, String startDate, String endDate,
			BigInteger bigInteger, BigInteger bigInteger2);

	@Query(value = "SELECT si.SERVICE_ID,si.SERVICE_NAME, COUNT(ct.transaction_id),SUM(ct.trxn_amount) FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) and si.SERVICE_ID=?5 GROUP BY si.SERVICE_ID,si.SERVICE_NAME ORDER BY si.SERVICE_NAME ASC", nativeQuery = true)
	List getServiceTotalTransaction1NewAndVpa(Long merchantId, String vpa, String startDate, String endDate,
			Long serviceIds);

	@Query(value = "SELECT ct.TRANSACTION_ID,ct.TRXN_AMOUNT FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID   INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND si.SERVICE_ID=?3 AND ((ct.TRXN_DATE>=?4) and (ct.TRXN_DATE<=?5))", nativeQuery = true)
	List getServiceTotalTransaction22AndVpa(Long merchantId, String vpa, Long serviceIds, String startDate,
			String endDate);

	@Query(value = "SELECT ts.STATUS_NAME,SUM(ct.TRXN_AMOUNT),COUNT(ct.TRANSACTION_ID),ts.TRANSACTION_STATUS_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID  WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND si.SERVICE_ID=?5 GROUP BY si.SERVICE_ID, ts.STATUS_NAME, si.SERVICE_NAME, ts.TRANSACTION_STATUS_ID ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List getServiceTotalTransactio33AndVpa(Long merchantId, String vpa, String startDate, String endDate,
			Long serviceIds);

	@Query(value = "SELECT ts.STATUS_NAME,ct.TRXN_AMOUNT, ct.TRANSACTION_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND ts.TRANSACTION_STATUS_ID=?5 AND si.SERVICE_ID=?6 ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List getServiceTotalTransactio44AndVpa(Long merchantId, String vpa, String startDate, String endDate,
			BigInteger bigInteger, Long serviceIds);

	@Query(value = "SELECT si.SERVICE_ID,si.SERVICE_NAME, COUNT(ct.transaction_id),SUM(ct.trxn_amount) FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND ct.TRANSACTION_STATUS_ID=?5 GROUP BY si.SERVICE_ID,si.SERVICE_NAME ORDER BY si.SERVICE_NAME ASC", nativeQuery = true)
	List getServiceTotalTransactionAndTrxnStatusId1AndVpa(Long merchantId, String vpa, String startDate, String endDate,
			Long trxnStatusId);

	@Query(value = "SELECT si.SERVICE_ID,si.SERVICE_NAME, COUNT(ct.transaction_id),SUM(ct.trxn_amount) FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND ct.TRANSACTION_STATUS_ID=?5 GROUP BY si.SERVICE_ID,si.SERVICE_NAME ORDER BY si.SERVICE_NAME ASC", nativeQuery = true)
	List getServiceTotalTransactionAndTrxnStatusId2AndVpa(Long merchantId, String vpa, BigInteger bigInteger,
			String startDate, String endDate, Long trxnStatusId);

	@Query(value = "SELECT ts.STATUS_NAME,SUM(ct.TRXN_AMOUNT),COUNT(ct.TRANSACTION_ID),ts.TRANSACTION_STATUS_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND si.SERVICE_ID=?5 AND ct.TRANSACTION_STATUS_ID=?6 GROUP BY si.SERVICE_ID, ts.STATUS_NAME, si.SERVICE_NAME, ts.TRANSACTION_STATUS_ID ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List getServiceTotalTransactioAndTrxnStatusId3AndVpa(Long merchantId, String vpa, String startDate, String endDate,
			BigInteger bigInteger, Long trxnStatusId);

	@Query(value = "SELECT ts.STATUS_NAME,ct.TRXN_AMOUNT, ct.TRANSACTION_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND ts.TRANSACTION_STATUS_ID=?5 AND si.SERVICE_ID=?6  ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List getServiceTotalTransactioAndTrxnStatusId4AndVpa(Long merchantId, String vpa, String startDate, String endDate,
			Long trxnStatusId, BigInteger bigInteger);

	@Query(value = "SELECT si.SERVICE_ID,si.SERVICE_NAME, COUNT(ct.transaction_id),SUM(ct.trxn_amount) FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) and si.SERVICE_ID=?5 AND ct.TRANSACTION_STATUS_ID=?6 GROUP BY si.SERVICE_ID,si.SERVICE_NAME ORDER BY si.SERVICE_NAME ASC", nativeQuery = true)
	List getServiceTotalTransactionAndTrxnStatusId1NewAndVpa(Long merchantId, String vpa, String startDate,
			String endDate, Long serviceIds, Long trxnStatusId);

	@Query(value = "SELECT ct.TRANSACTION_ID,ct.TRXN_AMOUNT FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON si.SERVICE_ID=ct.SERVICE_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND si.SERVICE_ID=?3 AND ((ct.TRXN_DATE>=?4) and (ct.TRXN_DATE<=?5)) AND ct.TRANSACTION_STATUS_ID=?6", nativeQuery = true)
	List getServiceTotalTransactionAndTrxnStatusId22AndVpa(Long merchantId, String vpa, Long serviceIds,
			String startDate, String endDate, Long trxnStatusId);

	@Query(value = "SELECT ts.STATUS_NAME,SUM(ct.TRXN_AMOUNT),COUNT(ct.TRANSACTION_ID),ts.TRANSACTION_STATUS_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID  WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND si.SERVICE_ID=?5 AND ct.TRANSACTION_STATUS_ID=?6 GROUP BY si.SERVICE_ID, ts.STATUS_NAME, si.SERVICE_NAME, ts.TRANSACTION_STATUS_ID ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List getServiceTotalTransactioAndTrxnStatusId33AndVpa(Long merchantId, String vpa, String startDate, String endDate,
			Long serviceIds, Long trxnStatusId);

	@Query(value = "SELECT ts.STATUS_NAME,ct.TRXN_AMOUNT, ct.TRANSACTION_ID FROM CORE_TRANSACTIONS ct INNER JOIN MERCHANT_TRANSACTIONS mt ON mt.TRANSACTION_ID = ct.TRANSACTION_ID INNER JOIN SERVICE_PROVIDER_TRANSACTIONS spt ON ct.TRANSACTION_ID=spt.TRANSACTION_ID  INNER JOIN SERVICE_INFO si ON ct.SERVICE_ID=si.SERVICE_ID  INNER JOIN TRANSACTION_STATUS ts ON ts.TRANSACTION_STATUS_ID=ct.TRANSACTION_STATUS_ID INNER JOIN PAYMENT_CHANNEL_TRANSACTIONS pct ON ct.TRANSACTION_ID=pct.TRANSACTION_ID WHERE  mt.MERCHANT_ID=?1 AND pct.PC_TRAN_PARAMETER=?2 AND ((ct.TRXN_DATE>=?3) and (ct.TRXN_DATE<=?4)) AND ts.TRANSACTION_STATUS_ID=?5 AND si.SERVICE_ID=?6 ORDER BY ts.STATUS_NAME DESC", nativeQuery = true)
	List getServiceTotalTransactioAndTrxnStatusId44AndVpa(Long merchantId, String vpa, String startDate, String endDate,
			Long trxnStatusId, Long serviceIds);

	@Query(value = "SELECT *  FROM SERVICE_INFO si WHERE si.SERVICE_NAME=?1", nativeQuery = true)
	ServiceInfo findByServiceName(String encString);

	@Query(value = "SELECT * FROM SERVICE_INFO si WHERE si.SERVICE_ID=?1", nativeQuery = true)
	ServiceInfo findByMerchantServiceId(long mServiceId);

	@Query(value = "SELECT * FROM SERVICE_INFO si WHERE si.service_Name=?1", nativeQuery = true)
	ServiceInfo findServiceByName(String serviceName);
}
