package com.fidypay.entity;

// Generated Sep 23, 2015 6:40:35 PM by Hibernate Tools 4.0.0



import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * CustomerWalletTransactions generated by hbm2java
 */

@Entity
@Table(name = "CUSTOMER_WALLET_TRANSACTIONS")
@EntityListeners(AuditingEntityListener.class)
public class CustomerWalletTransactions implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CUST_WALLET_TRXN_ID")
	private long custWalletTrxnId;
	
		
	 @ManyToOne
	 @JoinColumn(name = "CUST_WALLET_ID")
     private CustomerWalletInfo customerWalletInfo;
	
		
	 @ManyToOne
	 @JoinColumn(name = "TRANSACTION_ID")
   private CoreTransactions coreTransactions;
	
	@Column(name="ID_PROOF_TYPE", length = 100)
	private String idProofType;
	
	@Column(name="ID_PROOF_NUMBER", length = 100)
	private String idProofNumber;
	
	@Column(name="WALLET_TRX_TYPE1", length = 100)
	private String walletTrxType;
	
	@Column(name="CUST_WALLET_BALANCE")
	private Double custWalletBalance;
	
	@Column(name="DESCRIPTION",length = 200)
	private String description;
	
	@Column(name="WALLET_TXN_REF_NO",length = 200)
	private String walletTxnRefNo;
	
	@Column(name="WALLET_TXN_DATE")
	private Timestamp walletTxnDate;

	public CustomerWalletTransactions() {
	}

	public CustomerWalletTransactions(long custWalletTrxnId,
			CustomerWalletInfo customerWalletInfo,
			CoreTransactions coreTransactions) {
		this.custWalletTrxnId = custWalletTrxnId;
		this.customerWalletInfo = customerWalletInfo;
		this.coreTransactions = coreTransactions;
	}

	public CustomerWalletTransactions(long custWalletTrxnId,
			CustomerWalletInfo customerWalletInfo,
			CoreTransactions coreTransactions, String idProofType,
			String idProofNumber, String walletTrxType,
			Double custWalletBalance, String description,
			String walletTxnRefNo, Timestamp walletTxnDate) {
		this.custWalletTrxnId = custWalletTrxnId;
		this.customerWalletInfo = customerWalletInfo;
		this.coreTransactions = coreTransactions;
		this.idProofType = idProofType;
		this.idProofNumber = idProofNumber;
		this.walletTrxType = walletTrxType;
		this.custWalletBalance = custWalletBalance;
		this.description = description;
		this.walletTxnRefNo = walletTxnRefNo;
		this.walletTxnDate = walletTxnDate;
	}

	public long getCustWalletTrxnId() {
		return this.custWalletTrxnId;
	}

	public void setCustWalletTrxnId(long custWalletTrxnId) {
		this.custWalletTrxnId = custWalletTrxnId;
	}

	public CustomerWalletInfo getCustomerWalletInfo() {
		return this.customerWalletInfo;
	}

	public void setCustomerWalletInfo(CustomerWalletInfo customerWalletInfo) {
		this.customerWalletInfo = customerWalletInfo;
	}

	public CoreTransactions getCoreTransactions() {
		return this.coreTransactions;
	}

	public void setCoreTransactions(CoreTransactions coreTransactions) {
		this.coreTransactions = coreTransactions;
	}

	public String getIdProofType() {
		return this.idProofType;
	}

	public void setIdProofType(String idProofType) {
		this.idProofType = idProofType;
	}

	public String getIdProofNumber() {
		return this.idProofNumber;
	}

	public void setIdProofNumber(String idProofNumber) {
		this.idProofNumber = idProofNumber;
	}

	public String getWalletTrxType() {
		return walletTrxType;
	}

	public void setWalletTrxType(String walletTrxType) {
		this.walletTrxType = walletTrxType;
	}

	public Double getCustWalletBalance() {
		return this.custWalletBalance;
	}

	public void setCustWalletBalance(Double custWalletBalance) {
		this.custWalletBalance = custWalletBalance;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getWalletTxnRefNo() {
		return this.walletTxnRefNo;
	}

	public void setWalletTxnRefNo(String walletTxnRefNo) {
		this.walletTxnRefNo = walletTxnRefNo;
	}

	public Timestamp getWalletTxnDate() {
		return this.walletTxnDate;
	}

	public void setWalletTxnDate(Timestamp walletTxnDate) {
		this.walletTxnDate = walletTxnDate;
	}

}
