package com.fidypay.entity;

// Generated Apr 18, 2015 4:15:37 PM by Hibernate Tools 4.0.0

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * CustomerSubscriptions generated by hbm2java
 */

@Entity
@Table(name = "CUSTOMER_SUBSCRIPTIONS")
@EntityListeners(AuditingEntityListener.class)
public class CustomerSubscriptions implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "SUBSCRIPTION_ID")
	private long subscriptionId;
	
     @ManyToOne
	 @JoinColumn(name = "CUSTOMER_ID")
     private Customers customers;
	
		
	 @ManyToOne
	 @JoinColumn(name = "SERVICE_ID")
	private ServiceInfo serviceInfo;
	
	@Column(name="SUBSCRIPTION_BILLER", length = 100)
	private String subscriptionBiller;
	
	@Column(name="SUBSCRIPTION_ACCOUNT_NO", nullable = false, length = 100)
	private String subscriptionAccountNo;
	
	@Column(name="SUBSCRIPTION_AMOUNT")
	private Double subscriptionAmount;
	
	@Column(name="SUBSCRIPTION_DETAILS", length = 200)
	private String subscriptionDetails;
	
	@Column(name="SUBSCRIPTION_BILL_DATE")
	private Timestamp subscriptionBillDate;
	
	@Column(name="SUBSCRIPTION_FREQUENCY", length = 20)
	private String subscriptionFrequency;

	public CustomerSubscriptions() {
	}

	public CustomerSubscriptions(long subscriptionId, Customers customers,
			ServiceInfo serviceInfo, String subscriptionBiller,
			String subscriptionAccountNo) {
		this.subscriptionId = subscriptionId;
		this.customers = customers;
		this.serviceInfo = serviceInfo;
		this.subscriptionBiller = subscriptionBiller;
		this.subscriptionAccountNo = subscriptionAccountNo;
	}

	public CustomerSubscriptions(long subscriptionId, Customers customers,
			ServiceInfo serviceInfo, String subscriptionBiller,
			String subscriptionAccountNo, Double subscriptionAmount,
			String subscriptionDetails, Timestamp subscriptionBillDate,
			String subscriptionFrequency) {
		this.subscriptionId = subscriptionId;
		this.customers = customers;
		this.serviceInfo = serviceInfo;
		this.subscriptionBiller = subscriptionBiller;
		this.subscriptionAccountNo = subscriptionAccountNo;
		this.subscriptionAmount = subscriptionAmount;
		this.subscriptionDetails = subscriptionDetails;
		this.subscriptionBillDate = subscriptionBillDate;
		this.subscriptionFrequency = subscriptionFrequency;
	}

	public long getSubscriptionId() {
		return this.subscriptionId;
	}

	public void setSubscriptionId(long subscriptionId) {
		this.subscriptionId = subscriptionId;
	}

	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	public ServiceInfo getServiceInfo() {
		return this.serviceInfo;
	}

	public void setServiceInfo(ServiceInfo serviceInfo) {
		this.serviceInfo = serviceInfo;
	}

	public String getSubscriptionBiller() {
		return this.subscriptionBiller;
	}

	public void setSubscriptionBiller(String subscriptionBiller) {
		this.subscriptionBiller = subscriptionBiller;
	}

	public String getSubscriptionAccountNo() {
		return this.subscriptionAccountNo;
	}

	public void setSubscriptionAccountNo(String subscriptionAccountNo) {
		this.subscriptionAccountNo = subscriptionAccountNo;
	}

	public Double getSubscriptionAmount() {
		return this.subscriptionAmount;
	}

	public void setSubscriptionAmount(Double subscriptionAmount) {
		this.subscriptionAmount = subscriptionAmount;
	}

	public String getSubscriptionDetails() {
		return this.subscriptionDetails;
	}

	public void setSubscriptionDetails(String subscriptionDetails) {
		this.subscriptionDetails = subscriptionDetails;
	}

	public Timestamp getSubscriptionBillDate() {
		return this.subscriptionBillDate;
	}

	public void setSubscriptionBillDate(Timestamp subscriptionBillDate) {
		this.subscriptionBillDate = subscriptionBillDate;
	}

	public String getSubscriptionFrequency() {
		return this.subscriptionFrequency;
	}

	public void setSubscriptionFrequency(String subscriptionFrequency) {
		this.subscriptionFrequency = subscriptionFrequency;
	}

}
