package com.fidypay.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

// Generated Apr 18, 2015 4:15:37 PM by Hibernate Tools 4.0.0

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "FEEDBACK")
@EntityListeners(AuditingEntityListener.class)
public class Feedback implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CONTACT_ID")
	private long contactId;
	
	@Column(name="CONTACT_FNAME", length = 200)
	private String contactFname;
	
	@Column(name="CONTACT_LNAME", length = 200)
	private String contactLname;
	
	@Column(name="CONTACT_EMAIL", length = 300)
	private String contactEmail;
	
	@Column(name="CONTACT_MESSAGE", length = 1000)
	private String contactMessage;
	
	@Column(name="CONTACT_COMPANY_NAME", length = 100)
	private String contactCompanyName;
	
	@Column(name="CONTACT_PHONE", length = 100)
	private String contactPhone;

	public Feedback() {
	}

	public Feedback(int contactId, String contactFname, String contactLname,
			String contactEmail, String contactMessage) {
		this.contactId = contactId;
		this.contactFname = contactFname;
		this.contactLname = contactLname;
		this.contactEmail = contactEmail;
		this.contactMessage = contactMessage;
	}

	public Feedback(int contactId, String contactFname, String contactLname,
			String contactEmail, String contactMessage,
			String contactCompanyName, String contactPhone) {
		this.contactId = contactId;
		this.contactFname = contactFname;
		this.contactLname = contactLname;
		this.contactEmail = contactEmail;
		this.contactMessage = contactMessage;
		this.contactCompanyName = contactCompanyName;
		this.contactPhone = contactPhone;
	}

	
	
	
	public long getContactId() {
		return contactId;
	}

	public void setContactId(long contactId) {
		this.contactId = contactId;
	}

	public String getContactFname() {
		return this.contactFname;
	}

	public void setContactFname(String contactFname) {
		this.contactFname = contactFname;
	}

	public String getContactLname() {
		return this.contactLname;
	}

	public void setContactLname(String contactLname) {
		this.contactLname = contactLname;
	}

	public String getContactEmail() {
		return this.contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	public String getContactMessage() {
		return this.contactMessage;
	}

	public void setContactMessage(String contactMessage) {
		this.contactMessage = contactMessage;
	}

	public String getContactCompanyName() {
		return this.contactCompanyName;
	}

	public void setContactCompanyName(String contactCompanyName) {
		this.contactCompanyName = contactCompanyName;
	}

	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

}
