package com.fidypay.entity;

// Generated Apr 18, 2015 4:15:37 PM by Hibernate Tools 4.0.0


import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * InboundNotification generated by hbm2java
 */

@Entity
@Table(name = "INBOUND_NOTIFICATION")
@EntityListeners(AuditingEntityListener.class)
public class InboundNotification implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "NOTIFICATION_ID")
	private long notificationId;
	
	@Column(name="NOTIFICATION_DATE", nullable = false)
	private Timestamp notificationDate;
	
	
	@Column(name="UPI_ORIGINAL_ORDER_ID",length = 200)
	private String upiOriginalOrderId;
	
	@Column(name="UPI_UTR",length = 200)
	private String upiUTR;
	
	@Column(name="UPI_SUB_MERCHANT_ID",length = 200)
	private String upiSubMerchantId;
	
	@Column(name="UPI_CALLBACK_DATA",length = 2000)
	private String upiCallBackData;
	
	@Column(name="MERCHANT_CALLBACK_DATA",length = 2000)
	private String merchantCallBackData;
	
	@Column(name="MERCHANT_CALLBACK_STATUS",length = 2000)
	private String merchantCallBackStatus;
	
	@Column(name="NOTIFICATION_STATUS",length = 45)
	private String notificationStatus;
	
	@Column(name="TRXN_TYPE",length = 45)
	private String trxnType;

	
	public InboundNotification() {
	}

	public InboundNotification(long notificationId, Timestamp notificationDate, String upiOriginalOrderId,
			String upiUTR, String upiSubMerchantId, String upiCallBackData, String merchantCallBackData,
			String merchantCallBackStatus, String notificationStatus, String trxnType) {
		super();
		this.notificationId = notificationId;
		this.notificationDate = notificationDate;
		this.upiOriginalOrderId = upiOriginalOrderId;
		this.upiUTR = upiUTR;
		this.upiSubMerchantId = upiSubMerchantId;
		this.upiCallBackData = upiCallBackData;
		this.merchantCallBackData = merchantCallBackData;
		this.merchantCallBackStatus = merchantCallBackStatus;
		this.notificationStatus = notificationStatus;
		this.trxnType = trxnType;
	}

	public long getNotificationId() {
		return notificationId;
	}

	public void setNotificationId(long notificationId) {
		this.notificationId = notificationId;
	}

	public Timestamp getNotificationDate() {
		return notificationDate;
	}

	public void setNotificationDate(Timestamp notificationDate) {
		this.notificationDate = notificationDate;
	}

	public String getUpiOriginalOrderId() {
		return upiOriginalOrderId;
	}

	public void setUpiOriginalOrderId(String upiOriginalOrderId) {
		this.upiOriginalOrderId = upiOriginalOrderId;
	}

	public String getUpiUTR() {
		return upiUTR;
	}

	public void setUpiUTR(String upiUTR) {
		this.upiUTR = upiUTR;
	}

	public String getUpiSubMerchantId() {
		return upiSubMerchantId;
	}

	public void setUpiSubMerchantId(String upiSubMerchantId) {
		this.upiSubMerchantId = upiSubMerchantId;
	}

	public String getUpiCallBackData() {
		return upiCallBackData;
	}

	public void setUpiCallBackData(String upiCallBackData) {
		this.upiCallBackData = upiCallBackData;
	}

	public String getMerchantCallBackData() {
		return merchantCallBackData;
	}

	public void setMerchantCallBackData(String merchantCallBackData) {
		this.merchantCallBackData = merchantCallBackData;
	}

	public String getMerchantCallBackStatus() {
		return merchantCallBackStatus;
	}

	public void setMerchantCallBackStatus(String merchantCallBackStatus) {
		this.merchantCallBackStatus = merchantCallBackStatus;
	}

	public String getNotificationStatus() {
		return notificationStatus;
	}

	public void setNotificationStatus(String notificationStatus) {
		this.notificationStatus = notificationStatus;
	}

	public String getTrxnType() {
		return trxnType;
	}

	public void setTrxnType(String trxnType) {
		this.trxnType = trxnType;
	}


}
