package com.fidypay.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

// Generated Apr 18, 2015 4:15:37 PM by Hibernate Tools 4.0.0

/**
 * MerchantTillPosAssignment generated by hbm2java
 */

@Entity
@Table(name = "MERCHANT_TILL_POS_ASSIGNMENT")
@EntityListeners(AuditingEntityListener.class)
public class MerchantTillPosAssignment implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "TILL_POS_ASSIGNMENT_ID")
	private long tillPosAssignmentId;
	
	 @ManyToOne
	 @JoinColumn(name = "MERCHANT_TILL_ID")
	private MerchantTills merchantTills;
	
	 @ManyToOne
	 @JoinColumn(name = "POS_ID")
	private PosDevices posDevices;
	
	@Column(name="IS_ACTIVE", length = 1)
	private Character isActive;

	public MerchantTillPosAssignment() {
	}

	public MerchantTillPosAssignment(long tillPosAssignmentId,
			MerchantTills merchantTills, PosDevices posDevices,Character isActive) {
		this.tillPosAssignmentId = tillPosAssignmentId;
		this.merchantTills = merchantTills;
		this.posDevices = posDevices;
		this.isActive= isActive;
	}

	public long getTillPosAssignmentId() {
		return this.tillPosAssignmentId;
	}

	public void setTillPosAssignmentId(long tillPosAssignmentId) {
		this.tillPosAssignmentId = tillPosAssignmentId;
	}

	public MerchantTills getMerchantTills() {
		return this.merchantTills;
	}

	public void setMerchantTills(MerchantTills merchantTills) {
		this.merchantTills = merchantTills;
	}

	public PosDevices getPosDevices() {
		return this.posDevices;
	}

	public void setPosDevices(PosDevices posDevices) {
		this.posDevices = posDevices;
	}

	public Character getIsActive() {
		return isActive;
	}

	public void setIsActive(Character isActive) {
		this.isActive = isActive;
	}
	
	

}
