package com.fidypay.entity;

// Generated Apr 18, 2015 4:15:37 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * MerchantType generated by hbm2java
 */

@Entity
@Table(name = "MERCHANT_TYPE")
@EntityListeners(AuditingEntityListener.class)
public class MerchantType implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MERCHANT_TYPE_ID")
	private long merchantTypeId;
	
	@Column(name="MERCHANT_TYPE_NAME", length = 200)
	private String merchantTypeName;
	
	@Column(name="MERCHANT_TYPE_DETAIL", length = 200)
	private String merchantTypeDetail;
		
	@OneToMany(mappedBy = "merchantType", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
     private Set<Merchants> merchantses = new HashSet<Merchants>(0);

	public MerchantType() {
	}

	public MerchantType(long merchantTypeId, String merchantTypeName) {
		this.merchantTypeId = merchantTypeId;
		this.merchantTypeName = merchantTypeName;
	}

	public MerchantType(long merchantTypeId, String merchantTypeName,
			String merchantTypeDetail, Set merchantses) {
		this.merchantTypeId = merchantTypeId;
		this.merchantTypeName = merchantTypeName;
		this.merchantTypeDetail = merchantTypeDetail;
		this.merchantses = merchantses;
	}

	public long getMerchantTypeId() {
		return this.merchantTypeId;
	}

	public void setMerchantTypeId(long merchantTypeId) {
		this.merchantTypeId = merchantTypeId;
	}

	public String getMerchantTypeName() {
		return this.merchantTypeName;
	}

	public void setMerchantTypeName(String merchantTypeName) {
		this.merchantTypeName = merchantTypeName;
	}

	public String getMerchantTypeDetail() {
		return this.merchantTypeDetail;
	}

	public void setMerchantTypeDetail(String merchantTypeDetail) {
		this.merchantTypeDetail = merchantTypeDetail;
	}

	public Set getMerchantses() {
		return this.merchantses;
	}

	public void setMerchantses(Set merchantses) {
		this.merchantses = merchantses;
	}

}
