package com.fidypay.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

// Generated Jun 30, 2015 7:57:33 PM by Hibernate Tools 4.0.0

/**
 * MerchantTransactions generated by hbm2java
 */

@Entity
@Table(name = "MERCHANT_TRANSACTIONS")
@EntityListeners(AuditingEntityListener.class)
public class MerchantTransactions implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MERCHANT_TRXN_ID")
	private long merchantTrxnId;

	@ManyToOne
	@JoinColumn(name = "MERCHANT_OUTLET_TILL_ID")
	private MerchantOutletTills merchantOutletTills;

	@ManyToOne
	@JoinColumn(name = "MERCHANT_ID")
	private Merchants merchants;

	@ManyToOne
	@JoinColumn(name = "TRANSACTION_ID")
	private CoreTransactions coreTransactions;

	@ManyToOne
	@JoinColumn(name = "POS_ID")
	private PosDevices posDevices;

	@Column(name = "MERCHANT_COMISSION")
	private Double merchantComission;

	@Column(name = "MERCHANT_TRXN_REF_ID", length = 200)
	private String merchantTrxnRefId;

	@Column(name = "IS_SETTLED", nullable = false)
	private Character isSettled;

	@Column(name = "IS_RECONCILE", nullable = false)
	private Character isReconcile;

	public MerchantTransactions() {
	}

	public MerchantTransactions(long merchantTrxnId, MerchantOutletTills merchantOutletTills, Merchants merchants,
			CoreTransactions coreTransactions) {
		this.merchantTrxnId = merchantTrxnId;
		this.merchantOutletTills = merchantOutletTills;
		this.merchants = merchants;
		this.coreTransactions = coreTransactions;
	}

	public MerchantTransactions(long merchantTrxnId, MerchantOutletTills merchantOutletTills, Merchants merchants,
			CoreTransactions coreTransactions, PosDevices posDevices, Double merchantComission) {
		this.merchantTrxnId = merchantTrxnId;
		this.merchantOutletTills = merchantOutletTills;
		this.merchants = merchants;
		this.coreTransactions = coreTransactions;
		this.posDevices = posDevices;
		this.merchantComission = merchantComission;
	}

	public long getMerchantTrxnId() {
		return this.merchantTrxnId;
	}

	public void setMerchantTrxnId(long merchantTrxnId) {
		this.merchantTrxnId = merchantTrxnId;
	}

	public MerchantOutletTills getMerchantOutletTills() {
		return this.merchantOutletTills;
	}

	public void setMerchantOutletTills(MerchantOutletTills merchantOutletTills) {
		this.merchantOutletTills = merchantOutletTills;
	}

	public Merchants getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchants merchants) {
		this.merchants = merchants;
	}

	public CoreTransactions getCoreTransactions() {
		return this.coreTransactions;
	}

	public void setCoreTransactions(CoreTransactions coreTransactions) {
		this.coreTransactions = coreTransactions;
	}

	public PosDevices getPosDevices() {
		return this.posDevices;
	}

	public void setPosDevices(PosDevices posDevices) {
		this.posDevices = posDevices;
	}

	public Double getMerchantComission() {
		return this.merchantComission;
	}

	public void setMerchantComission(Double merchantComission) {
		this.merchantComission = merchantComission;
	}

	public String getMerchantTrxnRefId() {
		return merchantTrxnRefId;
	}

	public void setMerchantTrxnRefId(String merchantTrxnRefId) {
		this.merchantTrxnRefId = merchantTrxnRefId;
	}

	public Character getIsSettled() {
		return isSettled;
	}

	public void setIsSettled(Character isSettled) {
		this.isSettled = isSettled;
	}

	public Character getIsReconcile() {
		return isReconcile;
	}

	public void setIsReconcile(Character isReconcile) {
		this.isReconcile = isReconcile;
	}

}
