package com.fidypay.entity;

// Generated Oct 29, 2015 6:39:28 PM by Hibernate Tools 4.0.0

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * MerchantTillTxn generated by hbm2java
 */

@Entity
@Table(name = "MERCHANT_TILL_LOGIN_INFO")
@EntityListeners(AuditingEntityListener.class)
public class MerchantTillLoginInfo implements java.io.Serializable {

	/**
	 * 
	 */
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "LOGIN_INFO_ID")
	private long LoginInfoID;
	// private long merchantTillID;
	
	@Column(name="SESSION_KEY", length = 1000)
	private String SessionKey;
	
	@Column(name="IS_USED", length = 1)
	private Character isUsed;
	
	@Column(name="IS_EXPIRED", length = 1)
	private Character isExpired;
		
	 @ManyToOne
	 @JoinColumn(name = "MERCHANT_TILL_ID")
	private MerchantTills merchantTills;

	public MerchantTillLoginInfo() {
	}

	public MerchantTillLoginInfo(long LoginInfoID) {
		this.setLoginInfoID(LoginInfoID);
	}

	public MerchantTillLoginInfo(long LoginInfoID, MerchantTills merchantTills, String SessionKey, Character isUsed,
			Character isExpired) {
		this.setLoginInfoID(LoginInfoID);
		this.setMerchantTills(merchantTills);
		this.setSessionKey(SessionKey);
		this.setIsUsed(isUsed);
		this.setIsExpired(isExpired);
	}

	/**
	 * @return the loginInfoID
	 */
	public long getLoginInfoID() {
		return LoginInfoID;
	}

	/**
	 * @param loginInfoID the loginInfoID to set
	 */
	public void setLoginInfoID(long loginInfoID) {
		LoginInfoID = loginInfoID;
	}

	/**
	 * @return the sessionKey
	 */
	public String getSessionKey() {
		return SessionKey;
	}

	/**
	 * @param sessionKey the sessionKey to set
	 */
	public void setSessionKey(String sessionKey) {
		SessionKey = sessionKey;
	}

	
	
	/**
	 * @return the merchantTillID
	 */
	/*
	 * public long getMerchantTillID() { return merchantTillID; }
	 * 
	 *//**
		 * @param merchantTillID the merchantTillID to set
		 *//*
			 * public void setMerchantTillID(long merchantTillID) { this.merchantTillID =
			 * merchantTillID; }
			 */

	public MerchantTills getMerchantTills() {
		return merchantTills;
	}

	public void setMerchantTills(MerchantTills merchantTills) {
		this.merchantTills = merchantTills;
	}

	/**
	 * @return the isUsed
	 */
	public Character getIsUsed() {
		return isUsed;
	}

	/**
	 * @param isUsed the isUsed to set
	 */
	public void setIsUsed(Character isUsed) {
		this.isUsed = isUsed;
	}

	/**
	 * @return the isExpired
	 */
	public Character getIsExpired() {
		return isExpired;
	}

	/**
	 * @param isExpired the isExpired to set
	 */
	public void setIsExpired(Character isExpired) {
		this.isExpired = isExpired;
	}

}