package com.fidypay.entity;

// Generated Jun 30, 2015 7:57:33 PM by Hibernate Tools 4.0.0

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * MerchantReconciliation generated by hbm2java
 */

@Entity
@Table(name = "MERCHANT_RECONCILIATION")
@EntityListeners(AuditingEntityListener.class)
public class MerchantReconciliation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MERCHANT_RECON_ID")
	private long merchantReconId;

	@ManyToOne
	@JoinColumn(name = "MERCHANT_TILL_ID")
	private MerchantTills merchantTills;

	@ManyToOne
	@JoinColumn(name = "MERCHANT_ID")
	private Merchants merchants;

	@Column(name = "MERCHANT_SHARE")
	private Double merchantShare;

	@Column(name = "RECONCILIATION_DATE")
	private Timestamp reconciliationDate;

	@Column(name = "RECONCILIATION_DETAILS", length = 300)
	private String reconciliationDetails;

	@Column(name = "RECON_TOTAL_AMOUNT")
	private Double reconTotalAmount;

	@Column(name = "IS_VERIFIED", length = 1)
	private Character isVerified;

	@Column(name = "IS_SETTELED", length = 1)
	private Character isSetteled;

	public MerchantReconciliation() {
	}

	public MerchantReconciliation(long merchantReconId, Merchants merchants) {
		this.merchantReconId = merchantReconId;
		this.merchants = merchants;
	}

	public MerchantReconciliation(long merchantReconId, MerchantTills merchantTills, Merchants merchants,
			Double merchantShare, Timestamp reconciliationDate, String reconciliationDetails, Double reconTotalAmount,
			Character isVerified, Character isSetteled) {
		this.merchantReconId = merchantReconId;
		this.merchantTills = merchantTills;
		this.merchants = merchants;
		this.merchantShare = merchantShare;
		this.reconciliationDate = reconciliationDate;
		this.reconciliationDetails = reconciliationDetails;
		this.reconTotalAmount = reconTotalAmount;
		this.isVerified = isVerified;
		this.isSetteled = isSetteled;
	}

	public long getMerchantReconId() {
		return this.merchantReconId;
	}

	public void setMerchantReconId(long merchantReconId) {
		this.merchantReconId = merchantReconId;
	}

	public MerchantTills getMerchantTills() {
		return this.merchantTills;
	}

	public void setMerchantTills(MerchantTills merchantTills) {
		this.merchantTills = merchantTills;
	}

	public Merchants getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchants merchants) {
		this.merchants = merchants;
	}

	public Double getMerchantShare() {
		return this.merchantShare;
	}

	public void setMerchantShare(Double merchantShare) {
		this.merchantShare = merchantShare;
	}

	public Timestamp getReconciliationDate() {
		return this.reconciliationDate;
	}

	public void setReconciliationDate(Timestamp reconciliationDate) {
		this.reconciliationDate = reconciliationDate;
	}

	public String getReconciliationDetails() {
		return this.reconciliationDetails;
	}

	public void setReconciliationDetails(String reconciliationDetails) {
		this.reconciliationDetails = reconciliationDetails;
	}

	public Double getReconTotalAmount() {
		return this.reconTotalAmount;
	}

	public void setReconTotalAmount(Double reconTotalAmount) {
		this.reconTotalAmount = reconTotalAmount;
	}

	public Character getIsVerified() {
		return this.isVerified;
	}

	public void setIsVerified(Character isVerified) {
		this.isVerified = isVerified;
	}

	public Character getIsSetteled() {
		return this.isSetteled;
	}

	public void setIsSetteled(Character isSetteled) {
		this.isSetteled = isSetteled;
	}

}
