package com.fidypay.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

// Generated Apr 10, 2015 4:46:25 PM by Hibernate Tools 4.0.0

/**
 * MerchantServices generated by hbm2java
 */

@Entity
@Table(name = "MERCHANT_SERVICES")
@EntityListeners(AuditingEntityListener.class)
public class MerchantServices implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MERCHANT_SERVICE_ID")
	private long merchantServiceId;
	
	
	
	@ManyToOne
    @JoinColumn(name = "MERCHANT_ID")
    private Merchants merchants;
    
	
    
	@ManyToOne
    @JoinColumn(name = "SERVICE_ID")
     private ServiceInfo serviceInfo;
	
	@Column(name="COMMISION")
	private Double commision;
	
    
	@ManyToOne
    @JoinColumn(name = "MERCHANT_OUTLET_ID")
    private MerchantOutlets merchantOutlets;

	public MerchantServices() {
	}

	public MerchantServices(long merchantServiceId, Merchants merchants,
			ServiceInfo serviceInfo, MerchantOutlets merchantOutlets) {
		this.merchantServiceId = merchantServiceId;
		this.merchants = merchants;
		this.serviceInfo = serviceInfo;
		this.merchantOutlets = merchantOutlets;
	}

	public MerchantServices(long merchantServiceId, Merchants merchants,
			ServiceInfo serviceInfo, Double commision, MerchantOutlets merchantOutlets) {
		this.merchantServiceId = merchantServiceId;
		this.merchants = merchants;
		this.serviceInfo = serviceInfo;
		this.commision = commision;
		this.merchantOutlets = merchantOutlets;
	}

	
	public long getMerchantServiceId() {
		return merchantServiceId;
	}

	public void setMerchantServiceId(long merchantServiceId) {
		this.merchantServiceId = merchantServiceId;
	}

	public Merchants getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchants merchants) {
		this.merchants = merchants;
	}

	public ServiceInfo getServiceInfo() {
		return this.serviceInfo;
	}

	public void setServiceInfo(ServiceInfo serviceInfo) {
		this.serviceInfo = serviceInfo;
	}

	public Double getCommision() {
		return this.commision;
	}

	public void setCommision(Double commision) {
		this.commision = commision;
	}

	public MerchantOutlets getMerchantOutlets() {
		return merchantOutlets;
	}

	public void setMerchantOutlets(MerchantOutlets merchantOutlets) {
		this.merchantOutlets = merchantOutlets;
	}
	
	

}
