package com.fidypay.entity;

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * MerchantOutlets generated by hbm2java
 */

@Entity
@Table(name = "MERCHANT_OUTLET")
@EntityListeners(AuditingEntityListener.class)
public class MerchantOutlets implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MERCHANT_OUTLET_ID")
	private long merchantOutletId;
	
	
	  @ManyToOne
	 @JoinColumn(name = "MERCHANT_ID")
     private Merchants merchants;
	
	@Column(name="OUTLET_CODE", length = 100)
	private String outletCode;
	
	@Column(name="OUTLET_CONTACT_NAME", length = 100)
	private String outletContactName;
	
	@Column(name="OUTLET_ADDRESS", length = 200)
	private String outletAddress;
	
	@Column(name="OUTLET_CITY", length = 100)
	private String outletCity;
	
	@Column(name="OUTLET_STATE", length = 100)
	private String outletState;
	
	@Column(name="OUTLET_COUNTRY", length = 100)
	private String outletCountry;
	
	@Column(name="OUTLET_ZIPCODE", length = 50)
	private String outletZipcode;
	
	@Column(name="OUTLET_FROMDATE")
	private Timestamp outletFromdate;
	
	@Column(name="OUTLET_IS_ACTIE",length = 1)
	private Character outletIsActie;
	
	@Column(name="OUTLET_IS_VERIFIED", length = 1)
	private Character outletIsVerified;
	
	@Column(name="OUTLET_CONTACT_NUMBER", length = 50)
	private String outletContactNumber;
	
	@Column(name="OUTLET_TYPE", length = 20)
	private String outletType;
	
	@Column(name="OUTLET_COORDINATES", length = 100)
	private String outletCoordinates;
	
	
	  @OneToMany(mappedBy = "merchantOutlets", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantOutletTills> merchantOutletTillses = new HashSet<MerchantOutletTills>(0);
	
		
	  @OneToMany(mappedBy = "merchantOutlets", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantServices> merchantServiceses = new HashSet<MerchantServices>(0);

	public MerchantOutlets() {
	}

	public MerchantOutlets(long merchantOutletId, Merchants merchants,
			String outletCode) {
		this.merchantOutletId = merchantOutletId;
		this.merchants = merchants;
		this.outletCode = outletCode;
	}

	public MerchantOutlets(long merchantOutletId, Merchants merchants,
			String outletCode, String outletContactName, String outletAddress,
			String outletCity, String outletState, String outletCountry,
			String outletZipcode, Timestamp outletFromdate,
			Character outletIsActie, Character outletIsVerified,
			String outletContactNumber, String outletType,
			String outletCoordinates, Set merchantOutletTillses, Set merchantServiceses) {
		this.merchantOutletId = merchantOutletId;
		this.merchants = merchants;
		this.outletCode = outletCode;
		this.outletContactName = outletContactName;
		this.outletAddress = outletAddress;
		this.outletCity = outletCity;
		this.outletState = outletState;
		this.outletCountry = outletCountry;
		this.outletZipcode = outletZipcode;
		this.outletFromdate = outletFromdate;
		this.outletIsActie = outletIsActie;
		this.outletIsVerified = outletIsVerified;
		this.outletContactNumber = outletContactNumber;
		this.outletType = outletType;
		this.outletCoordinates = outletCoordinates;
		this.merchantOutletTillses = merchantOutletTillses;
		this.merchantServiceses  = merchantServiceses;
	}

	public long getMerchantOutletId() {
		return this.merchantOutletId;
	}

	public void setMerchantOutletId(long merchantOutletId) {
		this.merchantOutletId = merchantOutletId;
	}

	public Merchants getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchants merchants) {
		this.merchants = merchants;
	}

	public String getOutletCode() {
		return this.outletCode;
	}

	public void setOutletCode(String outletCode) {
		this.outletCode = outletCode;
	}

	public String getOutletContactName() {
		return this.outletContactName;
	}

	public void setOutletContactName(String outletContactName) {
		this.outletContactName = outletContactName;
	}

	public String getOutletAddress() {
		return this.outletAddress;
	}

	public void setOutletAddress(String outletAddress) {
		this.outletAddress = outletAddress;
	}

	public String getOutletCity() {
		return this.outletCity;
	}

	public void setOutletCity(String outletCity) {
		this.outletCity = outletCity;
	}

	public String getOutletState() {
		return this.outletState;
	}

	public void setOutletState(String outletState) {
		this.outletState = outletState;
	}

	public String getOutletCountry() {
		return this.outletCountry;
	}

	public void setOutletCountry(String outletCountry) {
		this.outletCountry = outletCountry;
	}

	public String getOutletZipcode() {
		return this.outletZipcode;
	}

	public void setOutletZipcode(String outletZipcode) {
		this.outletZipcode = outletZipcode;
	}

	public Timestamp getOutletFromdate() {
		return this.outletFromdate;
	}

	public void setOutletFromdate(Timestamp outletFromdate) {
		this.outletFromdate = outletFromdate;
	}

	public Character getOutletIsActie() {
		return this.outletIsActie;
	}

	public void setOutletIsActie(Character outletIsActie) {
		this.outletIsActie = outletIsActie;
	}

	public Character getOutletIsVerified() {
		return this.outletIsVerified;
	}

	public void setOutletIsVerified(Character outletIsVerified) {
		this.outletIsVerified = outletIsVerified;
	}

	public String getOutletContactNumber() {
		return this.outletContactNumber;
	}

	public void setOutletContactNumber(String outletContactNumber) {
		this.outletContactNumber = outletContactNumber;
	}

	public String getOutletType() {
		return this.outletType;
	}

	public void setOutletType(String outletType) {
		this.outletType = outletType;
	}

	public String getOutletCoordinates() {
		return this.outletCoordinates;
	}

	public void setOutletCoordinates(String outletCoordinates) {
		this.outletCoordinates = outletCoordinates;
	}

	public Set getMerchantOutletTillses() {
		return this.merchantOutletTillses;
	}

	public void setMerchantOutletTillses(Set merchantOutletTillses) {
		this.merchantOutletTillses = merchantOutletTillses;
	}

	public Set getMerchantServiceses() {
		return merchantServiceses;
	}

	public void setMerchantServiceses(Set merchantServiceses) {
		this.merchantServiceses = merchantServiceses;
	}
	
	

}
