package com.fidypay.entity;

// Generated Apr 18, 2015 4:15:37 PM by Hibernate Tools 4.0.0


import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * MerchantAddonWalletInfo generated by hbm2java
 */

@Entity
@Table(name = "MERCHANT_ADDON_WALLET_INFO")
@EntityListeners(AuditingEntityListener.class)
public class MerchantAddonWalletInfo implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MERCHANT_ADDON_WALLET_ID")
	private long merchantAddonWalletId;
	
		
	 @ManyToOne
	 @JoinColumn(name = "MERCHANT_ID")
    private Merchants merchants;
	
		
	 @ManyToOne
	 @JoinColumn(name = "CUSTOMER_ID")
     private Customers customers;
	
	@Column(name="WALLET_FROM_DATE")
	private Timestamp walletFromDate;
	
	@Column(name="WALLET_TO_DATE")
	private Timestamp walletToDate;
	
	@Column(name="IS_CUST_MAPPED", length = 1)
	private Character isCustMapped;

	public MerchantAddonWalletInfo() {
	}

	public MerchantAddonWalletInfo(long merchantAddonWalletId,
			Merchants merchants, Customers customers) {
		this.merchantAddonWalletId = merchantAddonWalletId;
		this.merchants = merchants;
		this.customers = customers;
	}

	public MerchantAddonWalletInfo(long merchantAddonWalletId,
			Merchants merchants, Customers customers,
			Timestamp walletFromDate, Timestamp walletToDate,
			Character isCustMapped) {
		this.merchantAddonWalletId = merchantAddonWalletId;
		this.merchants = merchants;
		this.customers = customers;
		this.walletFromDate = walletFromDate;
		this.walletToDate = walletToDate;
		this.isCustMapped = isCustMapped;
	}

	public long getMerchantAddonWalletId() {
		return this.merchantAddonWalletId;
	}

	public void setMerchantAddonWalletId(long merchantAddonWalletId) {
		this.merchantAddonWalletId = merchantAddonWalletId;
	}

	public Merchants getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchants merchants) {
		this.merchants = merchants;
	}

	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	public Timestamp getWalletFromDate() {
		return this.walletFromDate;
	}

	public void setWalletFromDate(Timestamp walletFromDate) {
		this.walletFromDate = walletFromDate;
	}

	public Timestamp getWalletToDate() {
		return this.walletToDate;
	}

	public void setWalletToDate(Timestamp walletToDate) {
		this.walletToDate = walletToDate;
	}

	public Character getIsCustMapped() {
		return this.isCustMapped;
	}

	public void setIsCustMapped(Character isCustMapped) {
		this.isCustMapped = isCustMapped;
	}

}
