package com.fidypay.entity;

// Generated Oct 29, 2015 6:39:28 PM by Hibernate Tools 4.0.0


import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * MerchantTillTxn generated by hbm2java
 */

@Entity
@Table(name = "MERCHANT_TILL_TXN")
@EntityListeners(AuditingEntityListener.class)
public class MerchantTillTxn implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MERCHANT_TILL_TXN_ID")
	private long merchantTillTxnId;
	
	@ManyToOne
    @JoinColumn(name = "MERCHANT_TILL_ID")
    private MerchantTills merchantTills;
	
	
	@Column(name="DESCRIPTION", length = 500)
	private String description;
	
	@Column(name="TXN_REF_NO", length = 100)
	private String txnRefNo;
	
	@Column(name="TXN_TYPE", length = 100)
	private String txnType;
	
	@Column(name="TXN_DATE")
	private Timestamp txnDate;
	
	@Column(name="TXN_AMOUNT")
	private Double txnAmount;
	
	@Column(name="FLOAT_BALANCE")
	private Double floatBalance;
	
	@Column(name="RECEIVED_AMOUNT")
	private Double receivedAmount;
	
	@Column(name="PAY_MODE", length = 100)
	private String payMode;
	
	@Column(name="IS_REVERTED", length = 1)
	private Character isReverted;

	public MerchantTillTxn() {
	}

	public MerchantTillTxn(long merchantTillTxnId) {
		this.merchantTillTxnId = merchantTillTxnId;
	}

	public MerchantTillTxn(long merchantTillTxnId, MerchantTills merchantTills,
			String description, String txnRefNo, String txnType,
			Timestamp txnDate, Double txnAmount, Double floatBalance,
			Double receivedAmount, String payMode, Character isReverted) {
		this.merchantTillTxnId = merchantTillTxnId;
		this.merchantTills = merchantTills;
		this.description = description;
		this.txnRefNo = txnRefNo;
		this.txnType = txnType;
		this.txnDate = txnDate;
		this.txnAmount = txnAmount;
		this.floatBalance = floatBalance;
		this.receivedAmount = receivedAmount;
		this.payMode = payMode;
		this.isReverted = isReverted;
	}

	public long getMerchantTillTxnId() {
		return this.merchantTillTxnId;
	}

	public void setMerchantTillTxnId(long merchantTillTxnId) {
		this.merchantTillTxnId = merchantTillTxnId;
	}

	public MerchantTills getMerchantTills() {
		return this.merchantTills;
	}

	public void setMerchantTills(MerchantTills merchantTills) {
		this.merchantTills = merchantTills;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTxnRefNo() {
		return this.txnRefNo;
	}

	public void setTxnRefNo(String txnRefNo) {
		this.txnRefNo = txnRefNo;
	}

	public String getTxnType() {
		return this.txnType;
	}

	public void setTxnType(String txnType) {
		this.txnType = txnType;
	}

	public Timestamp getTxnDate() {
		return this.txnDate;
	}

	public void setTxnDate(Timestamp txnDate) {
		this.txnDate = txnDate;
	}

	public Double getTxnAmount() {
		return this.txnAmount;
	}

	public void setTxnAmount(Double txnAmount) {
		this.txnAmount = txnAmount;
	}

	public Double getFloatBalance() {
		return this.floatBalance;
	}

	public void setFloatBalance(Double floatBalance) {
		this.floatBalance = floatBalance;
	}

	public Double getReceivedAmount() {
		return this.receivedAmount;
	}

	public void setReceivedAmount(Double receivedAmount) {
		this.receivedAmount = receivedAmount;
	}

	public String getPayMode() {
		return this.payMode;
	}

	public void setPayMode(String payMode) {
		this.payMode = payMode;
	}

	public Character getIsReverted() {
		return this.isReverted;
	}

	public void setIsReverted(Character isReverted) {
		this.isReverted = isReverted;
	}

}
