package com.fidypay.entity;

// Generated Jul 8, 2015 4:35:53 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * PaymentChannelOptions generated by hbm2java
 */
@Entity
@Table(name = "PAYMENT_CHANNEL_OPTIONS")
@EntityListeners(AuditingEntityListener.class)
public class PaymentChannelOptions  {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "PC_OPTION_ID")
	private long pcOptionId;
	
	@ManyToOne
	@JoinColumn(name = "PAYMENT_CHANNEL_ID")
	private PaymentChannels paymentChannels;
	
	@ManyToOne
	@JoinColumn(name = "API_ID")
	private ApiInfo apiInfo;
	
	@Column(name="PC_OPTION_NAME", length = 100)
	private String pcOptionName;
	
	@Column(name="PC_OPTION_DETAILS", length = 200)
	private String pcOptionDetails;
	
	@Column(name="PC_COMMISION")
	private Double pcCommision;
	
	@OneToMany(mappedBy = "paymentChannelOptions", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	  private Set<CoreTransactions> coreTransactionses = new HashSet<CoreTransactions>(0);
	
    @OneToMany(mappedBy = "paymentChannelOptions", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	  private Set<MerchantPaymentChannels> merchantPaymentChannelses = new HashSet<MerchantPaymentChannels>(0);
	
	@OneToMany(mappedBy = "paymentChannelOptions", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	   private Set<PaymentChannelReconciliation> paymentChannelReconciliations = new HashSet<PaymentChannelReconciliation>(0);

	public PaymentChannelOptions() {
	}

	public PaymentChannelOptions(long pcOptionId) {
		this.pcOptionId=pcOptionId;
	}

	public PaymentChannelOptions(long pcOptionId,
			PaymentChannels paymentChannels, ApiInfo apiInfo) {
		this.pcOptionId = pcOptionId;
		this.paymentChannels = paymentChannels;
		this.apiInfo = apiInfo;
	}

	public PaymentChannelOptions(long pcOptionId,
			PaymentChannels paymentChannels, ApiInfo apiInfo,
			String pcOptionName, String pcOptionDetails, Double pcCommision,
			Set coreTransactionses, Set merchantPaymentChannelses,
			Set paymentChannelReconciliations) {
		this.pcOptionId = pcOptionId;
		this.paymentChannels = paymentChannels;
		this.apiInfo = apiInfo;
		this.pcOptionName = pcOptionName;
		this.pcOptionDetails = pcOptionDetails;
		this.pcCommision = pcCommision;
		this.coreTransactionses = coreTransactionses;
		this.merchantPaymentChannelses = merchantPaymentChannelses;
		this.paymentChannelReconciliations = paymentChannelReconciliations;
	}

	public long getPcOptionId() {
		return this.pcOptionId;
	}

	public void setPcOptionId(long pcOptionId) {
		this.pcOptionId = pcOptionId;
	}

	public PaymentChannels getPaymentChannels() {
		return this.paymentChannels;
	}

	public void setPaymentChannels(PaymentChannels paymentChannels) {
		this.paymentChannels = paymentChannels;
	}

	public ApiInfo getApiInfo() {
		return this.apiInfo;
	}

	public void setApiInfo(ApiInfo apiInfo) {
		this.apiInfo = apiInfo;
	}

	public String getPcOptionName() {
		return this.pcOptionName;
	}

	public void setPcOptionName(String pcOptionName) {
		this.pcOptionName = pcOptionName;
	}

	public String getPcOptionDetails() {
		return this.pcOptionDetails;
	}

	public void setPcOptionDetails(String pcOptionDetails) {
		this.pcOptionDetails = pcOptionDetails;
	}

	public Double getPcCommision() {
		return this.pcCommision;
	}

	public void setPcCommision(Double pcCommision) {
		this.pcCommision = pcCommision;
	}

	public Set getCoreTransactionses() {
		return this.coreTransactionses;
	}

	public void setCoreTransactionses(Set coreTransactionses) {
		this.coreTransactionses = coreTransactionses;
	}

	public Set getMerchantPaymentChannelses() {
		return this.merchantPaymentChannelses;
	}

	public void setMerchantPaymentChannelses(Set merchantPaymentChannelses) {
		this.merchantPaymentChannelses = merchantPaymentChannelses;
	}

	public Set getPaymentChannelReconciliations() {
		return this.paymentChannelReconciliations;
	}

	public void setPaymentChannelReconciliations(
			Set paymentChannelReconciliations) {
		this.paymentChannelReconciliations = paymentChannelReconciliations;
	}

}
