package com.fidypay.entity;

// Generated Jul 8, 2015 4:35:53 PM by Hibernate Tools 4.0.0

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * PaymentChannelReconciliation generated by hbm2java
 */

@Entity
@Table(name = "PAYMENT_CHANNEL_RECONCILIATION")
@EntityListeners(AuditingEntityListener.class)
public class PaymentChannelReconciliation implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "PC_RECON_ID")
	private long pcReconId;

	@ManyToOne
	@JoinColumn(name = "PC_OPTION_ID")
	private PaymentChannelOptions paymentChannelOptions;

	@ManyToOne
	@JoinColumn(name = "PAYMENT_CHANNEL_ID")
	private PaymentChannels paymentChannels;

	@Column(name = "PC_SHARE", nullable = false, length = 100)
	private double pcShare;

	@Column(name = "RECONCILIATION_DATE")
	private Timestamp reconciliationDate;

	@Column(name = "RECONCILIATION_DETAILS", length = 300)
	private String reconciliationDetails;

	@Column(name = "RECON_TOTAL_AMOUNT")
	private Double reconTotalAmount;

	@Column(name = "IS_VERIFIED", length = 1)
	private Character isVerified;

	@Column(name = "IS_SETTELED", length = 1)
	private Character isSetteled;

	public PaymentChannelReconciliation() {
	}

	public PaymentChannelReconciliation(long pcReconId, PaymentChannels paymentChannels, double pcShare) {
		this.pcReconId = pcReconId;
		this.paymentChannels = paymentChannels;
		this.pcShare = pcShare;
	}

	public PaymentChannelReconciliation(long pcReconId, PaymentChannelOptions paymentChannelOptions,
			PaymentChannels paymentChannels, double pcShare, Timestamp reconciliationDate, String reconciliationDetails,
			Double reconTotalAmount, Character isVerified, Character isSetteled) {
		this.pcReconId = pcReconId;
		this.paymentChannelOptions = paymentChannelOptions;
		this.paymentChannels = paymentChannels;
		this.pcShare = pcShare;
		this.reconciliationDate = reconciliationDate;
		this.reconciliationDetails = reconciliationDetails;
		this.reconTotalAmount = reconTotalAmount;
		this.isVerified = isVerified;
		this.isSetteled = isSetteled;
	}

	public long getPcReconId() {
		return this.pcReconId;
	}

	public void setPcReconId(long pcReconId) {
		this.pcReconId = pcReconId;
	}

	public PaymentChannelOptions getPaymentChannelOptions() {
		return this.paymentChannelOptions;
	}

	public void setPaymentChannelOptions(PaymentChannelOptions paymentChannelOptions) {
		this.paymentChannelOptions = paymentChannelOptions;
	}

	public PaymentChannels getPaymentChannels() {
		return this.paymentChannels;
	}

	public void setPaymentChannels(PaymentChannels paymentChannels) {
		this.paymentChannels = paymentChannels;
	}

	public double getPcShare() {
		return this.pcShare;
	}

	public void setPcShare(double pcShare) {
		this.pcShare = pcShare;
	}

	public Timestamp getReconciliationDate() {
		return this.reconciliationDate;
	}

	public void setReconciliationDate(Timestamp reconciliationDate) {
		this.reconciliationDate = reconciliationDate;
	}

	public String getReconciliationDetails() {
		return this.reconciliationDetails;
	}

	public void setReconciliationDetails(String reconciliationDetails) {
		this.reconciliationDetails = reconciliationDetails;
	}

	public Double getReconTotalAmount() {
		return this.reconTotalAmount;
	}

	public void setReconTotalAmount(Double reconTotalAmount) {
		this.reconTotalAmount = reconTotalAmount;
	}

	public Character getIsVerified() {
		return this.isVerified;
	}

	public void setIsVerified(Character isVerified) {
		this.isVerified = isVerified;
	}

	public Character getIsSetteled() {
		return this.isSetteled;
	}

	public void setIsSetteled(Character isSetteled) {
		this.isSetteled = isSetteled;
	}

}
