package com.fidypay.entity;

// Generated May 30, 2015 1:02:11 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * PaymentChannelTransactions generated by hbm2java
 */

@Entity
@Table(name = "PAYMENT_CHANNEL_TRANSACTIONS")
@EntityListeners(AuditingEntityListener.class)
public class PaymentChannelTransactions implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "PC_TRANSACTION_ID")
	private long pcTransactionId;
	
	@ManyToOne
    @JoinColumn(name = "PAYMENT_CHANNEL_ID")
     private PaymentChannels paymentChannels;
		
	@ManyToOne
    @JoinColumn(name = "TRANSACTION_ID")
    private CoreTransactions coreTransactions;
	
	@Column(name="PC_TRAN_REF_ID", length = 50)
	private String pcTranRefId;
	
	@Column(name="PC_GATEWAY_REF_ID", length = 50)
	private String pcGatewayRefId;
	
	@Column(name="PC_TRAN_STATUS", length = 20)
	private String pcTranStatus;
	
	@Column(name="PC_TRAN_MSG", length = 200)
	private String pcTranMsg;
	
	@Column(name="PC_TRAN_PARAMETER", length = 100)
	private String pcTranParameter;
	
	@Column(name="IS_SETTLED", nullable = false)
	private Character isSettled;

	@Column(name="IS_RECONCILE", nullable = false)
	private Character isReconcile;
	 
	 @OneToMany(mappedBy = "paymentChannelTransactions", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
     private Set<PaymentChannelRefund> paymentChannelRefunds = new HashSet<PaymentChannelRefund>(0);

	public PaymentChannelTransactions() {
	}

	public PaymentChannelTransactions(long pcTransactionId,
			PaymentChannels paymentChannels, CoreTransactions coreTransactions) {
		this.pcTransactionId = pcTransactionId;
		this.paymentChannels = paymentChannels;
		this.coreTransactions = coreTransactions;
	}

	public PaymentChannelTransactions(long pcTransactionId,
			PaymentChannels paymentChannels, CoreTransactions coreTransactions,
			String pcTranRefId, String pcGatewayRefId, String pcTranStatus,
			String pcTranMsg, String pcTranParameter, Set paymentChannelRefunds) {
		this.pcTransactionId = pcTransactionId;
		this.paymentChannels = paymentChannels;
		this.coreTransactions = coreTransactions;
		this.pcTranRefId = pcTranRefId;
		this.pcGatewayRefId = pcGatewayRefId;
		this.pcTranStatus = pcTranStatus;
		this.pcTranMsg = pcTranMsg;
		this.pcTranParameter = pcTranParameter;
		this.paymentChannelRefunds = paymentChannelRefunds;
	}

	public long getPcTransactionId() {
		return this.pcTransactionId;
	}

	public void setPcTransactionId(long pcTransactionId) {
		this.pcTransactionId = pcTransactionId;
	}

	public PaymentChannels getPaymentChannels() {
		return this.paymentChannels;
	}

	public void setPaymentChannels(PaymentChannels paymentChannels) {
		this.paymentChannels = paymentChannels;
	}

	public CoreTransactions getCoreTransactions() {
		return this.coreTransactions;
	}

	public void setCoreTransactions(CoreTransactions coreTransactions) {
		this.coreTransactions = coreTransactions;
	}

	public String getPcTranRefId() {
		return this.pcTranRefId;
	}

	public void setPcTranRefId(String pcTranRefId) {
		this.pcTranRefId = pcTranRefId;
	}

	public String getPcGatewayRefId() {
		return this.pcGatewayRefId;
	}

	public void setPcGatewayRefId(String pcGatewayRefId) {
		this.pcGatewayRefId = pcGatewayRefId;
	}

	public String getPcTranStatus() {
		return this.pcTranStatus;
	}

	public void setPcTranStatus(String pcTranStatus) {
		this.pcTranStatus = pcTranStatus;
	}

	public String getPcTranMsg() {
		return this.pcTranMsg;
	}

	public void setPcTranMsg(String pcTranMsg) {
		this.pcTranMsg = pcTranMsg;
	}

	public String getPcTranParameter() {
		return this.pcTranParameter;
	}

	public void setPcTranParameter(String pcTranParameter) {
		this.pcTranParameter = pcTranParameter;
	}

	public Set getPaymentChannelRefunds() {
		return this.paymentChannelRefunds;
	}

	public void setPaymentChannelRefunds(Set paymentChannelRefunds) {
		this.paymentChannelRefunds = paymentChannelRefunds;
	}

	public Character getIsSettled() {
		return isSettled;
	}

	public void setIsSettled(Character isSettled) {
		this.isSettled = isSettled;
	}

	public Character getIsReconcile() {
		return isReconcile;
	}

	public void setIsReconcile(Character isReconcile) {
		this.isReconcile = isReconcile;
	}
	
	

}
