package com.fidypay.entity;

// Generated Jul 9, 2015 6:47:46 PM by Hibernate Tools 4.0.0

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * PaymentChannelSettlements generated by hbm2java
 */

@Entity
@Table(name = "PAYMENT_CHANNEL_SETTLEMENTS")
@EntityListeners(AuditingEntityListener.class)
public class PaymentChannelSettlements {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "PC_SETTLEMENT_ID")
	private long pcSettlementId;
		
	 @ManyToOne
	 @JoinColumn(name = "PAYMENT_CHANNEL_ID")
    private PaymentChannels paymentChannels;
	
	@Column(name="SETTLEMENT_DATE")
	private Timestamp settlementDate;
	
	@Column(name="SETTLEMENT_DETAILS")
	private String settlementDetails;
	
	@Column(name="SETTLEMENT_IS_VERIFIED")
	private Character settlementIsVerified;
	
	@Column(name="SETTLEMENT_IS_AUTHORIZED")
	private Character settlementIsAuthorized;
	
	@Column(name="SETTLEMENT_REPORT_PASSWORD")
	private String settlementReportPassword;
	
	@Column(name="DATE_GENERATED")
	private Timestamp dateGenerated;
	
	@Column(name="SETTLEMENT_FROM_DATE")
	private Timestamp settlementFromDate;
	
	@Column(name="SETTLEMENT_TO_DATE")
	private Timestamp settlementToDate;
	
	@Column(name="SETTLEMENT_AMOUNT")
	private Double settlementAmount;
	
	@Column(name="SETTLEMENT_TAX")
	private Double settlementTax;
	
	@Column(name="SETTLEMENT_NET_AMOUNT")
	private Double settlementNetAmount;
	
	@Column(name="SETTLEMENT_GROSS_AMOUNT")
	private Double settlementGrossAmount;

	public PaymentChannelSettlements() {
	}

	public PaymentChannelSettlements(long pcSettlementId) {
		this.pcSettlementId=pcSettlementId;
	}

	
	public PaymentChannelSettlements(long pcSettlementId,
			PaymentChannels paymentChannels) {
		this.pcSettlementId = pcSettlementId;
		this.paymentChannels = paymentChannels;
	}

	public PaymentChannelSettlements(long pcSettlementId,
			PaymentChannels paymentChannels, Timestamp settlementDate,
			String settlementDetails, Character settlementIsVerified,
			Character settlementIsAuthorized, String settlementReportPassword,
			Timestamp dateGenerated, Timestamp settlementFromDate,
			Timestamp settlementToDate, Double settlementAmount,
			Double settlementTax, Double settlementNetAmount,
			Double settlementGrossAmount) {
		this.pcSettlementId = pcSettlementId;
		this.paymentChannels = paymentChannels;
		this.settlementDate = settlementDate;
		this.settlementDetails = settlementDetails;
		this.settlementIsVerified = settlementIsVerified;
		this.settlementIsAuthorized = settlementIsAuthorized;
		this.settlementReportPassword = settlementReportPassword;
		this.dateGenerated = dateGenerated;
		this.settlementFromDate = settlementFromDate;
		this.settlementToDate = settlementToDate;
		this.settlementAmount = settlementAmount;
		this.settlementTax = settlementTax;
		this.settlementNetAmount = settlementNetAmount;
		this.settlementGrossAmount = settlementGrossAmount;
	}

	public long getPcSettlementId() {
		return this.pcSettlementId;
	}

	public void setPcSettlementId(long pcSettlementId) {
		this.pcSettlementId = pcSettlementId;
	}

	public PaymentChannels getPaymentChannels() {
		return this.paymentChannels;
	}

	public void setPaymentChannels(PaymentChannels paymentChannels) {
		this.paymentChannels = paymentChannels;
	}

	public Timestamp getSettlementDate() {
		return this.settlementDate;
	}

	public void setSettlementDate(Timestamp settlementDate) {
		this.settlementDate = settlementDate;
	}

	public String getSettlementDetails() {
		return this.settlementDetails;
	}

	public void setSettlementDetails(String settlementDetails) {
		this.settlementDetails = settlementDetails;
	}

	public Character getSettlementIsVerified() {
		return this.settlementIsVerified;
	}

	public void setSettlementIsVerified(Character settlementIsVerified) {
		this.settlementIsVerified = settlementIsVerified;
	}

	public Character getSettlementIsAuthorized() {
		return this.settlementIsAuthorized;
	}

	public void setSettlementIsAuthorized(Character settlementIsAuthorized) {
		this.settlementIsAuthorized = settlementIsAuthorized;
	}

	public String getSettlementReportPassword() {
		return this.settlementReportPassword;
	}

	public void setSettlementReportPassword(String settlementReportPassword) {
		this.settlementReportPassword = settlementReportPassword;
	}

	public Timestamp getDateGenerated() {
		return this.dateGenerated;
	}

	public void setDateGenerated(Timestamp dateGenerated) {
		this.dateGenerated = dateGenerated;
	}

	public Timestamp getSettlementFromDate() {
		return this.settlementFromDate;
	}

	public void setSettlementFromDate(Timestamp settlementFromDate) {
		this.settlementFromDate = settlementFromDate;
	}

	public Timestamp getSettlementToDate() {
		return this.settlementToDate;
	}

	public void setSettlementToDate(Timestamp settlementToDate) {
		this.settlementToDate = settlementToDate;
	}

	public Double getSettlementAmount() {
		return this.settlementAmount;
	}

	public void setSettlementAmount(Double settlementAmount) {
		this.settlementAmount = settlementAmount;
	}

	public Double getSettlementTax() {
		return this.settlementTax;
	}

	public void setSettlementTax(Double settlementTax) {
		this.settlementTax = settlementTax;
	}

	public Double getSettlementNetAmount() {
		return this.settlementNetAmount;
	}

	public void setSettlementNetAmount(Double settlementNetAmount) {
		this.settlementNetAmount = settlementNetAmount;
	}

	public Double getSettlementGrossAmount() {
		return this.settlementGrossAmount;
	}

	public void setSettlementGrossAmount(Double settlementGrossAmount) {
		this.settlementGrossAmount = settlementGrossAmount;
	}

}
