package com.fidypay.entity;
// Generated Jun 20, 2016 4:37:09 PM by Hibernate Tools 4.0.0.Final
import java.io.*;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * RequestFloat generated by hbm2java
 */

@Entity
@Table(name = "REQUEST_FLOAT")
@EntityListeners(AuditingEntityListener.class)
public class RequestFloat implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "REQUEST_FLOAT_ID")
	private long requestFloatId;
	
	 @ManyToOne
	 @JoinColumn(name = "AUTH_USER_ID")
	private AuthorizedUsers authorizedUsersByAuthUserId;
	
	@ManyToOne
	 @JoinColumn(name = "APPROVEDBY_AUTH")
	private AuthorizedUsers authorizedUsersByApprovedbyAuth;
	
	@Column(name="REQUEST_DETAILS_ID", length = 200)
	private String requestDetailsId;
	
	@Column(name="REQUEST_TYPE", length = 1)
	private Character requestType;
	
	@Column(name="REQUEST_DATE")
	private Timestamp requestDate;
	
	@Column(name="REQUEST_FLOAT")
	private Double requestFloat;
	
	@Column(name="DESCRIPTION", length = 500)
	private String description;
	
	@Column(name="PAY_MODE", length = 100)
	private String payMode;
	
	@Column(name="REQUEST_STATUS", length = 1)
	private Character requestStatus;
	
	@Column(name="REQUEST_SE_NAME", length = 200)
	private String requestSeName;
	
	@Column(name="RECEIVED_FLOAT")
	private Double receivedFloat;
	
	@Column(name="REF_FILE_PATH", length = 200)
	private String refFilePath;
	
	@Column(name="REQUEST_FLOAT_REF_ID", length = 100)
	private String requestFloatRefId;
	
	@Column(name="APPROVED_DATE")
	private Timestamp approvedDate;

	public RequestFloat() {
	}

	public RequestFloat(long requestFloatId, AuthorizedUsers authorizedUsersByAuthUserId) {
		this.requestFloatId = requestFloatId;
		this.authorizedUsersByAuthUserId = authorizedUsersByAuthUserId;
	}

	public RequestFloat(long requestFloatId, AuthorizedUsers authorizedUsersByAuthUserId,
			AuthorizedUsers authorizedUsersByApprovedbyAuth, String requestDetailsId, Character requestType,
			Timestamp requestDate, Double requestFloat, String description, String payMode, Character requestStatus,
			String requestSeName, Double receivedFloat, String refFilePath, String requestFloatRefId,
			Timestamp approvedDate) {
		this.requestFloatId = requestFloatId;
		this.authorizedUsersByAuthUserId = authorizedUsersByAuthUserId;
		this.authorizedUsersByApprovedbyAuth = authorizedUsersByApprovedbyAuth;
		this.requestDetailsId = requestDetailsId;
		this.requestType = requestType;
		this.requestDate = requestDate;
		this.requestFloat = requestFloat;
		this.description = description;
		this.payMode = payMode;
		this.requestStatus = requestStatus;
		this.requestSeName = requestSeName;
		this.receivedFloat = receivedFloat;
		this.refFilePath = refFilePath;
		this.requestFloatRefId = requestFloatRefId;
		this.approvedDate = approvedDate;
	}

	public long getRequestFloatId() {
		return this.requestFloatId;
	}

	public void setRequestFloatId(long requestFloatId) {
		this.requestFloatId = requestFloatId;
	}

	public AuthorizedUsers getAuthorizedUsersByAuthUserId() {
		return this.authorizedUsersByAuthUserId;
	}

	public void setAuthorizedUsersByAuthUserId(AuthorizedUsers authorizedUsersByAuthUserId) {
		this.authorizedUsersByAuthUserId = authorizedUsersByAuthUserId;
	}

	public AuthorizedUsers getAuthorizedUsersByApprovedbyAuth() {
		return this.authorizedUsersByApprovedbyAuth;
	}

	public void setAuthorizedUsersByApprovedbyAuth(AuthorizedUsers authorizedUsersByApprovedbyAuth) {
		this.authorizedUsersByApprovedbyAuth = authorizedUsersByApprovedbyAuth;
	}

	public String getRequestDetailsId() {
		return this.requestDetailsId;
	}

	public void setRequestDetailsId(String requestDetailsId) {
		this.requestDetailsId = requestDetailsId;
	}

	public Character getRequestType() {
		return this.requestType;
	}

	public void setRequestType(Character requestType) {
		this.requestType = requestType;
	}

	public Timestamp getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Timestamp requestDate) {
		this.requestDate = requestDate;
	}

	public Double getRequestFloat() {
		return this.requestFloat;
	}

	public void setRequestFloat(Double requestFloat) {
		this.requestFloat = requestFloat;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPayMode() {
		return this.payMode;
	}

	public void setPayMode(String payMode) {
		this.payMode = payMode;
	}

	public Character getRequestStatus() {
		return this.requestStatus;
	}

	public void setRequestStatus(Character requestStatus) {
		this.requestStatus = requestStatus;
	}

	public String getRequestSeName() {
		return this.requestSeName;
	}

	public void setRequestSeName(String requestSeName) {
		this.requestSeName = requestSeName;
	}

	public Double getReceivedFloat() {
		return this.receivedFloat;
	}

	public void setReceivedFloat(Double receivedFloat) {
		this.receivedFloat = receivedFloat;
	}

	public String getRefFilePath() {
		return this.refFilePath;
	}

	public void setRefFilePath(String refFilePath) {
		this.refFilePath = refFilePath;
	}

	public String getRequestFloatRefId() {
		return this.requestFloatRefId;
	}

	public void setRequestFloatRefId(String requestFloatRefId) {
		this.requestFloatRefId = requestFloatRefId;
	}

	public Timestamp getApprovedDate() {
		return this.approvedDate;
	}

	public void setApprovedDate(Timestamp approvedDate) {
		this.approvedDate = approvedDate;
	}

}
