package com.fidypay.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

// Generated Apr 11, 2016 5:25:15 PM by Hibernate Tools 4.0.0

/**
 * ServiceFlatCharge generated by hbm2java
 */

@Entity
@Table(name = "SERVICE_FLAT_CHARGE")
@EntityListeners(AuditingEntityListener.class)
public class ServiceFlatCharge implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "FLAT_CHARGE_ID")
    private long flatChargeId; 
	
		
	 @ManyToOne
	 @JoinColumn(name = "SERVICE_ID")
   private ServiceInfo serviceInfo;
	
	@Column(name="MIN_CHARGE_RANGE")
	private Long minChargeRange;
	
	@Column(name="MAX_CHARGE_RANGE")
	private Long maxChargeRange;
	
	@Column(name="FLAT_CHARGE")
	private Double flatCharge;

	public ServiceFlatCharge() {
	}

	public ServiceFlatCharge(long flatChargeId) {
		this.flatChargeId = flatChargeId;
	}

	public ServiceFlatCharge(long flatChargeId, ServiceInfo serviceInfo,
			Long minChargeRange, Long maxChargeRange, Double flatCharge) {
		this.flatChargeId = flatChargeId;
		this.serviceInfo = serviceInfo;
		this.minChargeRange = minChargeRange;
		this.maxChargeRange = maxChargeRange;
		this.flatCharge = flatCharge;
	}

	public long getFlatChargeId() {
		return this.flatChargeId;
	}

	public void setFlatChargeId(long flatChargeId) {
		this.flatChargeId = flatChargeId;
	}

	public ServiceInfo getServiceInfo() {
		return this.serviceInfo;
	}

	public void setServiceInfo(ServiceInfo serviceInfo) {
		this.serviceInfo = serviceInfo;
	}

	public Long getMinChargeRange() {
		return minChargeRange;
	}

	public void setMinChargeRange(Long minChargeRange) {
		this.minChargeRange = minChargeRange;
	}

	public Long getMaxChargeRange() {
		return maxChargeRange;
	}

	public void setMaxChargeRange(Long maxChargeRange) {
		this.maxChargeRange = maxChargeRange;
	}

	public Double getFlatCharge() {
		return flatCharge;
	}

	public void setFlatCharge(Double flatCharge) {
		this.flatCharge = flatCharge;
	}
}
