package com.fidypay.entity;

// Generated Aug 11, 2015 3:26:03 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * ServiceInfo generated by hbm2java
 */

@Entity
@Table(name = "SERVICE_INFO")
@EntityListeners(AuditingEntityListener.class)
public class ServiceInfo {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "SERVICE_ID")
	private long serviceId;

	@ManyToOne
	@JoinColumn(name = "SUB_SERVICE_CATEGORY_ID")
	private SubServiceCategory subServiceCategory;

	@ManyToOne
	@JoinColumn(name = "SERVICE_PROVIDER_ID")
	private ServiceProviders serviceProviders;

	@ManyToOne
	@JoinColumn(name = "SERVICE_CATEGORY_ID")
	private ServiceCategory serviceCategory;

	@ManyToOne
	@JoinColumn(name = "API_ID")
	private ApiInfo apiInfo;

	@Column(name = "IS_WALLET_SERVICE", length = 1)
	private Character isWalletService;

	@Column(name = "IS_CLIENT_SERVICE", length = 1)
	private Character isClientService;

	@Column(name = "SERVICE_NAME", length = 100)
	private String serviceName;

	@Column(name = "IS_SERVICE_DELETED", length = 1)
	private Character isServiceDeleted;

	@Column(name = "SERVICE_CHARGES")
	private Double serviceCharges;

	@Column(name = "COMM_PERCENT")
	private Double commPercent;

	@Column(name = "IS_FLAT_RATE", length = 1)
	private Character isFlatRate;

	@Column(name = "IS_SLAB", length = 1)
	private Character isSlab;

	@Column(name = "IS_SERV_IDENT_MOBILE", length = 1)
	private Character isServIdentMobile;

	@Column(name = "IS_SERVICE_CHARGE_SLAB", length = 1)
	private Character isServiceChargeSlab;

	@Column(name = "MIN_SERVICE_AMOUNT", length = 100)
	private Double minServiceAmount;

	@Column(name = "MAX_SERVICE_AMOUNT", length = 100)
	private Double maxServiceAmount;

	@OneToMany(mappedBy = "serviceInfo", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<ServiceFlatComm> serviceFlatComms = new HashSet<ServiceFlatComm>(0);

	@OneToMany(mappedBy = "serviceInfo", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<CustomerSubscriptions> customerSubscriptionses = new HashSet<CustomerSubscriptions>(0);

	@OneToMany(mappedBy = "serviceInfo", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<CoreTransactions> coreTransactionses = new HashSet<CoreTransactions>(0);

	@OneToMany(mappedBy = "serviceInfo", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantServices> merchantServiceses = new HashSet<MerchantServices>(0);

	@OneToMany(mappedBy = "serviceInfo", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<ServiceFlatCharge> serviceFlatCharges = new HashSet<ServiceFlatCharge>(0);

	@OneToMany(mappedBy = "serviceInfo", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<TicketingDetail> ticketingDetails = new HashSet<TicketingDetail>(0);

	public ServiceInfo() {
	}

	public ServiceInfo(long serviceId) {
		this.serviceId = serviceId;
	}

	public ServiceInfo(long serviceId, ServiceProviders serviceProviders, ApiInfo apiInfo) {
		this.serviceId = serviceId;
		this.serviceProviders = serviceProviders;
		this.apiInfo = apiInfo;
	}

	public ServiceInfo(long serviceId, SubServiceCategory subServiceCategory, ServiceProviders serviceProviders,
			ServiceCategory serviceCategory, Character isWalletService, Character isClientService, ApiInfo apiInfo,
			String serviceName, Character isServiceDeleted, Double serviceCharges, Double commPercent,
			Character isFlatRate, Character isServiceChargeSlab, Character isSlab, Character isServIdentMobile,
			Double minServiceAmount, Double maxServiceAmount, Set serviceFlatComms, Set customerSubscriptionses,
			Set coreTransactionses, Set merchantServiceses, Set serviceFlatCharges, Set ticketingDetails) {
		this.serviceId = serviceId;
		this.subServiceCategory = subServiceCategory;
		this.serviceProviders = serviceProviders;
		this.serviceCategory = serviceCategory;
		this.isWalletService = isWalletService;
		this.isClientService = isClientService;
		this.apiInfo = apiInfo;
		this.serviceName = serviceName;
		this.isServiceDeleted = isServiceDeleted;
		this.serviceCharges = serviceCharges;
		this.commPercent = commPercent;
		this.isFlatRate = isFlatRate;
		this.isSlab = isSlab;
		this.minServiceAmount = minServiceAmount;
		this.maxServiceAmount = maxServiceAmount;
		this.isServIdentMobile = isServIdentMobile;
		this.isServiceChargeSlab = isServiceChargeSlab;
		this.serviceFlatComms = serviceFlatComms;
		this.customerSubscriptionses = customerSubscriptionses;
		this.coreTransactionses = coreTransactionses;
		this.merchantServiceses = merchantServiceses;
		this.serviceFlatCharges = serviceFlatCharges;
		this.ticketingDetails = ticketingDetails;
	}

	public Character getIsServIdentMobile() {
		return isServIdentMobile;
	}

	public void setIsServIdentMobile(Character isServIdentMobile) {
		this.isServIdentMobile = isServIdentMobile;
	}

	public long getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(long serviceId) {
		this.serviceId = serviceId;
	}

	public SubServiceCategory getSubServiceCategory() {
		return this.subServiceCategory;
	}

	public void setSubServiceCategory(SubServiceCategory subServiceCategory) {
		this.subServiceCategory = subServiceCategory;
	}

	public ServiceProviders getServiceProviders() {
		return this.serviceProviders;
	}

	public void setServiceProviders(ServiceProviders serviceProviders) {
		this.serviceProviders = serviceProviders;
	}

	public ServiceCategory getServiceCategory() {
		return this.serviceCategory;
	}

	public void setServiceCategory(ServiceCategory serviceCategory) {
		this.serviceCategory = serviceCategory;
	}

	public Character getIsWalletService() {
		return this.isWalletService;
	}

	public void setIsWalletService(Character isWalletService) {
		this.isWalletService = isWalletService;
	}

	public Character getIsClientService() {
		return this.isClientService;
	}

	public void setIsClientService(Character isClientService) {
		this.isClientService = isClientService;
	}

	public ApiInfo getApiInfo() {
		return apiInfo;
	}

	public void setApiInfo(ApiInfo apiInfo) {
		this.apiInfo = apiInfo;
	}

	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public Character getIsServiceDeleted() {
		return this.isServiceDeleted;
	}

	public void setIsServiceDeleted(Character isServiceDeleted) {
		this.isServiceDeleted = isServiceDeleted;
	}

	public Double getServiceCharges() {
		return this.serviceCharges;
	}

	public void setServiceCharges(Double serviceCharges) {
		this.serviceCharges = serviceCharges;
	}

	public Double getCommPercent() {
		return this.commPercent;
	}

	public void setCommPercent(Double commPercent) {
		this.commPercent = commPercent;
	}

	public Character getIsFlatRate() {
		return this.isFlatRate;
	}

	public void setIsFlatRate(Character isFlatRate) {
		this.isFlatRate = isFlatRate;
	}

	public Character getIsSlab() {
		return this.isSlab;
	}

	public Double getMinServiceAmount() {
		return minServiceAmount;
	}

	public void setMinServiceAmount(Double minServiceAmount) {
		this.minServiceAmount = minServiceAmount;
	}

	public Double getMaxServiceAmount() {
		return maxServiceAmount;
	}

	public void setMaxServiceAmount(Double maxServiceAmount) {
		this.maxServiceAmount = maxServiceAmount;
	}

	public void setIsSlab(Character isSlab) {
		this.isSlab = isSlab;
	}

	public Character getIsServiceChargeSlab() {
		return isServiceChargeSlab;
	}

	public void setIsServiceChargeSlab(Character isServiceChargeSlab) {
		this.isServiceChargeSlab = isServiceChargeSlab;
	}

	public Set getServiceFlatComms() {
		return this.serviceFlatComms;
	}

	public void setServiceFlatComms(Set serviceFlatComms) {
		this.serviceFlatComms = serviceFlatComms;
	}

	public Set getCustomerSubscriptionses() {
		return this.customerSubscriptionses;
	}

	public void setCustomerSubscriptionses(Set customerSubscriptionses) {
		this.customerSubscriptionses = customerSubscriptionses;
	}

	public Set getCoreTransactionses() {
		return this.coreTransactionses;
	}

	public void setCoreTransactionses(Set coreTransactionses) {
		this.coreTransactionses = coreTransactionses;
	}

	public Set getMerchantServiceses() {
		return this.merchantServiceses;
	}

	public void setMerchantServiceses(Set merchantServiceses) {
		this.merchantServiceses = merchantServiceses;
	}

	public Set getServiceFlatCharges() {
		return serviceFlatCharges;
	}

	public void setServiceFlatCharges(Set serviceFlatCharges) {
		this.serviceFlatCharges = serviceFlatCharges;
	}

	public Set getTicketingDetails() {
		return ticketingDetails;
	}

	public void setTicketingDetails(Set ticketingDetails) {
		this.ticketingDetails = ticketingDetails;
	}

}
