package com.fidypay.entity;

// Generated Jun 30, 2015 7:57:33 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * ServiceCategory generated by hbm2java
 */

@Entity
@Table(name = "SERVICE_CATEGORY")
@EntityListeners(AuditingEntityListener.class)
public class ServiceCategory implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "SERVICE_CATEGORY_ID")
	private long serviceCategoryId;
	
	@Column(name="SERVICE_CATEGORY_NAME", length = 100)
	private String serviceCategoryName;
	
	@Column(name="SERVICE_CATEGORY_DETAILS", length = 200)
	private String serviceCategoryDetails;
	
	@Column(name="IS_SERVICE_SUB_CATEGORY", length = 1)
	private Character isServiceSubCategory;
	
	@Column(name="IS_SERVICE_CATEGORY_DELETED", length = 1)
	private Character isServiceCategoryDeleted;
	
		
	@OneToMany(mappedBy = "serviceCategory", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<ServiceInfo> serviceInfos = new HashSet<ServiceInfo>(0);
	
		
	@OneToMany(mappedBy = "serviceCategory", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<SubServiceCategory> subServiceCategories = new HashSet<SubServiceCategory>(0);

	public ServiceCategory() {
	}

	public ServiceCategory(long serviceCategoryId) {
		this.serviceCategoryId = serviceCategoryId;
	}

	public ServiceCategory(long serviceCategoryId, String serviceCategoryName,
			String serviceCategoryDetails, Character isServiceSubCategory,
			Character isServiceCategoryDeleted, Set serviceInfos,
			Set subServiceCategories) {
		this.serviceCategoryId = serviceCategoryId;
		this.serviceCategoryName = serviceCategoryName;
		this.serviceCategoryDetails = serviceCategoryDetails;
		this.isServiceSubCategory = isServiceSubCategory;
		this.isServiceCategoryDeleted = isServiceCategoryDeleted;
		this.serviceInfos = serviceInfos;
		this.subServiceCategories = subServiceCategories;
	}

	public long getServiceCategoryId() {
		return this.serviceCategoryId;
	}

	public void setServiceCategoryId(long serviceCategoryId) {
		this.serviceCategoryId = serviceCategoryId;
	}

	public String getServiceCategoryName() {
		return this.serviceCategoryName;
	}

	public void setServiceCategoryName(String serviceCategoryName) {
		this.serviceCategoryName = serviceCategoryName;
	}

	public String getServiceCategoryDetails() {
		return this.serviceCategoryDetails;
	}

	public void setServiceCategoryDetails(String serviceCategoryDetails) {
		this.serviceCategoryDetails = serviceCategoryDetails;
	}

	public Character getIsServiceSubCategory() {
		return this.isServiceSubCategory;
	}

	public void setIsServiceSubCategory(Character isServiceSubCategory) {
		this.isServiceSubCategory = isServiceSubCategory;
	}

	public Character getIsServiceCategoryDeleted() {
		return this.isServiceCategoryDeleted;
	}

	public void setIsServiceCategoryDeleted(Character isServiceCategoryDeleted) {
		this.isServiceCategoryDeleted = isServiceCategoryDeleted;
	}

	public Set getServiceInfos() {
		return this.serviceInfos;
	}

	public void setServiceInfos(Set serviceInfos) {
		this.serviceInfos = serviceInfos;
	}

	public Set getSubServiceCategories() {
		return this.subServiceCategories;
	}

	public void setSubServiceCategories(Set subServiceCategories) {
		this.subServiceCategories = subServiceCategories;
	}

}
