package com.fidypay.entity;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

// Generated Jun 30, 2015 7:57:33 PM by Hibernate Tools 4.0.0
/**
 * ServiceProviderSettlements generated by hbm2java
 */


@Entity
@Table(name = "SERVICE_PROVIDER_SETTLEMENTS")
@EntityListeners(AuditingEntityListener.class)
public class ServiceProviderSettlements implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "SP_SETTLEMENT_ID")
	private long spSettlementId;
	
	 @ManyToOne
	@JoinColumn(name = "SERVICE_PROVIDER_ID")
   private ServiceProviders serviceProviders;
	
	@Column(name="SETTLEMENT_DATE")
	private Timestamp settlementDate;
	
	@Column(name="SETTLEMENT_DETAILS", length = 200)
	private String settlementDetails;
	
	@Column(name="SETTLEMENT_IS_VERIFIED", length = 1)
	private Character settlementIsVerified;
	
	@Column(name="SETTLEMENT_IS_AUTHORIZED", length = 1)
	private Character settlementIsAuthorized;
	
	@Column(name="SETTLEMENT_REPORT_PASSWORD", length = 400)
	private String settlementReportPassword;
	
	@Column(name="DATE_GENERATED")
	private Timestamp dateGenerated;
	
	@Column(name="SETTLEMENT_FROM_DATE")
	private Timestamp settlementFromDate;
	
	@Column(name="SETTLEMENT_TO_DATE")
	private Timestamp settlementToDate;
	
	@Column(name="SETTLEMENT_AMOUNT")
	private Double settlementAmount;
	
	@Column(name="SETTLEMENT_GROSS_AMOUNT")
	private Double settlementGrossAmount;
	
	@Column(name="SETTLEMENT_TAX")
	private Double settlementTax;
	
	@Column(name="SETTLEMENT_NET_AMOUNT")
	private Double settlementNetAmount;

	public ServiceProviderSettlements() {
	}

	public ServiceProviderSettlements(long spSettlementId,
			ServiceProviders serviceProviders) {
		this.spSettlementId = spSettlementId;
		this.serviceProviders = serviceProviders;
	}

	public ServiceProviderSettlements(long spSettlementId,
			ServiceProviders serviceProviders, Timestamp settlementDate,
			String settlementDetails, Character settlementIsVerified,
			Character settlementIsAuthorized, String settlementReportPassword,
			Timestamp dateGenerated, Timestamp settlementFromDate,
			Timestamp settlementToDate, Double settlementAmount, Double settlementGrossAmount,
			Double settlementTax, Double settlementNetAmount) {
		this.spSettlementId = spSettlementId;
		this.serviceProviders = serviceProviders;
		this.settlementDate = settlementDate;
		this.settlementDetails = settlementDetails;
		this.settlementIsVerified = settlementIsVerified;
		this.settlementIsAuthorized = settlementIsAuthorized;
		this.settlementReportPassword = settlementReportPassword;
		this.dateGenerated = dateGenerated;
		this.settlementFromDate = settlementFromDate;
		this.settlementToDate = settlementToDate;
		this.settlementAmount = settlementAmount;
		this.settlementGrossAmount=settlementGrossAmount;
		this.settlementTax = settlementTax;
		this.settlementNetAmount = settlementNetAmount;
	}

	public long getSpSettlementId() {
		return this.spSettlementId;
	}

	public void setSpSettlementId(long spSettlementId) {
		this.spSettlementId = spSettlementId;
	}

	public ServiceProviders getServiceProviders() {
		return this.serviceProviders;
	}

	public void setServiceProviders(ServiceProviders serviceProviders) {
		this.serviceProviders = serviceProviders;
	}

	public Timestamp getSettlementDate() {
		return this.settlementDate;
	}

	public void setSettlementDate(Timestamp settlementDate) {
		this.settlementDate = settlementDate;
	}

	public String getSettlementDetails() {
		return this.settlementDetails;
	}

	public void setSettlementDetails(String settlementDetails) {
		this.settlementDetails = settlementDetails;
	}

	public Character getSettlementIsVerified() {
		return this.settlementIsVerified;
	}

	public void setSettlementIsVerified(Character settlementIsVerified) {
		this.settlementIsVerified = settlementIsVerified;
	}

	public Character getSettlementIsAuthorized() {
		return this.settlementIsAuthorized;
	}

	public void setSettlementIsAuthorized(Character settlementIsAuthorized) {
		this.settlementIsAuthorized = settlementIsAuthorized;
	}

	public String getSettlementReportPassword() {
		return this.settlementReportPassword;
	}

	public void setSettlementReportPassword(String settlementReportPassword) {
		this.settlementReportPassword = settlementReportPassword;
	}

	public Timestamp getDateGenerated() {
		return this.dateGenerated;
	}

	public void setDateGenerated(Timestamp dateGenerated) {
		this.dateGenerated = dateGenerated;
	}

	public Timestamp getSettlementFromDate() {
		return this.settlementFromDate;
	}

	public void setSettlementFromDate(Timestamp settlementFromDate) {
		this.settlementFromDate = settlementFromDate;
	}

	public Timestamp getSettlementToDate() {
		return this.settlementToDate;
	}

	public void setSettlementToDate(Timestamp settlementToDate) {
		this.settlementToDate = settlementToDate;
	}

	public Double getSettlementAmount() {
		return this.settlementAmount;
	}

	public void setSettlementAmount(Double settlementAmount) {
		this.settlementAmount = settlementAmount;
	}

	
	
	public Double getSettlementGrossAmount() {
		return settlementGrossAmount;
	}

	public void setSettlementGrossAmount(Double settlementGrossAmount) {
		this.settlementGrossAmount = settlementGrossAmount;
	}

	public Double getSettlementTax() {
		return this.settlementTax;
	}

	public void setSettlementTax(Double settlementTax) {
		this.settlementTax = settlementTax;
	}

	public Double getSettlementNetAmount() {
		return this.settlementNetAmount;
	}

	public void setSettlementNetAmount(Double settlementNetAmount) {
		this.settlementNetAmount = settlementNetAmount;
	}

}
