package com.fidypay.entity;

// Generated Apr 18, 2015 4:15:37 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * ServiceProviders generated by hbm2java
 */

@Entity
@Table(name = "SERVICE_PROVIDERS")
@EntityListeners(AuditingEntityListener.class)
public class ServiceProviders implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "SERVICE_PROVIDER_ID")
	private long serviceProviderId;
	
	@Column(name="SP_NAME", length = 200)
	private String spName;
	
	@Column(name="SP_DETAILS", length = 200)
	private String spDetails;
	
	@Column(name="SP_SETTLEMENT_FREQUENCY", length = 50)
	private String spSettlementFrequency;
	
	@Column(name="SP_BANK_NAME", length = 100)
	private String spBankName;
	
	@Column(name="SP_BANK_BRANCH", length = 100)
	private String spBankBranch;
	
	@Column(name="SP_BANK_CODE", length = 100)
	private String spBankCode;
	
	@Column(name="SP_ACCOUNT_NO", length = 100)
	private String spAccountNo;
	
	@Column(name="SP_EMAIL", length = 100)
	private String spEmail;
	
	@Column(name="SP_PHONE", length = 50)
	private String spPhone;
	
	@Column(name="SP_FLOAT")
	private Double spFloat;
	
	@Column(name="IS_SERV_PROVIDER_DELETED", length = 1)
	private Character isServProviderDeleted;
	
	
	 @OneToMany(mappedBy = "serviceProviders", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<ServiceProviderSettlements> serviceProviderSettlementses = new HashSet<ServiceProviderSettlements>(0);
	

	 @OneToMany(mappedBy = "serviceProviders", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<ServiceInfo> serviceInfos = new HashSet<ServiceInfo>(0);
	
	
	 @OneToMany(mappedBy = "serviceProviders", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<ServiceProviderTransactions> serviceProviderTransactionses = new HashSet<ServiceProviderTransactions>(0);
		
	 @OneToMany(mappedBy = "serviceProviders", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<SpReconciliation> spReconciliations = new HashSet<SpReconciliation>(0);
	
	

	 @OneToMany(mappedBy = "serviceProviders", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<ServiceProviderFloatManage> serviceProviderFloatManageses = new HashSet<ServiceProviderFloatManage>(0);

	public ServiceProviders() {
	}

	public ServiceProviders(long serviceProviderId) {
		this.serviceProviderId = serviceProviderId;
	}

	public ServiceProviders(long serviceProviderId, String spName,
			String spDetails, String spSettlementFrequency,
			 String spBankName, String spBankBranch,
			String spBankCode, String spAccountNo, String spEmail,
			String spPhone, Double spFloat, Character isServProviderDeleted,
			Set serviceProviderSettlementses, Set serviceInfos,
			Set serviceProviderTransactionses, Set spReconciliations , Set serviceProviderFloatManageses) {
		this.serviceProviderId = serviceProviderId;
		this.spName = spName;
		this.spDetails = spDetails;
		this.spSettlementFrequency = spSettlementFrequency;
		this.spBankName = spBankName;
		this.spBankBranch = spBankBranch;
		this.spBankCode = spBankCode;
		this.spAccountNo = spAccountNo;
		this.spEmail = spEmail;
		this.spPhone = spPhone;
		this.spFloat = spFloat;
		this.isServProviderDeleted = isServProviderDeleted;
		this.serviceProviderSettlementses = serviceProviderSettlementses;
		this.serviceInfos = serviceInfos;
		this.serviceProviderTransactionses = serviceProviderTransactionses;
		this.spReconciliations = spReconciliations;
		this.serviceProviderFloatManageses=serviceProviderFloatManageses;
	}

	public long getServiceProviderId() {
		return this.serviceProviderId;
	}

	public void setServiceProviderId(long serviceProviderId) {
		this.serviceProviderId = serviceProviderId;
	}

	public String getSpName() {
		return this.spName;
	}

	public void setSpName(String spName) {
		this.spName = spName;
	}

	public String getSpDetails() {
		return this.spDetails;
	}

	public void setSpDetails(String spDetails) {
		this.spDetails = spDetails;
	}

	public String getSpSettlementFrequency() {
		return this.spSettlementFrequency;
	}

	public void setSpSettlementFrequency(String spSettlementFrequency) {
		this.spSettlementFrequency = spSettlementFrequency;
	}


	public String getSpBankName() {
		return this.spBankName;
	}

	public void setSpBankName(String spBankName) {
		this.spBankName = spBankName;
	}

	public String getSpBankBranch() {
		return this.spBankBranch;
	}

	public void setSpBankBranch(String spBankBranch) {
		this.spBankBranch = spBankBranch;
	}

	public String getSpBankCode() {
		return this.spBankCode;
	}

	public void setSpBankCode(String spBankCode) {
		this.spBankCode = spBankCode;
	}

	public String getSpAccountNo() {
		return this.spAccountNo;
	}

	public void setSpAccountNo(String spAccountNo) {
		this.spAccountNo = spAccountNo;
	}

	public String getSpEmail() {
		return this.spEmail;
	}

	public void setSpEmail(String spEmail) {
		this.spEmail = spEmail;
	}

	public String getSpPhone() {
		return this.spPhone;
	}

	public void setSpPhone(String spPhone) {
		this.spPhone = spPhone;
	}

	public Double getSpFloat() {
		return this.spFloat;
	}

	public void setSpFloat(Double spFloat) {
		this.spFloat = spFloat;
	}

	public Character getIsServProviderDeleted() {
		return this.isServProviderDeleted;
	}

	public void setIsServProviderDeleted(Character isServProviderDeleted) {
		this.isServProviderDeleted = isServProviderDeleted;
	}

	public Set getServiceProviderSettlementses() {
		return this.serviceProviderSettlementses;
	}

	public void setServiceProviderSettlementses(Set serviceProviderSettlementses) {
		this.serviceProviderSettlementses = serviceProviderSettlementses;
	}

	public Set getServiceInfos() {
		return this.serviceInfos;
	}

	public void setServiceInfos(Set serviceInfos) {
		this.serviceInfos = serviceInfos;
	}

	public Set getServiceProviderTransactionses() {
		return this.serviceProviderTransactionses;
	}

	public void setServiceProviderTransactionses(
			Set serviceProviderTransactionses) {
		this.serviceProviderTransactionses = serviceProviderTransactionses;
	}

	public Set getSpReconciliations() {
		return this.spReconciliations;
	}

	public void setSpReconciliations(Set spReconciliations) {
		this.spReconciliations = spReconciliations;
	}

	public Set getServiceProviderFloatManageses() {
		return serviceProviderFloatManageses;
	}

	public void setServiceProviderFloatManageses(Set serviceProviderFloatManageses) {
		this.serviceProviderFloatManageses = serviceProviderFloatManageses;
	}

	

}
