
package com.fidypay.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

// Generated Aug 11, 2015 1:26:04 PM by Hibernate Tools 4.0.0

/**
 * ServiceFlatComm generated by hbm2java
 */

@Entity
@Table(name = "SERVICE_FLAT_COMM")
@EntityListeners(AuditingEntityListener.class)
public class ServiceFlatComm implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "FLAT_COMM_ID")
	private long flatCommId;
	
	
	 @ManyToOne
	 @JoinColumn(name = "SERVICE_ID")
    private ServiceInfo serviceInfo;
	
	@Column(name="MIN_RANGE")
	private Long minRange;
	
	@Column(name="MAX_RANGE")
	private Long maxRange;
	
	@Column(name="FLAT_COMM")
	private Double flatComm;

	public ServiceFlatComm() {
	}

	public ServiceFlatComm(long flatCommId) {
		this.flatCommId = flatCommId;
	}

	public ServiceFlatComm(long flatCommId, ServiceInfo serviceInfo,
			Long minRange, Long maxRange, Double flatComm) {
		this.flatCommId = flatCommId;
		this.serviceInfo = serviceInfo;
		this.minRange = minRange;
		this.maxRange = maxRange;
		this.flatComm = flatComm;
	}

	

	public long getFlatCommId() {
		return flatCommId;
	}

	public void setFlatCommId(long flatCommId) {
		this.flatCommId = flatCommId;
	}

	public ServiceInfo getServiceInfo() {
		return this.serviceInfo;
	}

	public void setServiceInfo(ServiceInfo serviceInfo) {
		this.serviceInfo = serviceInfo;
	}

	public Long getMinRange() {
		return this.minRange;
	}

	public void setMinRange(Long minRange) {
		this.minRange = minRange;
	}

	public Long getMaxRange() {
		return this.maxRange;
	}

	public void setMaxRange(Long maxRange) {
		this.maxRange = maxRange;
	}

	public Double getFlatComm() {
		return this.flatComm;
	}

	public void setFlatComm(Double flatComm) {
		this.flatComm = flatComm;
	}

}
