package com.fidypay.entity;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

// Generated Jun 30, 2015 7:57:33 PM by Hibernate Tools 4.0.0

/**
 * SpReconciliation generated by hbm2java
 */
@Entity
@Table(name = "SP_RECONCILIATION")
@EntityListeners(AuditingEntityListener.class)
public class SpReconciliation implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "SP_RECONCILIATION_ID")
	private long spReconciliationId;

	@ManyToOne
	@JoinColumn(name = "SERVICE_ID")
	private ServiceInfo serviceInfo;

	@ManyToOne
	@JoinColumn(name = "SERVICE_PROVIDER_ID")
	private ServiceProviders serviceProviders;

	@Column(name = "SP_SHARE", nullable = false)
	private double spShare;

	@Column(name = "RECONCILIATION_DATE")
	private Timestamp reconciliationDate;

	@Column(name = "RECONCILIATION_DETAILS", length = 300)
	private String reconciliationDetails;

	@Column(name = "RECON_TOTAL_AMOUNT")
	private Double reconTotalAmount;

	@Column(name = "IS_VERIFIED", length = 1)
	private Character isVerified;

	@Column(name = "IS_SETTELED", length = 1)
	private Character isSetteled;

	public SpReconciliation() {
	}

	public SpReconciliation(long spReconciliationId, ServiceProviders serviceProviders, double spShare) {
		this.spReconciliationId = spReconciliationId;
		this.serviceProviders = serviceProviders;
		this.spShare = spShare;
	}

	public SpReconciliation(long spReconciliationId, ServiceInfo serviceInfo, ServiceProviders serviceProviders,
			double spShare, Timestamp reconciliationDate, String reconciliationDetails, Double reconTotalAmount,
			Character isVerified, Character isSetteled) {
		this.spReconciliationId = spReconciliationId;
		this.serviceInfo = serviceInfo;
		this.serviceProviders = serviceProviders;
		this.spShare = spShare;
		this.reconciliationDate = reconciliationDate;
		this.reconciliationDetails = reconciliationDetails;
		this.reconTotalAmount = reconTotalAmount;
		this.isVerified = isVerified;
		this.isSetteled = isSetteled;
	}

	public long getSpReconciliationId() {
		return this.spReconciliationId;
	}

	public void setSpReconciliationId(long spReconciliationId) {
		this.spReconciliationId = spReconciliationId;
	}

	public ServiceInfo getServiceInfo() {
		return this.serviceInfo;
	}

	public void setServiceInfo(ServiceInfo serviceInfo) {
		this.serviceInfo = serviceInfo;
	}

	public ServiceProviders getServiceProviders() {
		return this.serviceProviders;
	}

	public void setServiceProviders(ServiceProviders serviceProviders) {
		this.serviceProviders = serviceProviders;
	}

	public double getSpShare() {
		return this.spShare;
	}

	public void setSpShare(double spShare) {
		this.spShare = spShare;
	}

	public Timestamp getReconciliationDate() {
		return this.reconciliationDate;
	}

	public void setReconciliationDate(Timestamp reconciliationDate) {
		this.reconciliationDate = reconciliationDate;
	}

	public String getReconciliationDetails() {
		return this.reconciliationDetails;
	}

	public void setReconciliationDetails(String reconciliationDetails) {
		this.reconciliationDetails = reconciliationDetails;
	}

	public Double getReconTotalAmount() {
		return this.reconTotalAmount;
	}

	public void setReconTotalAmount(Double reconTotalAmount) {
		this.reconTotalAmount = reconTotalAmount;
	}

	public Character getIsVerified() {
		return this.isVerified;
	}

	public void setIsVerified(Character isVerified) {
		this.isVerified = isVerified;
	}

	public Character getIsSetteled() {
		return this.isSetteled;
	}

	public void setIsSetteled(Character isSetteled) {
		this.isSetteled = isSetteled;
	}

}
