package com.fidypay.entity;

// Generated Apr 18, 2015 4:15:37 PM by Hibernate Tools 4.0.0


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * CustomerWalletInfo generated by hbm2java
 */

@Entity
//@Table(name = "CUSTOMER_WALLET_INFO")
@EntityListeners(AuditingEntityListener.class)
@Table(name = "CUSTOMER_WALLET_INFO", indexes = {
		@Index(name = "index_CUST_WALLET_ID", columnList = "CUST_WALLET_ID"),
		@Index(name = "index_CUSTOMER_ID", columnList = "CUSTOMER_ID"),
		@Index(name = "index_CUS_WALLET_ACCOUNT_NO", columnList = "CUS_WALLET_ACCOUNT_NO"),
		@Index(name = "index_CUST_WALLET_PIN", columnList = "CUST_WALLET_PIN"),
		@Index(name = "index_CUST_WALLET_FROM_DATE", columnList = "CUST_WALLET_FROM_DATE"),
		@Index(name = "index_CUST_WALLET_TO_DATE", columnList = "CUST_WALLET_TO_DATE"),
		@Index(name = "index_CUST_WALLET_AMOUNT", columnList = "CUST_WALLET_AMOUNT"),
		@Index(name = "index_CUST_PIN_LAST_CHANGED_DATE", columnList = "CUST_PIN_LAST_CHANGED_DATE"),
		@Index(name = "index_CUST_WALLET_PIC", columnList = "CUST_WALLET_PIC"),
		@Index(name = "index_CUST_ID_PROOF_TYPE", columnList = "CUST_ID_PROOF_TYPE"),
		@Index(name = "index_CUST_ID_PROOF_NUMBER", columnList = "CUST_ID_PROOF_NUMBER"),
		@Index(name = "index_CUST_ID_PROOF_PATH", columnList = "CUST_ID_PROOF_PATH"),
		@Index(name = "index_CUST_ADDRESS_PROOF_TYPE", columnList = "CUST_ADDRESS_PROOF_TYPE"),
		@Index(name = "index_CUST_ADDRESS_PROOF_PATH", columnList = "CUST_ADDRESS_PROOF_PATH"),
		@Index(name = "index_IS_ID_PROOF_VERIFIED", columnList = "IS_ID_PROOF_VERIFIED"),
		@Index(name = "index_IS_ADDRESS_PROOF_VERIFIED", columnList = "IS_ADDRESS_PROOF_VERIFIED"),
		@Index(name = "index_IS_CUST_KYC_COMPLETE", columnList = "IS_CUST_KYC_COMPLETE"),
		@Index(name = "index_IS_CUST_WALLET_ACTIVE", columnList = "IS_CUST_WALLET_ACTIVE")
		})
public class CustomerWalletInfo implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CUST_WALLET_ID")
	private long custWalletId;
	
		
	 @ManyToOne
	 @JoinColumn(name = "CUSTOMER_ID")
    private Customers customers;
	
	@Column(name="CUS_WALLET_ACCOUNT_NO", length = 100)
	private String cusWalletAccountNo;
	
	@Column(name="CUST_WALLET_PIN", length = 50)
	private String custWalletPin;
	
	@Column(name="CUST_WALLET_FROM_DATE")
	private Timestamp custWalletFromDate;
	
	@Column(name="CUST_WALLET_TO_DATE")
	private Timestamp custWalletToDate;
	
	@Column(name="CUST_WALLET_AMOUNT")
	private Double custWalletAmount;
	
	@Column(name="CUST_PIN_LAST_CHANGED_DATE")
	private Timestamp custPinLastChangedDate;
	
	@Column(name="CUST_WALLET_PIC", length = 300)
	private String custWalletPic;
	
	@Column(name="CUST_ID_PROOF_TYPE", length = 100)
	private String custIdProofType;
	
	@Column(name="CUST_ID_PROOF_NUMBER", length = 100)
	private String custIdProofNumber;
	
	@Column(name="CUST_ID_PROOF_PATH", length = 300)
	private String custIdProofPath;
	
	@Column(name="CUST_ADDRESS_PROOF_TYPE", length = 100)
	private String custAddressProofType;
	
	@Column(name="CUST_ADDRESS_PROOF_NUMBER", length = 100)
	private String custAddressProofNumber;
	
	@Column(name="CUST_ADDRESS_PROOF_PATH", length = 100)
	private String custAddressProofPath;
	
	@Column(name="IS_ID_PROOF_VERIFIED", length = 1)
	private Character isIdProofVerified;
	
	@Column(name="IS_ADDRESS_PROOF_VERIFIED",length = 1)
	private Character isAddressProofVerified;
	
	@Column(name="IS_CUST_KYC_COMPLETE", length = 1)
	private Character isCustKycComplete;
	
	@Column(name="IS_CUST_WALLET_ACTIVE", length = 1)
	private Character isCustWalletActive;
	
		
	 @OneToMany(mappedBy = "customerWalletInfo", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<CustomerWalletTransactions> customerWalletTransactionses = new HashSet<CustomerWalletTransactions>(0);

	public CustomerWalletInfo() {
	}

	public CustomerWalletInfo(long custWalletId, Customers customers,
			String cusWalletAccountNo, String custWalletPin) {
		this.custWalletId = custWalletId;
		this.customers = customers;
		this.cusWalletAccountNo = cusWalletAccountNo;
		this.custWalletPin = custWalletPin;
	}

	public CustomerWalletInfo(long custWalletId, Customers customers,
			String cusWalletAccountNo, String custWalletPin,
			Timestamp custWalletFromDate, Timestamp custWalletToDate,
			Double custWalletAmount, Timestamp custPinLastChangedDate,
			String custWalletPic, String custIdProofType,
			String custIdProofNumber, String custIdProofPath,
			String custAddressProofType, String custAddressProofNumber,
			String custAddressProofPath, Character isIdProofVerified,
			Character isAddressProofVerified, Character isCustKycComplete,
			Character isCustWalletActive, Set customerWalletTransactionses) {
		this.custWalletId = custWalletId;
		this.customers = customers;
		this.cusWalletAccountNo = cusWalletAccountNo;
		this.custWalletPin = custWalletPin;
		this.custWalletFromDate = custWalletFromDate;
		this.custWalletToDate = custWalletToDate;
		this.custWalletAmount = custWalletAmount;
		this.custPinLastChangedDate = custPinLastChangedDate;
		this.custWalletPic = custWalletPic;
		this.custIdProofType = custIdProofType;
		this.custIdProofNumber = custIdProofNumber;
		this.custIdProofPath = custIdProofPath;
		this.custAddressProofType = custAddressProofType;
		this.custAddressProofNumber = custAddressProofNumber;
		this.custAddressProofPath = custAddressProofPath;
		this.isIdProofVerified = isIdProofVerified;
		this.isAddressProofVerified = isAddressProofVerified;
		this.isCustKycComplete = isCustKycComplete;
		this.isCustWalletActive = isCustWalletActive;
		this.customerWalletTransactionses = customerWalletTransactionses;
	}

	public long getCustWalletId() {
		return this.custWalletId;
	}

	public void setCustWalletId(long custWalletId) {
		this.custWalletId = custWalletId;
	}

	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	public String getCusWalletAccountNo() {
		return this.cusWalletAccountNo;
	}

	public void setCusWalletAccountNo(String cusWalletAccountNo) {
		this.cusWalletAccountNo = cusWalletAccountNo;
	}

	public String getCustWalletPin() {
		return this.custWalletPin;
	}

	public void setCustWalletPin(String custWalletPin) {
		this.custWalletPin = custWalletPin;
	}

	public Timestamp getCustWalletFromDate() {
		return this.custWalletFromDate;
	}

	public void setCustWalletFromDate(Timestamp custWalletFromDate) {
		this.custWalletFromDate = custWalletFromDate;
	}

	public Timestamp getCustWalletToDate() {
		return this.custWalletToDate;
	}

	public void setCustWalletToDate(Timestamp custWalletToDate) {
		this.custWalletToDate = custWalletToDate;
	}

	public Double getCustWalletAmount() {
		return this.custWalletAmount;
	}

	public void setCustWalletAmount(Double custWalletAmount) {
		this.custWalletAmount = custWalletAmount;
	}

	public Timestamp getCustPinLastChangedDate() {
		return this.custPinLastChangedDate;
	}

	public void setCustPinLastChangedDate(Timestamp custPinLastChangedDate) {
		this.custPinLastChangedDate = custPinLastChangedDate;
	}

	public String getCustWalletPic() {
		return this.custWalletPic;
	}

	public void setCustWalletPic(String custWalletPic) {
		this.custWalletPic = custWalletPic;
	}

	public String getCustIdProofType() {
		return this.custIdProofType;
	}

	public void setCustIdProofType(String custIdProofType) {
		this.custIdProofType = custIdProofType;
	}

	public String getCustIdProofNumber() {
		return this.custIdProofNumber;
	}

	public void setCustIdProofNumber(String custIdProofNumber) {
		this.custIdProofNumber = custIdProofNumber;
	}

	public String getCustIdProofPath() {
		return this.custIdProofPath;
	}

	public void setCustIdProofPath(String custIdProofPath) {
		this.custIdProofPath = custIdProofPath;
	}

	public String getCustAddressProofType() {
		return this.custAddressProofType;
	}

	public void setCustAddressProofType(String custAddressProofType) {
		this.custAddressProofType = custAddressProofType;
	}

	public String getCustAddressProofNumber() {
		return this.custAddressProofNumber;
	}

	public void setCustAddressProofNumber(String custAddressProofNumber) {
		this.custAddressProofNumber = custAddressProofNumber;
	}

	public String getCustAddressProofPath() {
		return this.custAddressProofPath;
	}

	public void setCustAddressProofPath(String custAddressProofPath) {
		this.custAddressProofPath = custAddressProofPath;
	}

	public Character getIsIdProofVerified() {
		return this.isIdProofVerified;
	}

	public void setIsIdProofVerified(Character isIdProofVerified) {
		this.isIdProofVerified = isIdProofVerified;
	}

	public Character getIsAddressProofVerified() {
		return this.isAddressProofVerified;
	}

	public void setIsAddressProofVerified(Character isAddressProofVerified) {
		this.isAddressProofVerified = isAddressProofVerified;
	}

	public Character getIsCustKycComplete() {
		return this.isCustKycComplete;
	}

	public void setIsCustKycComplete(Character isCustKycComplete) {
		this.isCustKycComplete = isCustKycComplete;
	}

	public Character getIsCustWalletActive() {
		return this.isCustWalletActive;
	}

	public void setIsCustWalletActive(Character isCustWalletActive) {
		this.isCustWalletActive = isCustWalletActive;
	}

	public Set getCustomerWalletTransactionses() {
		return this.customerWalletTransactionses;
	}

	public void setCustomerWalletTransactionses(Set customerWalletTransactionses) {
		this.customerWalletTransactionses = customerWalletTransactionses;
	}

}
