package com.fidypay.entity;

// Generated Apr 18, 2015 4:15:37 PM by Hibernate Tools 4.0.0

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * DailyReconciliation generated by hbm2java
 */

@Entity
//@Table(name = "DAILY_RECONCILIATION")
@EntityListeners(AuditingEntityListener.class)
@Table(name = "DAILY_RECONCILIATION", indexes = {
		@Index(name = "index_RECONCILIATION_ID", columnList = "RECONCILIATION_ID"),
		@Index(name = "index_RECONCILIATION_REF", columnList = "RECONCILIATION_REF"),
		@Index(name = "index_RECONCILIATION_DATE", columnList = "RECONCILIATION_DATE"),
		@Index(name = "index_RECONCILIATION_DETAILS", columnList = "RECONCILIATION_DETAILS"),
		@Index(name = "index_RECON_TOTAL_AMOUNT", columnList = "RECON_TOTAL_AMOUNT"),
		@Index(name = "index_UMOJAPAY_SHARE", columnList = "UMOJAPAY_SHARE"),
		@Index(name = "index_VAT_TAX", columnList = "VAT_TAX"),
		@Index(name = "index_UMOJAPAY_NET", columnList = "UMOJAPAY_NET"),
		@Index(name = "index_IS_VERIFIED", columnList = "IS_VERIFIED"),
		@Index(name = "index_IS_SETTELED", columnList = "IS_SETTELED"),
		@Index(name = "index_STATUS", columnList = "STATUS")
		})
public class DailyReconciliation implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "RECONCILIATION_ID")
	private long reconciliationId;
	
	@Column(name="RECONCILIATION_REF", nullable = false, length = 200)
	private String reconciliationRef;
	
	@Column(name="RECONCILIATION_DATE")
	private Timestamp reconciliationDate;
	
	@Column(name="RECONCILIATION_DETAILS", length = 300)
	private String reconciliationDetails;
	
	@Column(name="RECON_TOTAL_AMOUNT", nullable = false)
	private double reconTotalAmount;
	
	@Column(name="UMOJAPAY_SHARE", nullable = false)
	private double umojapayShare;
	
	@Column(name="VAT_TAX", nullable = false)
	private double vatTax;
	
	@Column(name="UMOJAPAY_NET", nullable = false)
	private double umojapayNet;
	
	@Column(name="IS_VERIFIED", length = 1)
	private Character isVerified;
	
	@Column(name="IS_SETTELED", length = 1)
	private Character isSetteled;
	
	@Column(name="STATUS", length = 1)
	private Character status;
	
//	@OneToMany(mappedBy = "dailyReconciliation", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
//	private Set<PaymentChannelReconciliation> paymentChannelReconciliations = new HashSet<PaymentChannelReconciliation>(0);
//	
//	@OneToMany(mappedBy = "dailyReconciliation", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
//	private Set<MerchantReconciliation> merchantReconciliations = new HashSet<MerchantReconciliation>(0);
//	
//	@OneToMany(mappedBy = "dailyReconciliation", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
//	private Set<SpReconciliation> spReconciliations = new HashSet<SpReconciliation>(0);

	public DailyReconciliation() {
	}

	public DailyReconciliation(long reconciliationId, String reconciliationRef,
			double reconTotalAmount, double umojapayShare, double vatTax,
			double umojapayNet) {
		this.reconciliationId = reconciliationId;
		this.reconciliationRef = reconciliationRef;
		this.reconTotalAmount = reconTotalAmount;
		this.umojapayShare = umojapayShare;
		this.vatTax = vatTax;
		this.umojapayNet = umojapayNet;
	}

	public DailyReconciliation(long reconciliationId, String reconciliationRef,
			Timestamp reconciliationDate, String reconciliationDetails,
			double reconTotalAmount, double umojapayShare, double vatTax,
			double umojapayNet, Character isVerified, Character isSetteled,
			Character status) {
		this.reconciliationId = reconciliationId;
		this.reconciliationRef = reconciliationRef;
		this.reconciliationDate = reconciliationDate;
		this.reconciliationDetails = reconciliationDetails;
		this.reconTotalAmount = reconTotalAmount;
		this.umojapayShare = umojapayShare;
		this.vatTax = vatTax;
		this.umojapayNet = umojapayNet;
		this.isVerified = isVerified;
		this.isSetteled = isSetteled;
		this.status = status;
	}

	public long getReconciliationId() {
		return this.reconciliationId;
	}

	public void setReconciliationId(long reconciliationId) {
		this.reconciliationId = reconciliationId;
	}

	public String getReconciliationRef() {
		return this.reconciliationRef;
	}

	public void setReconciliationRef(String reconciliationRef) {
		this.reconciliationRef = reconciliationRef;
	}

	public Timestamp getReconciliationDate() {
		return this.reconciliationDate;
	}

	public void setReconciliationDate(Timestamp reconciliationDate) {
		this.reconciliationDate = reconciliationDate;
	}

	public String getReconciliationDetails() {
		return this.reconciliationDetails;
	}

	public void setReconciliationDetails(String reconciliationDetails) {
		this.reconciliationDetails = reconciliationDetails;
	}

	public double getReconTotalAmount() {
		return this.reconTotalAmount;
	}

	public void setReconTotalAmount(double reconTotalAmount) {
		this.reconTotalAmount = reconTotalAmount;
	}

	public double getUmojapayShare() {
		return this.umojapayShare;
	}

	public void setUmojapayShare(double umojapayShare) {
		this.umojapayShare = umojapayShare;
	}

	public double getVatTax() {
		return this.vatTax;
	}

	public void setVatTax(double vatTax) {
		this.vatTax = vatTax;
	}

	public double getUmojapayNet() {
		return this.umojapayNet;
	}

	public void setUmojapayNet(double umojapayNet) {
		this.umojapayNet = umojapayNet;
	}

	public Character getIsVerified() {
		return this.isVerified;
	}

	public void setIsVerified(Character isVerified) {
		this.isVerified = isVerified;
	}

	public Character getIsSetteled() {
		return this.isSetteled;
	}

	public void setIsSetteled(Character isSetteled) {
		this.isSetteled = isSetteled;
	}

	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

}
