package com.fidypay.entity;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

// Generated Oct 29, 2015 6:39:28 PM by Hibernate Tools 4.0.0



/**
 * MerchantFloatManage generated by hbm2java
 */


@Entity
//@Table(name = "MERCHANT_FLOAT_MANAGE")
@EntityListeners(AuditingEntityListener.class)
@Table(name = "MERCHANT_FLOAT_MANAGE", indexes = {
		@Index(name = "index_MERCHANT_FLOAT_MANAGE_ID", columnList = "MERCHANT_FLOAT_MANAGE_ID"),
		@Index(name = "index_MERCHANT_ID", columnList = "MERCHANT_ID"),
		@Index(name = "index_DESCRIPTION", columnList = "DESCRIPTION"),
		@Index(name = "index_TXN_REF_NO", columnList = "TXN_REF_NO"),
		@Index(name = "index_TXN_TYPE", columnList = "TXN_TYPE"),
		@Index(name = "index_PAY_MODE", columnList = "PAY_MODE"),
		@Index(name = "index_MANAGE_DATE", columnList = "MANAGE_DATE"),
		@Index(name = "index_AMOUNT", columnList = "AMOUNT"),
		@Index(name = "index_PRE_BALANCE", columnList = "PRE_BALANCE"),
		@Index(name = "index_NEW_BALANCE", columnList = "NEW_BALANCE"),
		@Index(name = "index_RECEIVED_AMOUNT", columnList = "RECEIVED_AMOUNT"),
		@Index(name = "index_IS_REVERTED", columnList = "IS_REVERTED")
		})
public class MerchantFloatManage implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MERCHANT_FLOAT_MANAGE_ID")
    private long merchantFloatManageId;
	
	
	  @ManyToOne
	 @JoinColumn(name = "MERCHANT_ID")
     private Merchants merchants;
	
	
	@Column(name="DESCRIPTION", length = 500)
	private String description;
	
	@Column(name="TXN_REF_NO", length = 100)
	private String txnRefNo;
	
	@Column(name="TXN_TYPE", length = 100)
	private String txnType;
	
	@Column(name="PAY_MODE", length = 100)
	private String payMode;
	
	@Column(name="MANAGE_DATE")
	private Timestamp manageDate;
	
	@Column(name="AMOUNT", nullable = false, length = 100)
	private double amount;
	
	@Column(name="PRE_BALANCE")
	private Double preBalance;
	
	
	@Column(name="NEW_BALANCE")
	private Double newBalance;
	
	@Column(name="RECEIVED_AMOUNT")
	private Double receivedAmount;
	
	@Column(name="IS_REVERTED", length = 1)
	private Character isReverted;

	public MerchantFloatManage() {
	}

	public MerchantFloatManage(long merchantFloatManageId, double amount) {
		this.merchantFloatManageId = merchantFloatManageId;
		this.amount = amount;
	}

	public MerchantFloatManage(long merchantFloatManageId, Merchants merchants,
			String description, String txnRefNo, String txnType,
			String payMode, Timestamp manageDate, double amount,
			Double preBalance, Double newBalance, Double receivedAmount,
			Character isReverted) {
		this.merchantFloatManageId = merchantFloatManageId;
		this.merchants = merchants;
		this.description = description;
		this.txnRefNo = txnRefNo;
		this.txnType = txnType;
		this.payMode = payMode;
		this.manageDate = manageDate;
		this.amount = amount;
		this.preBalance = preBalance;
		this.newBalance = newBalance;
		this.receivedAmount = receivedAmount;
		this.isReverted = isReverted;
	}

	public long getMerchantFloatManageId() {
		return this.merchantFloatManageId;
	}

	public void setMerchantFloatManageId(long merchantFloatManageId) {
		this.merchantFloatManageId = merchantFloatManageId;
	}

	public Merchants getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchants merchants) {
		this.merchants = merchants;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTxnRefNo() {
		return this.txnRefNo;
	}

	public void setTxnRefNo(String txnRefNo) {
		this.txnRefNo = txnRefNo;
	}

	public String getTxnType() {
		return this.txnType;
	}

	public void setTxnType(String txnType) {
		this.txnType = txnType;
	}

	public String getPayMode() {
		return this.payMode;
	}

	public void setPayMode(String payMode) {
		this.payMode = payMode;
	}

	public Timestamp getManageDate() {
		return this.manageDate;
	}

	public void setManageDate(Timestamp manageDate) {
		this.manageDate = manageDate;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public Double getPreBalance() {
		return this.preBalance;
	}

	public void setPreBalance(Double preBalance) {
		this.preBalance = preBalance;
	}

	public Double getNewBalance() {
		return this.newBalance;
	}

	public void setNewBalance(Double newBalance) {
		this.newBalance = newBalance;
	}

	public Double getReceivedAmount() {
		return this.receivedAmount;
	}

	public void setReceivedAmount(Double receivedAmount) {
		this.receivedAmount = receivedAmount;
	}

	public Character getIsReverted() {
		return this.isReverted;
	}

	public void setIsReverted(Character isReverted) {
		this.isReverted = isReverted;
	}

}
