package com.fidypay.entity;

// Generated Oct 17, 2015 5:26:34 PM by Hibernate Tools 4.0.0


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * MerchantTills generated by hbm2java
 */

@Entity
//@Table(name = "MERCHANT_TILLS")
@EntityListeners(AuditingEntityListener.class)
@Table(name = "MERCHANT_TILLS", indexes = {
		@Index(name = "index_MERCHANT_TILL_ID", columnList = "MERCHANT_TILL_ID"),
		@Index(name = "index_MERCHANT_ID", columnList = "MERCHANT_ID"),
		@Index(name = "index_TILL_CODE", columnList = "TILL_CODE"),
		@Index(name = "index_TILL_PASSWORD", columnList = "TILL_PASSWORD"),
		@Index(name = "index_TILL_FIRSTNAME", columnList = "TILL_FIRSTNAME"),
		@Index(name = "index_TILL_FIRSTNAME", columnList = "TILL_FIRSTNAME"),
		@Index(name = "index_TILL_LASTNAME", columnList = "TILL_LASTNAME"),
		@Index(name = "index_TILL_ADDRESS1", columnList = "TILL_ADDRESS1"),
		@Index(name = "index_TILL_ADDRESS2", columnList = "TILL_ADDRESS2"),
		@Index(name = "index_TILL_CITY", columnList = "TILL_CITY"),
		@Index(name = "index_TILL_STATE", columnList = "TILL_STATE"),
		@Index(name = "index_TILL_COUNTRY", columnList = "TILL_COUNTRY"),
		@Index(name = "index_TILL_ZIPCODE", columnList = "TILL_ZIPCODE"),
		@Index(name = "index_TILL_PHONE", columnList = "TILL_PHONE"),
		@Index(name = "index_TILL_EMAIL", columnList = "TILL_EMAIL"),
		@Index(name = "index_TILL_FLOAT_AMOUNT", columnList = "TILL_FLOAT_AMOUNT"),
		@Index(name = "index_TILL_FROMDATE", columnList = "TILL_FROMDATE"),
		@Index(name = "index_TILL_TODATE", columnList = "TILL_TODATE"),
		@Index(name = "index_TILL_IS_ACTIVE", columnList = "TILL_IS_ACTIVE"),
		@Index(name = "index_TILL_IS_VERIFIED", columnList = "TILL_IS_VERIFIED"),
		@Index(name = "index_TILL_IS_SUPERVISOR", columnList = "TILL_IS_SUPERVISOR"),
		@Index(name = "index_TILL_LAST_LOGIN", columnList = "TILL_LAST_LOGIN"),
		@Index(name = "index_TILL_LAST_LOGOUT", columnList = "TILL_LAST_LOGOUT"),
		@Index(name = "index_TILL_LAST_ACTIVE", columnList = "TILL_LAST_ACTIVE"),
		@Index(name = "index_TILL_DEVICE_ID", columnList = "TILL_DEVICE_ID"),
		@Index(name = "index_TILL_UPDATE", columnList = "TILL_UPDATE"),
		@Index(name = "index_TILL_BCID", columnList = "TILL_BCID")
		})
public class MerchantTills implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MERCHANT_TILL_ID")
	private long merchantTillId;
	
    @ManyToOne
	 @JoinColumn(name = "MERCHANT_ID")
     private Merchants merchants;
	
	@Column(name="TILL_CODE", nullable = false, length = 100)
	private String tillCode;
	
	@Column(name="TILL_PASSWORD", nullable = false, length = 200)
	private String tillPassword;
	
	@Column(name="TILL_FIRSTNAME", length = 100)
	private String tillFirstname;
	
	@Column(name="TILL_LASTNAME", length = 100)
	private String tillLastname;
	
	@Column(name="TILL_ADDRESS1", length = 200)
	private String tillAddress1;
	
	@Column(name="TILL_ADDRESS2", length = 100)
	private String tillAddress2;
	
	@Column(name="TILL_CITY", length = 100)
	private String tillCity;
	
	@Column(name="TILL_STATE", length = 100)
	private String tillState;
	
	
	@Column(name="TILL_COUNTRY", length = 100)
	private String tillCountry;
	
	@Column(name="TILL_ZIPCODE", length = 50)
	private String tillZipcode;
	
	@Column(name="TILL_PHONE", length = 50)
	private String tillPhone;
	
	@Column(name="TILL_EMAIL", length = 200)
	private String tillEmail;
	
	@Column(name="TILL_FLOAT_AMOUNT")
	private double tillFloatAmount;
	
	@Column(name="TILL_FROMDATE")
	private Timestamp tillFromdate;
	
	@Column(name="TILL_TODATE", length = 200)
	private Timestamp tillTodate;
	
	@Column(name="TILL_IS_ACTIVE", length = 1)
	private Character tillIsActive;
	
	@Column(name="TILL_IS_VERIFIED", length = 1)
	private Character tillIsVerified;
	
	@Column(name="TILL_IS_SUPERVISOR", length = 1)
	private Character tillIsSupervisor;
	
	@Column(name="TILL_LAST_LOGIN")
	private Timestamp tillLastLogin;
	
	@Column(name="TILL_LAST_LOGOUT")
	private Timestamp tillLastLogout;
	
	@Column(name="TILL_LAST_ACTIVE")
	private Timestamp tillLastActive;
	
	@Column(name="TILL_DEVICE_ID", length = 200)
	private String tillDeviceId;
	
	@Column(name="TILL_UPDATE", length = 1)
	private Character tillUpdate;
	
	@Column(name="TILL_BCID", length = 500)
	private String tillBCid;
	
	 @OneToMany(mappedBy = "merchantTills", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantTillPosAssignment> merchantTillPosAssignments = new HashSet<MerchantTillPosAssignment>(0);
	
	
	 @OneToMany(mappedBy = "merchantTills", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantOutletTills> merchantOutletTillses = new HashSet<MerchantOutletTills>(0);
	
	
	 @OneToMany(mappedBy = "merchantTills", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<ZReport> ZReports = new HashSet<ZReport>(0);
	
	 @OneToMany(mappedBy = "merchantTills", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantTillTxn> merchantTillTxns = new HashSet<MerchantTillTxn>(0);

	public MerchantTills() {
	}

	public MerchantTills(long merchantTillId, Merchants merchants,
			String tillCode, String tillPassword, double tillFloatAmount) {
		this.merchantTillId = merchantTillId;
		this.merchants = merchants;
		this.tillCode = tillCode;
		this.tillPassword = tillPassword;
		this.tillFloatAmount = tillFloatAmount;
	}

	public MerchantTills(long merchantTillId, Merchants merchants,
			String tillCode, String tillPassword, String tillFirstname,
			String tillLastname, String tillAddress1, String tillAddress2,
			String tillCity, String tillState, String tillCountry,
			String tillZipcode, String tillPhone, String tillEmail,
			double tillFloatAmount, Timestamp tillFromdate,
			Timestamp tillTodate, Character tillIsActive,
			Character tillIsVerified, Character tillIsSupervisor,
			Timestamp tillLastLogin, Timestamp tillLastLogout,
			Timestamp tillLastActive, String tillDeviceId, Character tillUpdate,
			Set merchantTillPosAssignments, Set merchantOutletTillses,
			Set ZReports, Set merchantTillTxns, String tillBCid) {
		this.merchantTillId = merchantTillId;
		this.merchants = merchants;
		this.tillCode = tillCode;
		this.tillPassword = tillPassword;
		this.tillFirstname = tillFirstname;
		this.tillLastname = tillLastname;
		this.tillAddress1 = tillAddress1;
		this.tillAddress2 = tillAddress2;
		this.tillCity = tillCity;
		this.tillState = tillState;
		this.tillCountry = tillCountry;
		this.tillZipcode = tillZipcode;
		this.tillPhone = tillPhone;
		this.tillEmail = tillEmail;
		this.tillFloatAmount = tillFloatAmount;
		this.tillFromdate = tillFromdate;
		this.tillTodate = tillTodate;
		this.tillIsActive = tillIsActive;
		this.tillIsVerified = tillIsVerified;
		this.tillIsSupervisor = tillIsSupervisor;
		this.tillLastLogin = tillLastLogin;
		this.tillLastLogout = tillLastLogout;
		this.tillLastActive = tillLastActive;
		this.tillDeviceId = tillDeviceId;
		this.tillUpdate = tillUpdate;
		this.merchantTillPosAssignments = merchantTillPosAssignments;
		this.merchantOutletTillses = merchantOutletTillses;
		this.ZReports = ZReports;
		this.merchantTillTxns = merchantTillTxns;
		this.tillBCid=tillBCid;
	}

	public long getMerchantTillId() {
		return this.merchantTillId;
	}

	public void setMerchantTillId(long merchantTillId) {
		this.merchantTillId = merchantTillId;
	}

	public Merchants getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchants merchants) {
		this.merchants = merchants;
	}

	public String getTillCode() {
		return this.tillCode;
	}

	public void setTillCode(String tillCode) {
		this.tillCode = tillCode;
	}

	public String getTillPassword() {
		return this.tillPassword;
	}

	public void setTillPassword(String tillPassword) {
		this.tillPassword = tillPassword;
	}

	public String getTillFirstname() {
		return this.tillFirstname;
	}

	public void setTillFirstname(String tillFirstname) {
		this.tillFirstname = tillFirstname;
	}

	public String getTillLastname() {
		return this.tillLastname;
	}

	public void setTillLastname(String tillLastname) {
		this.tillLastname = tillLastname;
	}

	public String getTillAddress1() {
		return this.tillAddress1;
	}

	public void setTillAddress1(String tillAddress1) {
		this.tillAddress1 = tillAddress1;
	}

	public String getTillAddress2() {
		return this.tillAddress2;
	}

	public void setTillAddress2(String tillAddress2) {
		this.tillAddress2 = tillAddress2;
	}

	public String getTillCity() {
		return this.tillCity;
	}

	public void setTillCity(String tillCity) {
		this.tillCity = tillCity;
	}

	public String getTillState() {
		return this.tillState;
	}

	public void setTillState(String tillState) {
		this.tillState = tillState;
	}

	public String getTillCountry() {
		return this.tillCountry;
	}

	public void setTillCountry(String tillCountry) {
		this.tillCountry = tillCountry;
	}

	public String getTillZipcode() {
		return this.tillZipcode;
	}

	public void setTillZipcode(String tillZipcode) {
		this.tillZipcode = tillZipcode;
	}

	public String getTillPhone() {
		return this.tillPhone;
	}

	public void setTillPhone(String tillPhone) {
		this.tillPhone = tillPhone;
	}

	public String getTillEmail() {
		return this.tillEmail;
	}

	public void setTillEmail(String tillEmail) {
		this.tillEmail = tillEmail;
	}

	public double getTillFloatAmount() {
		return this.tillFloatAmount;
	}

	public void setTillFloatAmount(double tillFloatAmount) {
		this.tillFloatAmount = tillFloatAmount;
	}

	public Timestamp getTillFromdate() {
		return this.tillFromdate;
	}

	public void setTillFromdate(Timestamp tillFromdate) {
		this.tillFromdate = tillFromdate;
	}

	public Timestamp getTillTodate() {
		return this.tillTodate;
	}

	public void setTillTodate(Timestamp tillTodate) {
		this.tillTodate = tillTodate;
	}

	public Character getTillIsActive() {
		return this.tillIsActive;
	}

	public void setTillIsActive(Character tillIsActive) {
		this.tillIsActive = tillIsActive;
	}

	public Character getTillIsVerified() {
		return this.tillIsVerified;
	}

	public void setTillIsVerified(Character tillIsVerified) {
		this.tillIsVerified = tillIsVerified;
	}

	public Character getTillIsSupervisor() {
		return this.tillIsSupervisor;
	}

	public void setTillIsSupervisor(Character tillIsSupervisor) {
		this.tillIsSupervisor = tillIsSupervisor;
	}

	public Timestamp getTillLastLogin() {
		return this.tillLastLogin;
	}

	public void setTillLastLogin(Timestamp tillLastLogin) {
		this.tillLastLogin = tillLastLogin;
	}

	public Timestamp getTillLastLogout() {
		return this.tillLastLogout;
	}

	public void setTillLastLogout(Timestamp tillLastLogout) {
		this.tillLastLogout = tillLastLogout;
	}

	public Timestamp getTillLastActive() {
		return this.tillLastActive;
	}

	public void setTillLastActive(Timestamp tillLastActive) {
		this.tillLastActive = tillLastActive;
	}

	public String getTillDeviceId() {
		return this.tillDeviceId;
	}

	public void setTillDeviceId(String tillDeviceId) {
		this.tillDeviceId = tillDeviceId;
	}
	 
	public Character getTillUpdate() {
		return tillUpdate;
	}

	public void setTillUpdate(Character tillUpdate) {
		this.tillUpdate = tillUpdate;
	}

	public Set getMerchantTillPosAssignments() {
		return this.merchantTillPosAssignments;
	}

	public void setMerchantTillPosAssignments(Set merchantTillPosAssignments) {
		this.merchantTillPosAssignments = merchantTillPosAssignments;
	}

	public Set getMerchantOutletTillses() {
		return this.merchantOutletTillses;
	}

	public void setMerchantOutletTillses(Set merchantOutletTillses) {
		this.merchantOutletTillses = merchantOutletTillses;
	}

	public Set getZReports() {
		return this.ZReports;
	}

	public void setZReports(Set ZReports) {
		this.ZReports = ZReports;
	}

	public Set getMerchantTillTxns() {
		return this.merchantTillTxns;
	}

	public void setMerchantTillTxns(Set merchantTillTxns) {
		this.merchantTillTxns = merchantTillTxns;
	}
	public String gettillBCid() {
		return this.tillBCid;
	}

	public void settillBCid(String tillBCid) {
		this.tillBCid = tillBCid;
	}


}
