package com.fidypay.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

// Generated Feb 16, 2018 1:42:37 PM by Hibernate Tools 4.0.0


/**
 * MerchantRegisterEnquiry generated by hbm2java
 */

@Entity
///@Table(name = "MERCHANT_REGISTER_ENQUIRY")
@EntityListeners(AuditingEntityListener.class)
@Table(name = "MERCHANT_REGISTER_ENQUIRY", indexes = {
		@Index(name = "index_ENQUIRY_ID", columnList = "ENQUIRY_ID"),
		@Index(name = "index_FIRST_NAME", columnList = "FIRST_NAME"),
		@Index(name = "index_LAST_NAME", columnList = "LAST_NAME"),
		@Index(name = "index_BUSINESS_NAME", columnList = "BUSINESS_NAME"),
		@Index(name = "index_GENDER", columnList = "GENDER"),
		@Index(name = "index_EMAIL", columnList = "EMAIL"),
		@Index(name = "index_PHONE_NO", columnList = "PHONE_NO"),
		@Index(name = "index_MERCHANT_PASSWORD", columnList = "MERCHANT_PASSWORD"),
		@Index(name = "index_MERCHANT_ADDRESS", columnList = "MERCHANT_ADDRESS"),
		@Index(name = "index_CITY", columnList = "CITY"),
		@Index(name = "index_STATE", columnList = "STATE"),
		@Index(name = "index_PINCODE", columnList = "PINCODE"),
		@Index(name = "index_COUNTRY", columnList = "COUNTRY"),
		@Index(name = "index_LATITUDE", columnList = "LATITUDE"),
		@Index(name = "index_LONGITUDE", columnList = "LONGITUDE"),
		@Index(name = "index_OUTLET_TYPE", columnList = "OUTLET_TYPE"),
		@Index(name = "index_AGENT_NAME", columnList = "AGENT_NAME")
				})
public class MerchantRegisterEnquiry implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ENQUIRY_ID")
	private long enquiryId;
	
	@Column(name="FIRST_NAME", nullable = false,length=200)
	private String fisrt_name;
	
	@Column(name="LAST_NAME", nullable = false,length=200)
	private String last_name;
	
	@Column(name="BUSINESS_NAME", nullable = false,length=500)
	private String business_name;
	
	@Column(name="GENDER", nullable = false,length=200)
	private String gender;
	
	@Column(name="EMAIL", nullable = false,length=500)
	private String email;
	
	@Column(name="PHONE_NO", nullable = false,length=200)
	private String phone_no;
	
	@Column(name="MERCHANT_PASSWORD", nullable = false,length=200)
	private String merchant_password;
	
	@Column(name="MERCHANT_ADDRESS", nullable = false,length=500)
	private String merchant_address;
	
	@Column(name="CITY", nullable = false ,length=200)
	private String city;
	
	@Column(name="STATE", nullable = false,length=200)
	private String state;
	
	@Column(name="PINCODE", nullable = false,length=200)
	private String pincode;
	
	@Column(name="COUNTRY", nullable = false,length=200)
	private String country;
	
	@Column(name="LATITUDE", nullable = false,length=200)
	private String latitude;
	
	@Column(name="LONGITUDE", nullable = false,length=200)
	private String longitude;
	
	@Column(name="OUTLET_TYPE", nullable = false,length=200)
	private String outlet_type;
	
	@Column(name="AGENT_NAME", nullable = false,length=200)
	private String agent_name;
	
	public MerchantRegisterEnquiry() {
	}

	public MerchantRegisterEnquiry(long enquiryId, String fisrt_name, String last_name, String business_name,
									String gender, String email, String phone_no, String merchant_password, 
									String merchant_address, String city, String state, String pincode, String country,
									String latitude, String longitude, String outlet_type, String agent_name) {
		this.setEnquiryId(enquiryId);
		this.setFisrt_name(fisrt_name);
		this.setLast_name(last_name);
		this.setBusiness_name(business_name);
		this.setGender(gender);
		this.setEmail(email);
		this.setPhone_no(phone_no);
		this.setMerchant_address(merchant_password);
		this.setMerchant_address(merchant_address);
		this.setCity(city);
		this.setState(state);
		this.setPincode(pincode);
		this.setCountry(country);
		this.setLatitude(latitude);
		this.setLongitude(longitude);
		this.setOutlet_type(outlet_type);
		this.setAgent_name(agent_name);
	}

	public long getEnquiryId() {
		return enquiryId;
	}

	public void setEnquiryId(long enquiryId) {
		this.enquiryId = enquiryId;
	}

	public String getFisrt_name() {
		return fisrt_name;
	}

	public void setFisrt_name(String fisrt_name) {
		this.fisrt_name = fisrt_name;
	}

	public String getLast_name() {
		return last_name;
	}

	public void setLast_name(String last_name) {
		this.last_name = last_name;
	}

	public String getBusiness_name() {
		return business_name;
	}

	public void setBusiness_name(String business_name) {
		this.business_name = business_name;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone_no() {
		return phone_no;
	}

	public void setPhone_no(String phone_no) {
		this.phone_no = phone_no;
	}

	public String getMerchant_password() {
		return merchant_password;
	}

	public void setMerchant_password(String merchant_password) {
		this.merchant_password = merchant_password;
	}

	public String getMerchant_address() {
		return merchant_address;
	}

	public void setMerchant_address(String merchant_address) {
		this.merchant_address = merchant_address;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPincode() {
		return pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getLatitude() {
		return latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongitude() {
		return longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getOutlet_type() {
		return outlet_type;
	}

	public void setOutlet_type(String outlet_type) {
		this.outlet_type = outlet_type;
	}

	public String getAgent_name() {
		return agent_name;
	}

	public void setAgent_name(String agent_name) {
		this.agent_name = agent_name;
	}

}
