package com.fidypay.entity;

// Generated Jun 30, 2015 7:57:33 PM by Hibernate Tools 4.0.0

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * Merchants generated by hbm2java
 */

@Entity
@Table(name = "MERCHANTS")
@EntityListeners(AuditingEntityListener.class)
public class Merchants implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MERCHANT_ID")
	private long merchantId;

	@ManyToOne
	@JoinColumn(name = "SEC_QUESTION_ID")
	private SecurityQuestions securityQuestions;

	@ManyToOne
	@JoinColumn(name = "MERCHANT_TYPE_ID")
	private MerchantType merchantType;

	@Column(name = "MERCHANT_EMAIL", nullable = false, length = 200)
	private String merchantEmail;

	@Column(name = "MERCHANT_PHONE", nullable = false, length = 100)
	private String merchantPhone;

	@Column(name = "MERCHANT_PASSWORD", nullable = false, length = 200)
	private String merchantPassword;

	@Column(name = "MERCHANT_FIRSTNAME", length = 100)
	private String merchantFirstname;

	@Column(name = "MERCHANT_LASTNAME", length = 100)
	private String merchantLastname;

	@Column(name = "MERCHANT_ADDRESS1", length = 200)
	private String merchantAddress1;

	@Column(name = "MERCHANT_ADDRESS2", length = 200)
	private String merchantAddress2;

	@Column(name = "MERCHANT_CITY", length = 100)
	private String merchantCity;

	@Column(name = "MERCHANT_STATE", length = 100)
	private String merchantState;

	@Column(name = "MERCHANT_COUNTRY", length = 100)
	private String merchantCountry;

	@Column(name = "MERCHANT_ZIPCODE", length = 50)
	private String merchantZipcode;

	@Column(name = "MERCHANT_FROMDATE")
	private Timestamp merchantFromdate;

	@Column(name = "MERCHANT_LASTLOGIN")
	private Timestamp merchantLastlogin;

	@Column(name = "MERCHANT_FLOAT_AMOUNT")
	private Double merchantFloatAmount;

	@Column(name = "MERCHANT_SETTLEMENT_FREQUENCY")
	private String merchantSettlementFrequency;

	@Column(name = "MERCHANT_COMMISSION")
	private Long merchantCommission;

	@Column(name = "MERCHANT_BANK_NAME", length = 100)
	private String merchantBankName;

	@Column(name = "MERCHANT_BANK_BRANCH", length = 100)
	private String merchantBankBranch;

	@Column(name = "MERCHANT_BANK_CODE", length = 100)
	private String merchantBankCode;

	@Column(name = "MERCHANT_ACCOUNT_NO", length = 100)
	private String merchantAccountNo;

	@Column(name = "IS_MERCHANT_ACTIVE", length = 1)
	private Character isMerchantActive;

	@Column(name = "MERCHANT_LOGIN_COUNT", length = 1)
	private Character merchantLoginCount;

	@Column(name = "MERCHANT_BUSINESS_NAME", length = 300)
	private String merchantBusinessName;

	@Column(name = "MERCHANT_VAT_ID", length = 100)
	private String merchantVatId;

	@Column(name = "IS_MERCHANT_EMAIL_VERIFIED", length = 1)
	private Character isMerchantEmailVerified;

	@Column(name = "IS_MERCHANT_PHONE_VERIFIED", length = 1)
	private Character isMerchantPhoneVerified;

	@Column(name = "GENDER", length = 1)
	private Character gender;

	@Column(name = "MERCHANT_NATIONALITY", length = 200)
	private String merchantNationality;

	@Column(name = "DATE_ESTABLISHED")
	private Timestamp dateEstablished;

	@Column(name = "ESTABLISH_TYPE", length = 200)
	private String establishType;

	@Column(name = "SEC_ANSWER", length = 200)
	private String secAnswer;

	@Column(name = "MERCHANT_BANK_DOC_TYPE", length = 100)
	private String merchantBankDocType;

	@Column(name = "MERCHANT_BANK_DOC_TYPE_PATH", length = 300)
	private String merchantBankDocTypePath;

	@Column(name = "IS_BANK_DOC_VERIFIED", length = 1)
	private Character isBankDocVerified;

	@Column(name = "SECOND_SEC_QUESTION_ID")
	private Long secondSecQuestionId;

	@Column(name = "SECOND_SEC_ANSWER", length = 200)
	private String secondSecAnswer;

	@Column(name = "MERCHANT_ALTERNATE_EMAIL", length = 300)
	private String merchantAlternateEmail;

	@OneToMany(mappedBy = "merchants", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantSettlements> merchantSettlementses = new HashSet<MerchantSettlements>(0);

	@OneToMany(mappedBy = "merchants", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantPaymentChannels> merchantPaymentChannelses = new HashSet<MerchantPaymentChannels>(0);

	@OneToMany(mappedBy = "merchants", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantAddonWalletInfo> merchantAddonWalletInfos = new HashSet<MerchantAddonWalletInfo>(0);

	@OneToMany(mappedBy = "merchants", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantTransactions> merchantTransactionses = new HashSet<MerchantTransactions>(0);

	@OneToMany(mappedBy = "merchants", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantTills> merchantTillses = new HashSet<MerchantTills>(0);

	@OneToMany(mappedBy = "merchants", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantServices> merchantServiceses = new HashSet<MerchantServices>(0);

	@OneToMany(mappedBy = "merchants", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantReconciliation> merchantReconciliations = new HashSet<MerchantReconciliation>(0);

	@OneToMany(mappedBy = "merchants", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantOutlets> merchantOutletses = new HashSet<MerchantOutlets>(0);

	@OneToMany(mappedBy = "merchants", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<PosDevices> posDeviceses = new HashSet<PosDevices>(0);

	@OneToMany(mappedBy = "merchants", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantWalletInfo> merchantWalletInfos = new HashSet<MerchantWalletInfo>(0);

	@OneToMany(mappedBy = "merchants", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantFloatManage> merchantFloatManages = new HashSet<MerchantFloatManage>(0);

	@OneToMany(mappedBy = "merchants", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantWalletTransactions> merchantWalletTransactionses = new HashSet<MerchantWalletTransactions>(0);

	@Column(name = "AUTH_USER_ID", nullable = false, length = 200)
	private long authUserId;

	@Column(name = "VERTICAL_REGIONS", length = 300)
	private String verticalRegions;

	public Merchants() {
	}

	public Merchants(long merchantId, String merchantEmail, String merchantPhone, String merchantPassword) {
		this.merchantId = merchantId;
		this.merchantEmail = merchantEmail;
		this.merchantPhone = merchantPhone;
		this.merchantPassword = merchantPassword;
	}

	public Merchants(long merchantId) {
		this.merchantId = merchantId;
	}

	public Merchants(long merchantId, SecurityQuestions securityQuestions, MerchantType merchantType,
			String merchantEmail, String merchantPhone, String merchantPassword, String merchantFirstname,
			String merchantLastname, String merchantAddress1, String merchantAddress2, String merchantCity,
			String merchantState, String merchantCountry, String merchantZipcode, Timestamp merchantFromdate,
			Timestamp merchantLastlogin, Double merchantFloatAmount, String merchantSettlementFrequency,
			Long merchantCommission, String merchantBankName, String merchantBankBranch, String merchantBankCode,
			String merchantAccountNo, Character isMerchantActive, Character merchantLoginCount,
			String merchantBusinessName, String merchantVatId, Character isMerchantEmailVerified,
			Character isMerchantPhoneVerified, Character gender, String merchantNationality, Timestamp dateEstablished,
			String establishType, String secAnswer, String merchantBankDocType, String merchantBankDocTypePath,
			Character isBankDocVerified, Long secondSecQuestionId, String secondSecAnswer,
			String merchantAlternateEmail, Set merchantSettlementses, Set merchantPaymentChannelses,
			Set merchantAddonWalletInfos, Set merchantTransactionses, Set merchantTillses, Set merchantServiceses,
			Set merchantReconciliations, Set merchantOutletses, Set posDeviceses, Set merchantFloatManages,
			Set merchantWalletInfos) {
		this.merchantId = merchantId;
		this.securityQuestions = securityQuestions;
		this.merchantType = merchantType;
		this.merchantEmail = merchantEmail;
		this.merchantPhone = merchantPhone;
		this.merchantPassword = merchantPassword;
		this.merchantFirstname = merchantFirstname;
		this.merchantLastname = merchantLastname;
		this.merchantAddress1 = merchantAddress1;
		this.merchantAddress2 = merchantAddress2;
		this.merchantCity = merchantCity;
		this.merchantState = merchantState;
		this.merchantCountry = merchantCountry;
		this.merchantZipcode = merchantZipcode;
		this.merchantFromdate = merchantFromdate;
		this.merchantLastlogin = merchantLastlogin;
		this.merchantFloatAmount = merchantFloatAmount;
		this.merchantSettlementFrequency = merchantSettlementFrequency;
		this.merchantCommission = merchantCommission;
		this.merchantBankName = merchantBankName;
		this.merchantBankBranch = merchantBankBranch;
		this.merchantBankCode = merchantBankCode;
		this.merchantAccountNo = merchantAccountNo;
		this.isMerchantActive = isMerchantActive;
		this.merchantLoginCount = merchantLoginCount;
		this.merchantBusinessName = merchantBusinessName;
		this.merchantVatId = merchantVatId;
		this.isMerchantEmailVerified = isMerchantEmailVerified;
		this.isMerchantPhoneVerified = isMerchantPhoneVerified;
		this.gender = gender;
		this.merchantNationality = merchantNationality;
		this.dateEstablished = dateEstablished;
		this.establishType = establishType;
		this.secAnswer = secAnswer;
		this.merchantBankDocType = merchantBankDocType;
		this.merchantBankDocTypePath = merchantBankDocTypePath;
		this.isBankDocVerified = isBankDocVerified;
		this.secondSecQuestionId = secondSecQuestionId;
		this.secondSecAnswer = secondSecAnswer;
		this.merchantAlternateEmail = merchantAlternateEmail;
		this.merchantSettlementses = merchantSettlementses;
		this.merchantPaymentChannelses = merchantPaymentChannelses;
		this.merchantAddonWalletInfos = merchantAddonWalletInfos;
		this.merchantTransactionses = merchantTransactionses;
		this.merchantTillses = merchantTillses;
		this.merchantServiceses = merchantServiceses;
		this.merchantReconciliations = merchantReconciliations;
		this.merchantOutletses = merchantOutletses;
		this.posDeviceses = posDeviceses;
		this.merchantFloatManages = merchantFloatManages;
		this.merchantWalletInfos = merchantWalletInfos;
	}

	public String getVerticalRegions() {
		return verticalRegions;
	}

	public void setVerticalRegions(String verticalRegions) {
		this.verticalRegions = verticalRegions;
	}

	public long getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(long merchantId) {
		this.merchantId = merchantId;
	}

	public SecurityQuestions getSecurityQuestions() {
		return this.securityQuestions;
	}

	public void setSecurityQuestions(SecurityQuestions securityQuestions) {
		this.securityQuestions = securityQuestions;
	}

	public MerchantType getMerchantType() {
		return this.merchantType;
	}

	public void setMerchantType(MerchantType merchantType) {
		this.merchantType = merchantType;
	}

	public String getMerchantEmail() {
		return this.merchantEmail;
	}

	public void setMerchantEmail(String merchantEmail) {
		this.merchantEmail = merchantEmail;
	}

	public String getMerchantPhone() {
		return this.merchantPhone;
	}

	public void setMerchantPhone(String merchantPhone) {
		this.merchantPhone = merchantPhone;
	}

	public String getMerchantPassword() {
		return this.merchantPassword;
	}

	public void setMerchantPassword(String merchantPassword) {
		this.merchantPassword = merchantPassword;
	}

	public String getMerchantFirstname() {
		return this.merchantFirstname;
	}

	public void setMerchantFirstname(String merchantFirstname) {
		this.merchantFirstname = merchantFirstname;
	}

	public String getMerchantLastname() {
		return this.merchantLastname;
	}

	public void setMerchantLastname(String merchantLastname) {
		this.merchantLastname = merchantLastname;
	}

	public String getMerchantAddress1() {
		return this.merchantAddress1;
	}

	public void setMerchantAddress1(String merchantAddress1) {
		this.merchantAddress1 = merchantAddress1;
	}

	public String getMerchantAddress2() {
		return this.merchantAddress2;
	}

	public void setMerchantAddress2(String merchantAddress2) {
		this.merchantAddress2 = merchantAddress2;
	}

	public String getMerchantCity() {
		return this.merchantCity;
	}

	public void setMerchantCity(String merchantCity) {
		this.merchantCity = merchantCity;
	}

	public String getMerchantState() {
		return this.merchantState;
	}

	public void setMerchantState(String merchantState) {
		this.merchantState = merchantState;
	}

	public String getMerchantCountry() {
		return this.merchantCountry;
	}

	public void setMerchantCountry(String merchantCountry) {
		this.merchantCountry = merchantCountry;
	}

	public String getMerchantZipcode() {
		return this.merchantZipcode;
	}

	public void setMerchantZipcode(String merchantZipcode) {
		this.merchantZipcode = merchantZipcode;
	}

	public Timestamp getMerchantFromdate() {
		return this.merchantFromdate;
	}

	public void setMerchantFromdate(Timestamp merchantFromdate) {
		this.merchantFromdate = merchantFromdate;
	}

	public Timestamp getMerchantLastlogin() {
		return this.merchantLastlogin;
	}

	public void setMerchantLastlogin(Timestamp merchantLastlogin) {
		this.merchantLastlogin = merchantLastlogin;
	}

	public Double getMerchantFloatAmount() {
		return this.merchantFloatAmount;
	}

	public void setMerchantFloatAmount(Double merchantFloatAmount) {
		this.merchantFloatAmount = merchantFloatAmount;
	}

	public String getMerchantSettlementFrequency() {
		return this.merchantSettlementFrequency;
	}

	public void setMerchantSettlementFrequency(String merchantSettlementFrequency) {
		this.merchantSettlementFrequency = merchantSettlementFrequency;
	}

	public Long getMerchantCommission() {
		return this.merchantCommission;
	}

	public void setMerchantCommission(Long merchantCommission) {
		this.merchantCommission = merchantCommission;
	}

	public String getMerchantBankName() {
		return this.merchantBankName;
	}

	public void setMerchantBankName(String merchantBankName) {
		this.merchantBankName = merchantBankName;
	}

	public String getMerchantBankBranch() {
		return this.merchantBankBranch;
	}

	public void setMerchantBankBranch(String merchantBankBranch) {
		this.merchantBankBranch = merchantBankBranch;
	}

	public String getMerchantBankCode() {
		return this.merchantBankCode;
	}

	public void setMerchantBankCode(String merchantBankCode) {
		this.merchantBankCode = merchantBankCode;
	}

	public String getMerchantAccountNo() {
		return this.merchantAccountNo;
	}

	public void setMerchantAccountNo(String merchantAccountNo) {
		this.merchantAccountNo = merchantAccountNo;
	}

	public Character getIsMerchantActive() {
		return isMerchantActive;
	}

	public void setIsMerchantActive(Character isMerchantActive) {
		this.isMerchantActive = isMerchantActive;
	}

	public Character getMerchantLoginCount() {
		return this.merchantLoginCount;
	}

	public void setMerchantLoginCount(Character merchantLoginCount) {
		this.merchantLoginCount = merchantLoginCount;
	}

	public String getMerchantBusinessName() {
		return this.merchantBusinessName;
	}

	public void setMerchantBusinessName(String merchantBusinessName) {
		this.merchantBusinessName = merchantBusinessName;
	}

	public String getMerchantVatId() {
		return this.merchantVatId;
	}

	public void setMerchantVatId(String merchantVatId) {
		this.merchantVatId = merchantVatId;
	}

	public Character getIsMerchantEmailVerified() {
		return this.isMerchantEmailVerified;
	}

	public void setIsMerchantEmailVerified(Character isMerchantEmailVerified) {
		this.isMerchantEmailVerified = isMerchantEmailVerified;
	}

	public Character getIsMerchantPhoneVerified() {
		return this.isMerchantPhoneVerified;
	}

	public void setIsMerchantPhoneVerified(Character isMerchantPhoneVerified) {
		this.isMerchantPhoneVerified = isMerchantPhoneVerified;
	}

	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	public String getMerchantNationality() {
		return this.merchantNationality;
	}

	public void setMerchantNationality(String merchantNationality) {
		this.merchantNationality = merchantNationality;
	}

	public Timestamp getDateEstablished() {
		return this.dateEstablished;
	}

	public void setDateEstablished(Timestamp dateEstablished) {
		this.dateEstablished = dateEstablished;
	}

	public String getEstablishType() {
		return this.establishType;
	}

	public void setEstablishType(String establishType) {
		this.establishType = establishType;
	}

	public String getSecAnswer() {
		return this.secAnswer;
	}

	public void setSecAnswer(String secAnswer) {
		this.secAnswer = secAnswer;
	}

	public String getMerchantBankDocType() {
		return this.merchantBankDocType;
	}

	public void setMerchantBankDocType(String merchantBankDocType) {
		this.merchantBankDocType = merchantBankDocType;
	}

	public String getMerchantBankDocTypePath() {
		return this.merchantBankDocTypePath;
	}

	public void setMerchantBankDocTypePath(String merchantBankDocTypePath) {
		this.merchantBankDocTypePath = merchantBankDocTypePath;
	}

	public Character getIsBankDocVerified() {
		return this.isBankDocVerified;
	}

	public void setIsBankDocVerified(Character isBankDocVerified) {
		this.isBankDocVerified = isBankDocVerified;
	}

	public Long getSecondSecQuestionId() {
		return this.secondSecQuestionId;
	}

	public void setSecondSecQuestionId(Long secondSecQuestionId) {
		this.secondSecQuestionId = secondSecQuestionId;
	}

	public String getSecondSecAnswer() {
		return this.secondSecAnswer;
	}

	public void setSecondSecAnswer(String secondSecAnswer) {
		this.secondSecAnswer = secondSecAnswer;
	}

	public String getMerchantAlternateEmail() {
		return this.merchantAlternateEmail;
	}

	public void setMerchantAlternateEmail(String merchantAlternateEmail) {
		this.merchantAlternateEmail = merchantAlternateEmail;
	}

	public Set getMerchantSettlementses() {
		return this.merchantSettlementses;
	}

	public void setMerchantSettlementses(Set merchantSettlementses) {
		this.merchantSettlementses = merchantSettlementses;
	}

	public Set getMerchantPaymentChannelses() {
		return this.merchantPaymentChannelses;
	}

	public void setMerchantPaymentChannelses(Set merchantPaymentChannelses) {
		this.merchantPaymentChannelses = merchantPaymentChannelses;
	}

	public Set getMerchantAddonWalletInfos() {
		return this.merchantAddonWalletInfos;
	}

	public void setMerchantAddonWalletInfos(Set merchantAddonWalletInfos) {
		this.merchantAddonWalletInfos = merchantAddonWalletInfos;
	}

	public Set getMerchantTransactionses() {
		return this.merchantTransactionses;
	}

	public void setMerchantTransactionses(Set merchantTransactionses) {
		this.merchantTransactionses = merchantTransactionses;
	}

	public Set getMerchantTillses() {
		return this.merchantTillses;
	}

	public void setMerchantTillses(Set merchantTillses) {
		this.merchantTillses = merchantTillses;
	}

	public Set getMerchantServiceses() {
		return this.merchantServiceses;
	}

	public void setMerchantServiceses(Set merchantServiceses) {
		this.merchantServiceses = merchantServiceses;
	}

	public Set getMerchantReconciliations() {
		return this.merchantReconciliations;
	}

	public void setMerchantReconciliations(Set merchantReconciliations) {
		this.merchantReconciliations = merchantReconciliations;
	}

	public Set getMerchantOutletses() {
		return this.merchantOutletses;
	}

	public void setMerchantOutletses(Set merchantOutletses) {
		this.merchantOutletses = merchantOutletses;
	}

	public Set getPosDeviceses() {
		return this.posDeviceses;
	}

	public void setPosDeviceses(Set posDeviceses) {
		this.posDeviceses = posDeviceses;
	}

	public Set getMerchantFloatManages() {
		return this.merchantFloatManages;
	}

	public void setMerchantFloatManages(Set merchantFloatManages) {
		this.merchantFloatManages = merchantFloatManages;
	}

	public Set getMerchantWalletInfos() {
		return this.merchantWalletInfos;
	}

	public void setMerchantWalletInfos(Set merchantWalletInfos) {
		this.merchantWalletInfos = merchantWalletInfos;
	}

	public long getAuthUserId() {
		return authUserId;
	}

	public void setAuthUserId(long authUserId) {
		this.authUserId = authUserId;
	}

}
