package com.fidypay.entity;

// Generated Jun 12, 2015 7:50:13 PM by Hibernate Tools 4.0.0


import java.sql.Timestamp;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * MerchantWalletInfo generated by hbm2java
 */

@Entity
//@Table(name = "MERCHANT_WALLET_INFO")
@EntityListeners(AuditingEntityListener.class)
@Table(name = "MERCHANT_WALLET_INFO", indexes = {
		@Index(name = "index_MERCH_WALLET_ID", columnList = "MERCH_WALLET_ID"),
		@Index(name = "index_MERCHANT_ID", columnList = "MERCHANT_ID"),
		@Index(name = "index_MERCH_WALLET_ACCOUNT_NO", columnList = "MERCH_WALLET_ACCOUNT_NO"),
		@Index(name = "index_MERCH_WALLET_PIN", columnList = "MERCH_WALLET_PIN"),
		@Index(name = "index_MERCH_WALLET_FROM_DATE", columnList = "MERCH_WALLET_FROM_DATE"),
		@Index(name = "index_MERCH_WALLET_TO_DATE", columnList = "MERCH_WALLET_TO_DATE"),
		@Index(name = "index_MERCH_WALLET_AMOUNT", columnList = "MERCH_WALLET_AMOUNT"),
		@Index(name = "index_MERCH_PIN_LAST_CHANGED_DATE", columnList = "MERCH_PIN_LAST_CHANGED_DATE"),
		@Index(name = "index_MERCH_WALLET_PIC", columnList = "MERCH_WALLET_PIC"),
		@Index(name = "index_MERCH_ID_PROOF_TYPE", columnList = "MERCH_ID_PROOF_TYPE"),
		@Index(name = "index_MERCH_ID_PROOF_NUMBER", columnList = "MERCH_ID_PROOF_NUMBER"),
		@Index(name = "index_MERCH_ID_PROOF_PATH", columnList = "MERCH_ID_PROOF_PATH"),
		@Index(name = "index_MERCH_ADDRESS_PROOF_TYPE", columnList = "MERCH_ADDRESS_PROOF_TYPE"),
		@Index(name = "index_MERCH_ADDRESS_PROOF_NUMBER", columnList = "MERCH_ADDRESS_PROOF_NUMBER"),
		@Index(name = "index_MERCH_ADDRESS_PROOF_PATH", columnList = "MERCH_ADDRESS_PROOF_PATH"),
		@Index(name = "index_IS_ID_PROOF_VERIFIED", columnList = "IS_ID_PROOF_VERIFIED"),
		@Index(name = "index_IS_ADDRESS_PROOF_VERIFIED", columnList = "IS_ADDRESS_PROOF_VERIFIED"),
		@Index(name = "index_IS_MERCH_KYC_COMPLETE", columnList = "IS_MERCH_KYC_COMPLETE"),
		@Index(name = "index_IS_MERCH_WALLET_ACTIVE", columnList = "IS_MERCH_WALLET_ACTIVE"),
		@Index(name = "index_MERCH_PERMIT_TYPE", columnList = "MERCH_PERMIT_TYPE"),
		@Index(name = "index_MERCH_PERMIT_TYPE_PATH", columnList = "MERCH_PERMIT_TYPE_PATH"),
		@Index(name = "index_ITAX_CERTIFICATE_PATH", columnList = "ITAX_CERTIFICATE_PATH"),
		@Index(name = "index_EXTRA_DOCS_NAME", columnList = "EXTRA_DOCS_NAME"),
		@Index(name = "index_EXTRA_DOCS_PATH", columnList = "EXTRA_DOCS_PATH"),
		@Index(name = "index_MERCH_BUSINESS_LOGO", columnList = "MERCH_BUSINESS_LOGO"),
		@Index(name = "index_MERCHANT_VAT_ID", columnList = "MERCHANT_VAT_ID"),
		@Index(name = "index_IS_ITAX_VERIFIED", columnList = "IS_ITAX_VERIFIED"),
		@Index(name = "index_IS_PERMIT_VERIFIED", columnList = "IS_PERMIT_VERIFIED"),
		@Index(name = "index_IS_EXTRA_DOC_VERIFIED", columnList = "IS_EXTRA_DOC_VERIFIED")
		})
public class MerchantWalletInfo {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MERCH_WALLET_ID")
	private long merchWalletId;
	
	@ManyToOne
	@JoinColumn(name = "MERCHANT_ID")
    private Merchants merchants;
	
	@Column(name="MERCH_WALLET_ACCOUNT_NO", length = 100)
	private String merchWalletAccountNo;
	
	@Column(name="MERCH_WALLET_PIN", length =50)
	private String merchWalletPin;
	
	@Column(name="MERCH_WALLET_FROM_DATE")
	private Timestamp merchWalletFromDate;
	
	@Column(name="MERCH_WALLET_TO_DATE")
	private Timestamp merchWalletToDate;
	
	@Column(name="MERCH_WALLET_AMOUNT")
	private Double merchWalletAmount;
	
	@Column(name="MERCH_PIN_LAST_CHANGED_DATE")
	private Timestamp merchPinLastChangedDate;
	
	@Column(name="MERCH_WALLET_PIC", length = 300)
	private String merchWalletPic;
	
	@Column(name="MERCH_ID_PROOF_TYPE", length = 100)
	private String merchIdProofType;
	
	@Column(name="MERCH_ID_PROOF_NUMBER", length = 300)
	private String merchIdProofNumber;
	
	@Column(name="MERCH_ID_PROOF_PATH", length = 300)
	private String merchIdProofPath;
	
	@Column(name="MERCH_ADDRESS_PROOF_TYPE", length = 100)
	private String merchAddressProofType;
	
	@Column(name="MERCH_ADDRESS_PROOF_NUMBER", length = 300) 
	private String merchAddressProofNumber;
	
	@Column(name="MERCH_ADDRESS_PROOF_PATH", length = 300)
	private String merchAddressProofPath;
	
	@Column(name="IS_ID_PROOF_VERIFIED", length = 1)
	private Character isIdProofVerified;
	
	@Column(name="IS_ADDRESS_PROOF_VERIFIED", length = 1)
	private Character isAddressProofVerified;
	
	@Column(name="IS_MERCH_KYC_COMPLETE", length = 1)
	private Character isMerchKycComplete;
	
	@Column(name="IS_MERCH_WALLET_ACTIVE", length = 1)
	private Character isMerchWalletActive;
	
	@Column(name="MERCH_PERMIT_TYPE", length = 100)
	private String merchPermitType;
	
	@Column(name="MERCH_PERMIT_TYPE_PATH", length = 300)
	private String merchPermitTypePath;
	
	@Column(name="ITAX_CERTIFICATE_PATH", length = 300)
	private String itaxCertificatePath;
	
	@Column(name="EXTRA_DOCS_NAME", length = 100)
	private String extraDocsName;
	
	@Column(name="EXTRA_DOCS_PATH", length = 300)
	private String extraDocsPath;
	
	@Column(name="MERCH_BUSINESS_LOGO", length = 300)
	private String merchBusinessLogo;
	
	@Column(name="MERCHANT_VAT_ID", length = 100)
	private String merchantVatId;
	
	@Column(name="IS_ITAX_VERIFIED", length = 1)
	private Character isItaxVerified;
	
	@Column(name="IS_PERMIT_VERIFIED", length = 1)
	private Character isPermitVerified;
	
	@Column(name="IS_EXTRA_DOC_VERIFIED", length = 1)
	private Character isExtraDocVerified;
	
	
	

	public MerchantWalletInfo() {
	}

	public MerchantWalletInfo(long merchWalletId, Merchants merchants,
			String merchWalletAccountNo, String merchWalletPin) {
		this.merchWalletId = merchWalletId;
		this.merchants = merchants;
		this.merchWalletAccountNo = merchWalletAccountNo;
		this.merchWalletPin = merchWalletPin;
	}

	public MerchantWalletInfo(long merchWalletId, Merchants merchants,
			String merchWalletAccountNo, String merchWalletPin,
			Timestamp merchWalletFromDate, Timestamp merchWalletToDate,
			Double merchWalletAmount, Timestamp merchPinLastChangedDate,
			String merchWalletPic, String merchIdProofType,
			String merchIdProofNumber, String merchIdProofPath,
			String merchAddressProofType, String merchAddressProofNumber,
			String merchAddressProofPath, Character isIdProofVerified,
			Character isAddressProofVerified, Character isMerchKycComplete,
			Character isMerchWalletActive, String merchPermitType,
			String merchPermitTypePath, String itaxCertificatePath,
			String extraDocsName, String extraDocsPath,
			String merchBusinessLogo, String merchantVatId,
			Character isItaxVerified, Character isPermitVerified,
			Character isExtraDocVerified, Set merchantWalletTransactionses) {
		this.merchWalletId = merchWalletId;
		this.merchants = merchants;
		this.merchWalletAccountNo = merchWalletAccountNo;
		this.merchWalletPin = merchWalletPin;
		this.merchWalletFromDate = merchWalletFromDate;
		this.merchWalletToDate = merchWalletToDate;
		this.merchWalletAmount = merchWalletAmount;
		this.merchPinLastChangedDate = merchPinLastChangedDate;
		this.merchWalletPic = merchWalletPic;
		this.merchIdProofType = merchIdProofType;
		this.merchIdProofNumber = merchIdProofNumber;
		this.merchIdProofPath = merchIdProofPath;
		this.merchAddressProofType = merchAddressProofType;
		this.merchAddressProofNumber = merchAddressProofNumber;
		this.merchAddressProofPath = merchAddressProofPath;
		this.isIdProofVerified = isIdProofVerified;
		this.isAddressProofVerified = isAddressProofVerified;
		this.isMerchKycComplete = isMerchKycComplete;
		this.isMerchWalletActive = isMerchWalletActive;
		this.merchPermitType = merchPermitType;
		this.merchPermitTypePath = merchPermitTypePath;
		this.itaxCertificatePath = itaxCertificatePath;
		this.extraDocsName = extraDocsName;
		this.extraDocsPath = extraDocsPath;
		this.merchBusinessLogo = merchBusinessLogo;
		this.merchantVatId = merchantVatId;
		this.isItaxVerified = isItaxVerified;
		this.isPermitVerified = isPermitVerified;
		this.isExtraDocVerified = isExtraDocVerified;
	
	}

	public long getMerchWalletId() {
		return this.merchWalletId;
	}

	public void setMerchWalletId(long merchWalletId) {
		this.merchWalletId = merchWalletId;
	}

	public Merchants getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchants merchants) {
		this.merchants = merchants;
	}

	public String getMerchWalletAccountNo() {
		return this.merchWalletAccountNo;
	}

	public void setMerchWalletAccountNo(String merchWalletAccountNo) {
		this.merchWalletAccountNo = merchWalletAccountNo;
	}

	public String getMerchWalletPin() {
		return this.merchWalletPin;
	}

	public void setMerchWalletPin(String merchWalletPin) {
		this.merchWalletPin = merchWalletPin;
	}

	public Timestamp getMerchWalletFromDate() {
		return this.merchWalletFromDate;
	}

	public void setMerchWalletFromDate(Timestamp merchWalletFromDate) {
		this.merchWalletFromDate = merchWalletFromDate;
	}

	public Timestamp getMerchWalletToDate() {
		return this.merchWalletToDate;
	}

	public void setMerchWalletToDate(Timestamp merchWalletToDate) {
		this.merchWalletToDate = merchWalletToDate;
	}

	public Double getMerchWalletAmount() {
		return this.merchWalletAmount;
	}

	public void setMerchWalletAmount(Double merchWalletAmount) {
		this.merchWalletAmount = merchWalletAmount;
	}

	public Timestamp getMerchPinLastChangedDate() {
		return this.merchPinLastChangedDate;
	}

	public void setMerchPinLastChangedDate(Timestamp merchPinLastChangedDate) {
		this.merchPinLastChangedDate = merchPinLastChangedDate;
	}

	public String getMerchWalletPic() {
		return this.merchWalletPic;
	}

	public void setMerchWalletPic(String merchWalletPic) {
		this.merchWalletPic = merchWalletPic;
	}

	public String getMerchIdProofType() {
		return this.merchIdProofType;
	}

	public void setMerchIdProofType(String merchIdProofType) {
		this.merchIdProofType = merchIdProofType;
	}

	public String getMerchIdProofNumber() {
		return this.merchIdProofNumber;
	}

	public void setMerchIdProofNumber(String merchIdProofNumber) {
		this.merchIdProofNumber = merchIdProofNumber;
	}

	public String getMerchIdProofPath() {
		return this.merchIdProofPath;
	}

	public void setMerchIdProofPath(String merchIdProofPath) {
		this.merchIdProofPath = merchIdProofPath;
	}

	public String getMerchAddressProofType() {
		return this.merchAddressProofType;
	}

	public void setMerchAddressProofType(String merchAddressProofType) {
		this.merchAddressProofType = merchAddressProofType;
	}

	public String getMerchAddressProofNumber() {
		return this.merchAddressProofNumber;
	}

	public void setMerchAddressProofNumber(String merchAddressProofNumber) {
		this.merchAddressProofNumber = merchAddressProofNumber;
	}

	public String getMerchAddressProofPath() {
		return this.merchAddressProofPath;
	}

	public void setMerchAddressProofPath(String merchAddressProofPath) {
		this.merchAddressProofPath = merchAddressProofPath;
	}

	public Character getIsIdProofVerified() {
		return this.isIdProofVerified;
	}

	public void setIsIdProofVerified(Character isIdProofVerified) {
		this.isIdProofVerified = isIdProofVerified;
	}

	public Character getIsAddressProofVerified() {
		return this.isAddressProofVerified;
	}

	public void setIsAddressProofVerified(Character isAddressProofVerified) {
		this.isAddressProofVerified = isAddressProofVerified;
	}

	public Character getIsMerchKycComplete() {
		return this.isMerchKycComplete;
	}

	public void setIsMerchKycComplete(Character isMerchKycComplete) {
		this.isMerchKycComplete = isMerchKycComplete;
	}

	public Character getIsMerchWalletActive() {
		return this.isMerchWalletActive;
	}

	public void setIsMerchWalletActive(Character isMerchWalletActive) {
		this.isMerchWalletActive = isMerchWalletActive;
	}

	public String getMerchPermitType() {
		return this.merchPermitType;
	}

	public void setMerchPermitType(String merchPermitType) {
		this.merchPermitType = merchPermitType;
	}

	public String getMerchPermitTypePath() {
		return this.merchPermitTypePath;
	}

	public void setMerchPermitTypePath(String merchPermitTypePath) {
		this.merchPermitTypePath = merchPermitTypePath;
	}

	public String getItaxCertificatePath() {
		return this.itaxCertificatePath;
	}

	public void setItaxCertificatePath(String itaxCertificatePath) {
		this.itaxCertificatePath = itaxCertificatePath;
	}

	public String getExtraDocsName() {
		return this.extraDocsName;
	}

	public void setExtraDocsName(String extraDocsName) {
		this.extraDocsName = extraDocsName;
	}

	public String getExtraDocsPath() {
		return this.extraDocsPath;
	}

	public void setExtraDocsPath(String extraDocsPath) {
		this.extraDocsPath = extraDocsPath;
	}

	public String getMerchBusinessLogo() {
		return this.merchBusinessLogo;
	}

	public void setMerchBusinessLogo(String merchBusinessLogo) {
		this.merchBusinessLogo = merchBusinessLogo;
	}

	public String getMerchantVatId() {
		return this.merchantVatId;
	}

	public void setMerchantVatId(String merchantVatId) {
		this.merchantVatId = merchantVatId;
	}

	public Character getIsItaxVerified() {
		return this.isItaxVerified;
	}

	public void setIsItaxVerified(Character isItaxVerified) {
		this.isItaxVerified = isItaxVerified;
	}

	public Character getIsPermitVerified() {
		return this.isPermitVerified;
	}

	public void setIsPermitVerified(Character isPermitVerified) {
		this.isPermitVerified = isPermitVerified;
	}

	public Character getIsExtraDocVerified() {
		return this.isExtraDocVerified;
	}

	public void setIsExtraDocVerified(Character isExtraDocVerified) {
		this.isExtraDocVerified = isExtraDocVerified;
	}

	
}
