package com.fidypay.entity;

// Generated Jul 2, 2015 11:22:57 AM by Hibernate Tools 4.0.0

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * MerchantSettlements generated by hbm2java
 */

@Entity
@Table(name = "MERCHANT_SETTLEMENTS")
@EntityListeners(AuditingEntityListener.class)
public class MerchantSettlements implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MERCHANT_SETTLEMENT_ID")
	private long merchantSettlementId;

	@ManyToOne
	@JoinColumn(name = "MERCHANT_ID")
	private Merchants merchants;

	@Column(name = "SETTLEMENT_DATE")
	private Timestamp settlementDate;

	@Column(name = "SETTLEMENT_DETAILS", length = 200)
	private String settlementDetails;

	@Column(name = "SETTLEMENT_IS_VERIFIED", length = 1)
	private Character settlementIsVerified;

	@Column(name = "SETTLEMENT_IS_AUTHORIZED", length = 1)
	private Character settlementIsAuthorized;

	@Column(name = "SETTLEMENT_REPORT_PASSWORD", length = 400)
	private String settlementReportPassword;

	@Column(name = "DATE_GENERATED")
	private Timestamp dateGenerated;

	@Column(name = "SETTLEMENT_FROM_DATE")
	private Timestamp settlementFromDate;

	@Column(name = "SETTLEMENT_TO_DATE")
	private Timestamp settlementToDate;

	@Column(name = "SETTLEMENT_GROSS_AMOUNT")
	private Double settlementGrossAmount;

	@Column(name = "SETTLEMENT_TAX")
	private Double settlementTax;

	@Column(name = "SETTLEMENT_NET_AMOUNT")
	private Double settlementNetAmount;

	@Column(name = "SETTLEMENT_TOTAL_AMOUNT")
	private Double settlementTotalAmount;

	@Column(name = "SETTLEMENT_TOTAL_TRXN")
	private int settlementTotalTrxn;

	@Column(name = "SETTLEMENT_CHARGE")
	private Double settlementCharge;

	@Column(name = "MERCHANT_VPA", length = 200)
	private String merchantVPA;

	@Column(name = "MERCHANT_BUSSINESS_NAME")
	private String merchantBussinessName;

	@Column(name = "SUB_MERCHANT_BUSSINESS_NAME")
	private String subMerchantBussinessName;

	@Column(name = "BANK_DETAILS", length = 400)
	private String bankDetails;

	@Column(name = "SETTLEMENT_TYPE", length = 200)
	private String settlementType;

	@Column(name = "SETTLEMENT_STATUS", length = 200)
	private String settlementStatus;

	@Column(name = "SELLER_IDENTIFIER")
	private String sellerIdentifier;

	@Column(name = "BANK_ID")
	private String bankId;

	@Column(name = "SETTLEMENT_UTR")
	private String settlementUTR;

	@Column(name = "PAYEE_MOBILE_NUMBER")
	private String payeeMobileNumber;

	@Column(name = "PAYEE_EMAIL")
	private String payeeEmail;

	public MerchantSettlements() {
	}

	public MerchantSettlements(long merchantSettlementId, Merchants merchants) {
		this.merchantSettlementId = merchantSettlementId;
		this.merchants = merchants;
	}

	public MerchantSettlements(long merchantSettlementId, Merchants merchants, Timestamp settlementDate,
			String settlementDetails, Character settlementIsVerified, Character settlementIsAuthorized,
			String settlementReportPassword, Timestamp dateGenerated, Timestamp settlementFromDate,
			Timestamp settlementToDate, Double settlementGrossAmount, Double settlementTax, Double settlementNetAmount,
			Double settlementTotalAmount, Double settlementCharge, String merchantVPA, String merchantBussinessName,
			String subMerchantBussinessName) {
		this.merchantSettlementId = merchantSettlementId;
		this.merchants = merchants;
		this.settlementDate = settlementDate;
		this.settlementDetails = settlementDetails;
		this.settlementIsVerified = settlementIsVerified;
		this.settlementIsAuthorized = settlementIsAuthorized;
		this.settlementReportPassword = settlementReportPassword;
		this.dateGenerated = dateGenerated;
		this.settlementFromDate = settlementFromDate;
		this.settlementToDate = settlementToDate;
		this.settlementGrossAmount = settlementGrossAmount;
		this.settlementTax = settlementTax;
		this.settlementNetAmount = settlementNetAmount;
		this.settlementTotalAmount = settlementTotalAmount;
		this.settlementCharge = settlementCharge;
		this.merchantVPA = merchantVPA;
		this.merchantBussinessName = merchantBussinessName;
		this.subMerchantBussinessName = subMerchantBussinessName;
	}

	public long getMerchantSettlementId() {
		return this.merchantSettlementId;
	}

	public void setMerchantSettlementId(long merchantSettlementId) {
		this.merchantSettlementId = merchantSettlementId;
	}

	public Merchants getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchants merchants) {
		this.merchants = merchants;
	}

	public Timestamp getSettlementDate() {
		return this.settlementDate;
	}

	public void setSettlementDate(Timestamp settlementDate) {
		this.settlementDate = settlementDate;
	}

	public String getSettlementDetails() {
		return this.settlementDetails;
	}

	public void setSettlementDetails(String settlementDetails) {
		this.settlementDetails = settlementDetails;
	}

	public Character getSettlementIsVerified() {
		return this.settlementIsVerified;
	}

	public void setSettlementIsVerified(Character settlementIsVerified) {
		this.settlementIsVerified = settlementIsVerified;
	}

	public Character getSettlementIsAuthorized() {
		return this.settlementIsAuthorized;
	}

	public void setSettlementIsAuthorized(Character settlementIsAuthorized) {
		this.settlementIsAuthorized = settlementIsAuthorized;
	}

	public String getSettlementReportPassword() {
		return this.settlementReportPassword;
	}

	public void setSettlementReportPassword(String settlementReportPassword) {
		this.settlementReportPassword = settlementReportPassword;
	}

	public Timestamp getDateGenerated() {
		return this.dateGenerated;
	}

	public void setDateGenerated(Timestamp dateGenerated) {
		this.dateGenerated = dateGenerated;
	}

	public Timestamp getSettlementFromDate() {
		return this.settlementFromDate;
	}

	public void setSettlementFromDate(Timestamp settlementFromDate) {
		this.settlementFromDate = settlementFromDate;
	}

	public Timestamp getSettlementToDate() {
		return this.settlementToDate;
	}

	public void setSettlementToDate(Timestamp settlementToDate) {
		this.settlementToDate = settlementToDate;
	}

	public Double getSettlementGrossAmount() {
		return this.settlementGrossAmount;
	}

	public void setSettlementGrossAmount(Double settlementGrossAmount) {
		this.settlementGrossAmount = settlementGrossAmount;
	}

	public Double getSettlementTax() {
		return this.settlementTax;
	}

	public void setSettlementTax(Double settlementTax) {
		this.settlementTax = settlementTax;
	}

	public Double getSettlementNetAmount() {
		return this.settlementNetAmount;
	}

	public void setSettlementNetAmount(Double settlementNetAmount) {
		this.settlementNetAmount = settlementNetAmount;
	}

	public Double getSettlementTotalAmount() {
		return this.settlementTotalAmount;
	}

	public void setSettlementTotalAmount(Double settlementTotalAmount) {
		this.settlementTotalAmount = settlementTotalAmount;
	}

	public int getSettlementTotalTrxn() {
		return settlementTotalTrxn;
	}

	public void setSettlementTotalTrxn(int settlementTotalTrxn) {
		this.settlementTotalTrxn = settlementTotalTrxn;
	}

	public Double getSettlementCharge() {
		return settlementCharge;
	}

	public void setSettlementCharge(Double settlementCharge) {
		this.settlementCharge = settlementCharge;
	}

	public String getMerchantVPA() {
		return merchantVPA;
	}

	public void setMerchantVPA(String merchantVPA) {
		this.merchantVPA = merchantVPA;
	}

	public String getMerchantBussinessName() {
		return merchantBussinessName;
	}

	public void setMerchantBussinessName(String merchantBussinessName) {
		this.merchantBussinessName = merchantBussinessName;
	}

	public String getSubMerchantBussinessName() {
		return subMerchantBussinessName;
	}

	public void setSubMerchantBussinessName(String subMerchantBussinessName) {
		this.subMerchantBussinessName = subMerchantBussinessName;
	}

	public String getBankDetails() {
		return bankDetails;
	}

	public void setBankDetails(String bankDetails) {
		this.bankDetails = bankDetails;
	}

	public String getSettlementType() {
		return settlementType;
	}

	public void setSettlementType(String settlementType) {
		this.settlementType = settlementType;
	}

	public String getSettlementStatus() {
		return settlementStatus;
	}

	public void setSettlementStatus(String settlementStatus) {
		this.settlementStatus = settlementStatus;
	}

	public String getSellerIdentifier() {
		return sellerIdentifier;
	}

	public void setSellerIdentifier(String sellerIdentifier) {
		this.sellerIdentifier = sellerIdentifier;
	}

	public String getBankId() {
		return bankId;
	}

	public void setBankId(String bankId) {
		this.bankId = bankId;
	}

	public String getSettlementUTR() {
		return settlementUTR;
	}

	public void setSettlementUTR(String settlementUTR) {
		this.settlementUTR = settlementUTR;
	}

	public String getPayeeMobileNumber() {
		return payeeMobileNumber;
	}

	public void setPayeeMobileNumber(String payeeMobileNumber) {
		this.payeeMobileNumber = payeeMobileNumber;
	}

	public String getPayeeEmail() {
		return payeeEmail;
	}

	public void setPayeeEmail(String payeeEmail) {
		this.payeeEmail = payeeEmail;
	}

}
