package com.fidypay.entity;

// Generated Sep 23, 2015 6:40:35 PM by Hibernate Tools 4.0.0

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * MerchantWalletTransactions generated by hbm2java
 */

@Entity
@Table(name = "MERCHANT_WALLET_TRANSACTIONS")
@EntityListeners(AuditingEntityListener.class)
public class MerchantWalletTransactions implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MERCHANT_WALLET_TRXN_ID")
	private long merchantWalletTrxnId;

	@ManyToOne
	@JoinColumn(name = "MERCHANT_ID")
	private Merchants merchants;

	@Column(name = "TRANSACTION_ID")
	private long coreTransactions;

	@Column(name = "IS_REVERTED", nullable = false, length = 1)
	private Character isReverted;

	@Column(name = "MERC_WALLET_PREVIOUS_BALANCE", nullable = false)
	private Double mercWalletPreviousBalance;

	@Column(name = "WALLET_TRXN_TYPE", nullable = false, length = 100)
	private String walletTrxnType;

	@Column(name = "MERC_WALLET_NEW_BALANCE", nullable = false)
	private Double mercWalletNewBalance;

	@Column(name = "DESCRIPTION", nullable = false, length = 200)
	private String description;

	@Column(name = "WALLET_TXN_REF_NO", nullable = false, length = 200)
	private String walletTxnRefNo;

	@Column(name = "WALLET_TXN_DATE", nullable = false)
	private Timestamp walletTxnDate;

	@Column(name = "SERVICE_NAME", length = 200)
	private String serviceName;

	@Column(name = "TRXN_REF_ID", length = 200)
	private String trxnRefId;

	@Column(name = "MERCHANT_TRXN_REF_ID", length = 200)
	private String merchantTrxnRefId;

	public MerchantWalletTransactions() {
	}

	public MerchantWalletTransactions(long merchantWalletTrxnId, long coreTransactions, Character isReverted,
			Double mercWalletPreviousBalance, String walletTrxnType, Double mercWalletNewBalance, String description,
			String walletTxnRefNo, Timestamp walletTxnDate, Merchants merchants) {
		this.merchantWalletTrxnId = merchantWalletTrxnId;
		this.coreTransactions = coreTransactions;
		this.isReverted = isReverted;
		this.mercWalletPreviousBalance = mercWalletPreviousBalance;
		this.walletTrxnType = walletTrxnType;
		this.mercWalletNewBalance = mercWalletNewBalance;
		this.description = description;
		this.walletTxnRefNo = walletTxnRefNo;
		this.walletTxnDate = walletTxnDate;
		this.merchants = merchants;
	}

	public long getMerchantWalletTrxnId() {
		return merchantWalletTrxnId;
	}

	public void setMerchantWalletTrxnId(long merchantWalletTrxnId) {
		this.merchantWalletTrxnId = merchantWalletTrxnId;
	}

	public long getCoreTransactions() {
		return coreTransactions;
	}

	public void setCoreTransactions(long coreTransactions) {
		this.coreTransactions = coreTransactions;
	}

	public Character getIsReverted() {
		return isReverted;
	}

	public void setIsReverted(Character isReverted) {
		this.isReverted = isReverted;
	}

	public Double getMercWalletPreviousBalance() {
		return mercWalletPreviousBalance;
	}

	public void setMercWalletPreviousBalance(Double mercWalletPreviousBalance) {
		this.mercWalletPreviousBalance = mercWalletPreviousBalance;
	}

	public String getWalletTrxnType() {
		return walletTrxnType;
	}

	public void setWalletTrxnType(String walletTrxnType) {
		this.walletTrxnType = walletTrxnType;
	}

	public Double getMercWalletNewBalance() {
		return mercWalletNewBalance;
	}

	public void setMercWalletNewBalance(Double mercWalletNewBalance) {
		this.mercWalletNewBalance = mercWalletNewBalance;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getWalletTxnRefNo() {
		return walletTxnRefNo;
	}

	public void setWalletTxnRefNo(String walletTxnRefNo) {
		this.walletTxnRefNo = walletTxnRefNo;
	}

	public Timestamp getWalletTxnDate() {
		return walletTxnDate;
	}

	public void setWalletTxnDate(Timestamp walletTxnDate) {
		this.walletTxnDate = walletTxnDate;
	}

	public Merchants getMerchants() {
		return merchants;
	}

	public void setMerchants(Merchants merchants) {
		this.merchants = merchants;
	}

	public String getServiceName() {
		return serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public String getTrxnRefId() {
		return trxnRefId;
	}

	public void setTrxnRefId(String trxnRefId) {
		this.trxnRefId = trxnRefId;
	}

	public String getMerchantTrxnRefId() {
		return merchantTrxnRefId;
	}

	public void setMerchantTrxnRefId(String merchantTrxnRefId) {
		this.merchantTrxnRefId = merchantTrxnRefId;
	}

}