package com.fidypay.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

// Generated Apr 18, 2015 4:15:37 PM by Hibernate Tools 4.0.0

/**
 * MerchantPaymentChannels generated by hbm2java
 */

@Entity
//@Table(name = "MERCHANT_PAYMENT_CHANNELS")
@EntityListeners(AuditingEntityListener.class)
@Table(name = "MERCHANT_PAYMENT_CHANNELS", indexes = {
		@Index(name = "index_MERCHANT_PC_ID", columnList = "MERCHANT_PC_ID"),
		@Index(name = "index_PC_OPTION_ID", columnList = "PC_OPTION_ID"),
		@Index(name = "index_MERCHANT_ID", columnList = "MERCHANT_ID")
		})
public class MerchantPaymentChannels implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MERCHANT_PC_ID")
	private long merchantPcId;
	
	
	
	@ManyToOne
    @JoinColumn(name = "PC_OPTION_ID")
    private PaymentChannelOptions paymentChannelOptions;
	
	
	
	@ManyToOne
    @JoinColumn(name = "MERCHANT_ID")
   private Merchants merchants;

	public MerchantPaymentChannels() {
	}

	public MerchantPaymentChannels(long merchantPcId,
			PaymentChannelOptions paymentChannelOptions, Merchants merchants) {
		this.merchantPcId = merchantPcId;
		this.paymentChannelOptions = paymentChannelOptions;
		this.merchants = merchants;
	}

	public long getMerchantPcId() {
		return this.merchantPcId;
	}

	public void setMerchantPcId(long merchantPcId) {
		this.merchantPcId = merchantPcId;
	}

	public PaymentChannelOptions getPaymentChannelOptions() {
		return this.paymentChannelOptions;
	}

	public void setPaymentChannelOptions(
			PaymentChannelOptions paymentChannelOptions) {
		this.paymentChannelOptions = paymentChannelOptions;
	}

	public Merchants getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchants merchants) {
		this.merchants = merchants;
	}

}
