package com.fidypay.entity;

// Generated Apr 18, 2015 4:15:37 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * MerchantOutletTills generated by hbm2java
 */

@Entity
//@Table(name = "MERCHANT_OUTLET_TILLS")
@EntityListeners(AuditingEntityListener.class)
@Table(name = "MERCHANT_OUTLET_TILLS", indexes = {
		@Index(name = "index_MERCHANT_OUTLET_TILL_ID", columnList = "MERCHANT_OUTLET_TILL_ID"),
		@Index(name = "index_MERCHANT_TILL_ID", columnList = "MERCHANT_TILL_ID"),
		@Index(name = "index_MERCHANT_OUTLET_ID", columnList = "MERCHANT_OUTLET_ID"),
		@Index(name = "index_OUTLET_TILL_IS_ACTIVE", columnList = "OUTLET_TILL_IS_ACTIVE")
		})
public class MerchantOutletTills implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MERCHANT_OUTLET_TILL_ID")
	private long merchantOutletTillId;
	
	
	@ManyToOne
    @JoinColumn(name = "MERCHANT_TILL_ID")
    private MerchantTills merchantTills;
	
	
	@ManyToOne
    @JoinColumn(name = "MERCHANT_OUTLET_ID")
    private MerchantOutlets merchantOutlets;
	
	@Column(name="OUTLET_TILL_IS_ACTIVE", length=1)
	private Character outletTillIsActive;
	
	   
    @OneToMany(mappedBy = "merchantOutletTills", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantTransactions> merchantTransactionses = new HashSet<MerchantTransactions>(0);
	
	public MerchantOutletTills() {
	}

	public MerchantOutletTills(long merchantOutletTillId,
			MerchantTills merchantTills, MerchantOutlets merchantOutlets, Character outletTillIsActive) {
		this.merchantOutletTillId = merchantOutletTillId;
		this.merchantTills = merchantTills;
		this.merchantOutlets = merchantOutlets;
		this.outletTillIsActive=outletTillIsActive;
	}

	public MerchantOutletTills(long merchantOutletTillId,
			MerchantTills merchantTills, MerchantOutlets merchantOutlets,
			Set<MerchantTransactions> merchantTransactionses,  Character outletTillIsActive) {
		this.merchantOutletTillId = merchantOutletTillId;
		this.merchantTills = merchantTills;
		this.merchantOutlets = merchantOutlets;
		this.outletTillIsActive=outletTillIsActive;
		this.merchantTransactionses = merchantTransactionses;
	}

	public long getMerchantOutletTillId() {
		return this.merchantOutletTillId;
	}

	public void setMerchantOutletTillId(long merchantOutletTillId) {
		this.merchantOutletTillId = merchantOutletTillId;
	}

	public MerchantTills getMerchantTills() {
		return this.merchantTills;
	}

	public void setMerchantTills(MerchantTills merchantTills) {
		this.merchantTills = merchantTills;
	}

	public MerchantOutlets getMerchantOutlets() {
		return this.merchantOutlets;
	}

	public void setMerchantOutlets(MerchantOutlets merchantOutlets) {
		this.merchantOutlets = merchantOutlets;
	}
	

	public Character getOutletTillIsActive() {
		return outletTillIsActive;
	}

	public void setOutletTillIsActive(Character outletTillIsActive) {
		this.outletTillIsActive = outletTillIsActive;
	}

	public Set getMerchantTransactionses() {
		return this.merchantTransactionses;
	}

	public void setMerchantTransactionses(Set merchantTransactionses) {
		this.merchantTransactionses = merchantTransactionses;
	}

}
