package com.fidypay.entity;

// Generated May 30, 2015 1:02:11 PM by Hibernate Tools 4.0.0

import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * PaymentChannelRefund generated by hbm2java
 */

@Entity
//@Table(name = "PAYMENT_CHANNEL_REFUND")
@EntityListeners(AuditingEntityListener.class)
@Table(name = "PAYMENT_CHANNEL_REFUND", indexes = {
		@Index(name = "index_PC_REFUND_ID", columnList = "PC_REFUND_ID"),
		@Index(name = "index_PC_TRANSACTION_ID", columnList = "PC_TRANSACTION_ID"),
		@Index(name = "index_PC_REFUND_REF_ID", columnList = "PC_REFUND_REF_ID"),
		@Index(name = "index_PC_REFUND_TRXN_REF_ID", columnList = "PC_REFUND_TRXN_REF_ID"),
		@Index(name = "index_PC_REFUND_STATUS", columnList = "PC_REFUND_STATUS"),
		@Index(name = "index_PC_REFUND_MESSAGE", columnList = "PC_REFUND_MESSAGE"),
		@Index(name = "index_PC_REFUND_AMOUNT", columnList = "PC_REFUND_AMOUNT"),
		@Index(name = "index_PC_REFUND_DATE", columnList = "PC_REFUND_DATE"),
		@Index(name = "index_PC_REFUND_BANK_REF_ID", columnList = "PC_REFUND_BANK_REF_ID")
		})
public class PaymentChannelRefund implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "PC_REFUND_ID")
	private long pcRefundId;
	
	@ManyToOne
    @JoinColumn(name = "PC_TRANSACTION_ID")
    private PaymentChannelTransactions paymentChannelTransactions;
	
	@Column(name="PC_REFUND_REF_ID", length = 20)
	private String pcRefundRefId;
	
	@Column(name="PC_REFUND_TRXN_REF_ID", length = 100)
	private String pcRefundTrxnRefId;
	
	@Column(name="PC_REFUND_STATUS", length = 20)
	private String pcRefundStatus;
	
	@Column(name="PC_REFUND_MESSAGE", length = 200)
	private String pcRefundMessage;
	
	@Column(name="PC_REFUND_AMOUNT")
	private Double pcRefundAmount;
	
	@Column(name="PC_REFUND_DATE", length = 7)
	private Timestamp pcRefundDate;
	
	@Column(name="PC_REFUND_BANK_REF_ID", length = 20)
	private String pcRefundBankRefId;

	public PaymentChannelRefund() {
	}

	public PaymentChannelRefund(long pcRefundId,
			PaymentChannelTransactions paymentChannelTransactions) {
		this.pcRefundId = pcRefundId;
		this.paymentChannelTransactions = paymentChannelTransactions;
	}

	public PaymentChannelRefund(long pcRefundId,
			PaymentChannelTransactions paymentChannelTransactions,
			String pcRefundRefId, String pcRefundTrxnRefId,
			String pcRefundStatus, String pcRefundMessage,
			Double pcRefundAmount, Timestamp pcRefundDate, String pcRefundBankRefId) {
		this.pcRefundId = pcRefundId;
		this.paymentChannelTransactions = paymentChannelTransactions;
		this.pcRefundRefId = pcRefundRefId;
		this.pcRefundTrxnRefId = pcRefundTrxnRefId;
		this.pcRefundStatus = pcRefundStatus;
		this.pcRefundMessage = pcRefundMessage;
		this.pcRefundAmount = pcRefundAmount;
		this.pcRefundDate = pcRefundDate;
		this.pcRefundBankRefId = pcRefundBankRefId;
	}

	public long getPcRefundId() {
		return this.pcRefundId;
	}

	public void setPcRefundId(long pcRefundId) {
		this.pcRefundId = pcRefundId;
	}

	public PaymentChannelTransactions getPaymentChannelTransactions() {
		return this.paymentChannelTransactions;
	}

	public void setPaymentChannelTransactions(
			PaymentChannelTransactions paymentChannelTransactions) {
		this.paymentChannelTransactions = paymentChannelTransactions;
	}

	public String getPcRefundRefId() {
		return this.pcRefundRefId;
	}

	public void setPcRefundRefId(String pcRefundRefId) {
		this.pcRefundRefId = pcRefundRefId;
	}

	public String getPcRefundTrxnRefId() {
		return this.pcRefundTrxnRefId;
	}

	public void setPcRefundTrxnRefId(String pcRefundTrxnRefId) {
		this.pcRefundTrxnRefId = pcRefundTrxnRefId;
	}

	public String getPcRefundStatus() {
		return this.pcRefundStatus;
	}

	public void setPcRefundStatus(String pcRefundStatus) {
		this.pcRefundStatus = pcRefundStatus;
	}

	public String getPcRefundMessage() {
		return this.pcRefundMessage;
	}

	public void setPcRefundMessage(String pcRefundMessage) {
		this.pcRefundMessage = pcRefundMessage;
	}

	public Double getPcRefundAmount() {
		return this.pcRefundAmount;
	}

	public void setPcRefundAmount(Double pcRefundAmount) {
		this.pcRefundAmount = pcRefundAmount;
	}

	public Date getPcRefundDate() {
		return this.pcRefundDate;
	}

	public void setPcRefundDate(Timestamp pcRefundDate) {
		this.pcRefundDate = pcRefundDate;
	}

	public String getPcRefundBankRefId() {
		return this.pcRefundBankRefId;
	}

	public void setPcRefundBankRefId(String pcRefundBankRefId) {
		this.pcRefundBankRefId = pcRefundBankRefId;
	}

}
