package com.fidypay.entity;

// Generated Apr 18, 2015 4:15:37 PM by Hibernate Tools 4.0.0

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * PosDevices generated by hbm2java
 */

@Entity
//@Table(name = "POS_DEVICES")
@EntityListeners(AuditingEntityListener.class)
@Table(name = "POS_DEVICES", indexes = {
		@Index(name = "index_POS_ID", columnList = "POS_ID"),
		@Index(name = "index_MERCHANT_ID", columnList = "MERCHANT_ID"),
		@Index(name = "index_POS_SERIAL_NO", columnList = "POS_SERIAL_NO"),
		@Index(name = "index_POS_ASSIGN_DATE", columnList = "POS_ASSIGN_DATE"),
		@Index(name = "index_POS_DETAILS", columnList = "POS_DETAILS"),
		@Index(name = "index_POS_MAKE", columnList = "POS_MAKE"),
		@Index(name = "index_POS_SOFTWARE_VER", columnList = "POS_SOFTWARE_VER"),
		@Index(name = "index_POS_IS_ACTIVE", columnList = "POS_IS_ACTIVE"),
		@Index(name = "index_IS_POS_ASSIGNED", columnList = "IS_POS_ASSIGNED"),
		@Index(name = "index_IS_MOBILE", columnList = "IS_MOBILE"),
		})
public class PosDevices implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "POS_ID")
	private long posId;
	
	 @ManyToOne
	 @JoinColumn(name = "MERCHANT_ID")
     private Merchants merchants;
	
	@Column(name="POS_SERIAL_NO", nullable = false, length = 200)
	private String posSerialNo;
	
	@Column(name="POS_ASSIGN_DATE")
	private Timestamp posAssignDate;
	
	@Column(name="POS_DETAILS", length = 200)
	private String posDetails;
	
	@Column(name="POS_MAKE", nullable = false, length = 200)
	private String posMake;
	
	@Column(name="POS_SOFTWARE_VER", nullable = false, length = 200)
	private String posSoftwareVer;
	
	@Column(name="POS_IS_ACTIVE", length = 1)
	private Character posIsActive;
	
	@Column(name="IS_POS_ASSIGNED", length = 1)
	private Character isPosAssigned;
	
	@Column(name="IS_MOBILE", length = 1)
	private Character isMobile;
	
		
	@OneToMany(mappedBy = "posDevices", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantTransactions> merchantTransactionses = new HashSet<MerchantTransactions>(0);
	
	@OneToMany(mappedBy = "posDevices", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MerchantTillPosAssignment> merchantTillPosAssignments = new HashSet<MerchantTillPosAssignment>(0);

	public PosDevices() {
	}

	public PosDevices(long posId, String posSerialNo, String posMake,
			String posSoftwareVer) {
		this.posId = posId;
		this.posSerialNo = posSerialNo;
		this.posMake = posMake;
		this.posSoftwareVer = posSoftwareVer;
	}

	public PosDevices(long posId, Merchants merchants, String posSerialNo,
			Timestamp posAssignDate, String posDetails, String posMake,
			String posSoftwareVer, Character posIsActive,
			Character isPosAssigned, Character isMobile,
			Set merchantTransactionses, Set merchantTillPosAssignments) {

		this.posId = posId;
		this.merchants = merchants;
		this.posSerialNo = posSerialNo;
		this.posAssignDate = posAssignDate;
		this.posDetails = posDetails;
		this.posMake = posMake;
		this.posSoftwareVer = posSoftwareVer;
		this.posIsActive = posIsActive;
		this.isPosAssigned = isPosAssigned;
		this.merchantTransactionses = merchantTransactionses;
		this.merchantTillPosAssignments = merchantTillPosAssignments;
		this.isMobile = isMobile;
	}

	public long getPosId() {
		return this.posId;
	}

	public void setPosId(long posId) {
		this.posId = posId;
	}

	public Merchants getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchants merchants) {
		this.merchants = merchants;
	}

	public String getPosSerialNo() {
		return this.posSerialNo;
	}

	public void setPosSerialNo(String posSerialNo) {
		this.posSerialNo = posSerialNo;
	}

	public Timestamp getPosAssignDate() {
		return this.posAssignDate;
	}

	public void setPosAssignDate(Timestamp posAssignDate) {
		this.posAssignDate = posAssignDate;
	}

	public String getPosDetails() {
		return this.posDetails;
	}

	public void setPosDetails(String posDetails) {
		this.posDetails = posDetails;
	}

	public String getPosMake() {
		return this.posMake;
	}

	public void setPosMake(String posMake) {
		this.posMake = posMake;
	}

	public String getPosSoftwareVer() {
		return this.posSoftwareVer;
	}

	public void setPosSoftwareVer(String posSoftwareVer) {
		this.posSoftwareVer = posSoftwareVer;
	}

	public Character getPosIsActive() {
		return this.posIsActive;
	}

	public void setPosIsActive(Character posIsActive) {
		this.posIsActive = posIsActive;
	}

	public Character getIsPosAssigned() {
		return this.isPosAssigned;
	}

	public void setIsPosAssigned(Character isPosAssigned) {
		this.isPosAssigned = isPosAssigned;
	}

	public Set getMerchantTransactionses() {
		return this.merchantTransactionses;
	}

	public void setMerchantTransactionses(Set merchantTransactionses) {
		this.merchantTransactionses = merchantTransactionses;
	}

	public Set getMerchantTillPosAssignments() {
		return this.merchantTillPosAssignments;
	}

	public void setMerchantTillPosAssignments(Set merchantTillPosAssignments) {
		this.merchantTillPosAssignments = merchantTillPosAssignments;
	}

	public Character getIsMobile() {
		return isMobile;
	}

	public void setIsMobile(Character isMobile) {
		this.isMobile = isMobile;
	}

}
