package com.fidypay.entity;

// Generated Apr 22, 2015 5:10:44 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * SecurityQuestions generated by hbm2java
 */

@Entity
//@Table(name = "SECURITY_QUESTIONS")
@EntityListeners(AuditingEntityListener.class)
@Table(name = "SECURITY_QUESTIONS", indexes = {
		@Index(name = "index_SEC_QUESTION_ID", columnList = "SEC_QUESTION_ID"),
		@Index(name = "index_SEC_QUESTION", columnList = "SEC_QUESTION")
		})
public class SecurityQuestions implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "SEC_QUESTION_ID")
	private long secQuestionId;
	
	@Column(name="SEC_QUESTION", length = 200)
	private String secQuestion;
	
	 
	 @OneToMany(mappedBy = "securityQuestions", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<Customers> customerses = new HashSet<Customers>(0);
	 
	 
	 @OneToMany(mappedBy = "securityQuestions", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<Merchants> merchantses = new HashSet<Merchants>(0);

	public SecurityQuestions() {
	}

	public SecurityQuestions(long secQuestionId) {
		this.secQuestionId = secQuestionId;
	}

	public SecurityQuestions(long secQuestionId, String secQuestion,
			Set customerses, Set merchantses) {
		this.secQuestionId = secQuestionId;
		this.secQuestion = secQuestion;
		this.customerses = customerses;
		this.merchantses = merchantses;
	}

	public long getSecQuestionId() {
		return this.secQuestionId;
	}

	public void setSecQuestionId(long secQuestionId) {
		this.secQuestionId = secQuestionId;
	}

	public String getSecQuestion() {
		return this.secQuestion;
	}

	public void setSecQuestion(String secQuestion) {
		this.secQuestion = secQuestion;
	}

	public Set getCustomerses() {
		return this.customerses;
	}

	public void setCustomerses(Set customerses) {
		this.customerses = customerses;
	}

	public Set getMerchantses() {
		return this.merchantses;
	}

	public void setMerchantses(Set merchantses) {
		this.merchantses = merchantses;
	}

}
