package com.fidypay.entity;

// Generated May 27, 2015 3:40:33 PM by Hibernate Tools 4.0.0


import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * MerchantTillFloatManage generated by hbm2java
 */
@Entity
//@Table(name = "SERVICE_PROVIDER_FLOAT_MANAGE")
@EntityListeners(AuditingEntityListener.class)
@Table(name = "SERVICE_PROVIDER_FLOAT_MANAGE", indexes = {
		@Index(name = "index_SERVICE_PROVIDER_FLOAT_MNG_ID", columnList = "SERVICE_PROVIDER_FLOAT_MNG_ID"),
		@Index(name = "index_SERVICE_PROVIDER_ID", columnList = "SERVICE_PROVIDER_ID"),
		@Index(name = "index_FLOAT_AMOUNT", columnList = "FLOAT_AMOUNT"),
		@Index(name = "index_PAY_MODE", columnList = "PAY_MODE"),
		@Index(name = "index_COMMENTS", columnList = "COMMENTS"),
		@Index(name = "index_MNG_DATE", columnList = "MNG_DATE")
		})
public class ServiceProviderFloatManage implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "SERVICE_PROVIDER_FLOAT_MNG_ID")
	private long serviceProviderFloatMngId;

	
	@ManyToOne
    @JoinColumn(name = "SERVICE_PROVIDER_ID", nullable = false)
    private ServiceProviders serviceProviders;
	
	@Column(name="FLOAT_AMOUNT")
	private double floatAmount;
	
	@Column(name="PAY_MODE", length = 100)
	private String payMode;
	
	@Column(name="COMMENTS", length = 200)
	private String comments;
	
	@Column(name="MNG_DATE")
	private Timestamp mngDate;

	public ServiceProviderFloatManage() {
	}

	public ServiceProviderFloatManage(long serviceProviderFloatMngId,
			ServiceProviders serviceProviders) {
		this.serviceProviderFloatMngId = serviceProviderFloatMngId;
		this.serviceProviders = serviceProviders;
	}

	public ServiceProviderFloatManage(long serviceProviderFloatMngId,
			ServiceProviders serviceProviders, double floatAmount,
			String payMode, String comments, Timestamp mngDate) {
		this.serviceProviderFloatMngId = serviceProviderFloatMngId;
		this.serviceProviders = serviceProviders;
		this.floatAmount = floatAmount;
		this.payMode = payMode;
		this.comments = comments;
		this.mngDate = mngDate;
	}




	public long getServiceProviderFloatMngId() {
		return serviceProviderFloatMngId;
	}

	public void setServiceProviderFloatMngId(long serviceProviderFloatMngId) {
		this.serviceProviderFloatMngId = serviceProviderFloatMngId;
	}

	public ServiceProviders getServiceProviders() {
		return serviceProviders;
	}

	public void setServiceProviders(ServiceProviders serviceProviders) {
		this.serviceProviders = serviceProviders;
	}

	public double getFloatAmount() {
		return this.floatAmount;
	}

	public void setFloatAmount(double floatAmount) {
		this.floatAmount = floatAmount;
	}

	public String getPayMode() {
		return this.payMode;
	}

	public void setPayMode(String payMode) {
		this.payMode = payMode;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Timestamp getMngDate() {
		return this.mngDate;
	}

	public void setMngDate(Timestamp mngDate) {
		this.mngDate = mngDate;
	}

}
