package com.fidypay.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

// Generated Apr 18, 2015 4:15:37 PM by Hibernate Tools 4.0.0

/**
 * ServiceProviderTransactions generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_PROVIDER_TRANSACTIONS")
@EntityListeners(AuditingEntityListener.class)
public class ServiceProviderTransactions implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "SP_TRANSACTION_ID")
	private long spTransactionId;
	
		
	 @ManyToOne
	 @JoinColumn(name = "TRANSACTION_ID")
     private CoreTransactions coreTransactions;
	
	 
	 @ManyToOne
	 @JoinColumn(name = "SERVICE_PROVIDER_ID")
    private ServiceProviders serviceProviders;
	
	@Column(name="SP_REFERENCE_ID", length = 200)
	private String spReferenceId;
	
	@Column(name="OPERATOR_REF_NO", length = 200)
	private String operatorRefNo;
	
	@Column(name="RESPONSE_MESSAGE", length = 500)
	private String responseMessage;
	
	@Column(name="COMMISSION_AMOUNT")
	private Double commissionAmount;
	
	@Column(name="SP_AMOUNT")
	private Double spAmount;
	
	@Column(name="USER_IDNUMBER", length = 200)	
	private String userIdnumber;
	
	
	@Column(name="IS_SETTLED", nullable = false)
	private Character isSettled;

	@Column(name="IS_RECONCILE", nullable = false)
	private Character isReconcile;

	public ServiceProviderTransactions() {
	}

	public ServiceProviderTransactions(long spTransactionId) {
		this.spTransactionId = spTransactionId;
	}

	public ServiceProviderTransactions(long spTransactionId,
			CoreTransactions coreTransactions,
			ServiceProviders serviceProviders, String spReferenceId,
			String operatorRefNo, String responseMessage, Double commissionAmount, Double spAmount,String userIdnumber) {
		this.spTransactionId = spTransactionId;
		this.coreTransactions = coreTransactions;
		this.serviceProviders = serviceProviders;
		this.spReferenceId = spReferenceId;
		this.operatorRefNo = operatorRefNo;
		this.responseMessage = responseMessage;
		this.commissionAmount=commissionAmount;
		this.spAmount = spAmount;
		this.userIdnumber = userIdnumber;
	}

	public long getSpTransactionId() {
		return this.spTransactionId;
	}

	public void setSpTransactionId(long spTransactionId) {
		this.spTransactionId = spTransactionId;
	}

	public CoreTransactions getCoreTransactions() {
		return this.coreTransactions;
	}

	public void setCoreTransactions(CoreTransactions coreTransactions) {
		this.coreTransactions = coreTransactions;
	}

	public ServiceProviders getServiceProviders() {
		return this.serviceProviders;
	}

	public void setServiceProviders(ServiceProviders serviceProviders) {
		this.serviceProviders = serviceProviders;
	}

	public String getSpReferenceId() {
		return this.spReferenceId;
	}

	public void setSpReferenceId(String spReferenceId) {
		this.spReferenceId = spReferenceId;
	}

	public String getOperatorRefNo() {
		return this.operatorRefNo;
	}

	public void setOperatorRefNo(String operatorRefNo) {
		this.operatorRefNo = operatorRefNo;
	}

	public String getResponseMessage() {
		return this.responseMessage;
	}

	public void setResponseMessage(String responseMessage) {
		this.responseMessage = responseMessage;
	}

	public Double getCommissionAmount() {
		return commissionAmount;
	}

	public void setCommissionAmount(Double commissionAmount) {
		this.commissionAmount = commissionAmount;
	}

	public Double getSpAmount() {
		return spAmount;
	}

	public void setSpAmount(Double spAmount) {
		this.spAmount = spAmount;
	}

	public String getUserIdnumber() {
		return userIdnumber;
	}

	public void setUserIdnumber(String userIdnumber) {
		this.userIdnumber = userIdnumber;
	}

	public Character getIsSettled() {
		return isSettled;
	}

	public void setIsSettled(Character isSettled) {
		this.isSettled = isSettled;
	}

	public Character getIsReconcile() {
		return isReconcile;
	}

	public void setIsReconcile(Character isReconcile) {
		this.isReconcile = isReconcile;
	}
	
	
	
}
