package com.fidypay.entity;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

// Generated Jun 30, 2015 7:57:33 PM by Hibernate Tools 4.0.0



/**
 * SettlementInfo generated by hbm2java
 */
@Entity
//@Table(name = "SETTLEMENT_INFO")
@EntityListeners(AuditingEntityListener.class)
@Table(name = "SETTLEMENT_INFO", indexes = {
		@Index(name = "index_SETTLEMENT_ID", columnList = "SETTLEMENT_ID"),
		@Index(name = "index_SETTLEMENT_REF_ID", columnList = "SETTLEMENT_REF_ID"),
		@Index(name = "index_SETTLEMENT_DATE", columnList = "SETTLEMENT_DATE"),
		@Index(name = "index_SETTLEMENT_AMOUNT", columnList = "SETTLEMENT_AMOUNT"),
		@Index(name = "index_SETTLEMENT_DETAILS", columnList = "SETTLEMENT_DETAILS"),
		@Index(name = "index_SETTLEMENT_REPORT_URL", columnList = "SETTLEMENT_REPORT_URL"),
		@Index(name = "index_SETTLEMENT_IS_VERIFIED", columnList = "SETTLEMENT_IS_VERIFIED"),
		@Index(name = "index_SETTLEMENT_IS_AUTHORIZED", columnList = "SETTLEMENT_IS_AUTHORIZED"),
		@Index(name = "index_SETTLEMENT_REPORT_PASSWORD", columnList = "SETTLEMENT_REPORT_PASSWORD"),
		@Index(name = "index_DATE_GENERATED", columnList = "DATE_GENERATED"),
		@Index(name = "index_SETTLEMENT_FROM_DATE", columnList = "SETTLEMENT_FROM_DATE"),
		@Index(name = "index_SETTLEMENT_TO_DATE", columnList = "SETTLEMENT_TO_DATE")
		})
public class SettlementInfo implements java.io.Serializable {
  
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "SETTLEMENT_ID")
    private long settlementId;
	
	@Column(name="SETTLEMENT_REF_ID", length = 200)
	private String settlementRefId;
	
	@Column(name="SETTLEMENT_DATE")
	private Timestamp settlementDate;
	
	@Column(name="SETTLEMENT_AMOUNT")
	private Double settlementAmount;
	
	@Column(name="SETTLEMENT_DETAILS", length = 200)
	private String settlementDetails;
	
	@Column(name="SETTLEMENT_REPORT_URL", length = 400)
	private String settlementReportUrl;
	
	@Column(name="SETTLEMENT_IS_VERIFIED", length = 1)
	private Character settlementIsVerified;
	
	@Column(name="SETTLEMENT_IS_AUTHORIZED", length = 2)
	private Character settlementIsAuthorized;
	
	@Column(name="SETTLEMENT_REPORT_PASSWORD", length = 400)
	private String settlementReportPassword;
	
	@Column(name="DATE_GENERATED")
	private Timestamp dateGenerated;
	
	@Column(name="SETTLEMENT_FROM_DATE")
	private Timestamp settlementFromDate;
	
	@Column(name="SETTLEMENT_TO_DATE")
	private Timestamp settlementToDate;

	public SettlementInfo() {
	}

	public SettlementInfo(long settlementId, String settlementRefId) {
		this.settlementId = settlementId;
		this.settlementRefId = settlementRefId;
	}

	public SettlementInfo(long settlementId, String settlementRefId,
			Timestamp settlementDate, Double settlementAmount,
			String settlementDetails, String settlementReportUrl,
			Character settlementIsVerified, Character settlementIsAuthorized,
			String settlementReportPassword, Timestamp dateGenerated,
			Timestamp settlementFromDate, Timestamp settlementToDate) {
		this.settlementId = settlementId;
		this.settlementRefId = settlementRefId;
		this.settlementDate = settlementDate;
		this.settlementAmount = settlementAmount;
		this.settlementDetails = settlementDetails;
		this.settlementReportUrl = settlementReportUrl;
		this.settlementIsVerified = settlementIsVerified;
		this.settlementIsAuthorized = settlementIsAuthorized;
		this.settlementReportPassword = settlementReportPassword;
		this.dateGenerated = dateGenerated;
		this.settlementFromDate = settlementFromDate;
		this.settlementToDate = settlementToDate;
	}

	public long getSettlementId() {
		return this.settlementId;
	}

	public void setSettlementId(long settlementId) {
		this.settlementId = settlementId;
	}

	public String getSettlementRefId() {
		return this.settlementRefId;
	}

	public void setSettlementRefId(String settlementRefId) {
		this.settlementRefId = settlementRefId;
	}

	public Timestamp getSettlementDate() {
		return this.settlementDate;
	}

	public void setSettlementDate(Timestamp settlementDate) {
		this.settlementDate = settlementDate;
	}

	public Double getSettlementAmount() {
		return this.settlementAmount;
	}

	public void setSettlementAmount(Double settlementAmount) {
		this.settlementAmount = settlementAmount;
	}

	public String getSettlementDetails() {
		return this.settlementDetails;
	}

	public void setSettlementDetails(String settlementDetails) {
		this.settlementDetails = settlementDetails;
	}

	public String getSettlementReportUrl() {
		return this.settlementReportUrl;
	}

	public void setSettlementReportUrl(String settlementReportUrl) {
		this.settlementReportUrl = settlementReportUrl;
	}

	public Character getSettlementIsVerified() {
		return this.settlementIsVerified;
	}

	public void setSettlementIsVerified(Character settlementIsVerified) {
		this.settlementIsVerified = settlementIsVerified;
	}

	public Character getSettlementIsAuthorized() {
		return this.settlementIsAuthorized;
	}

	public void setSettlementIsAuthorized(Character settlementIsAuthorized) {
		this.settlementIsAuthorized = settlementIsAuthorized;
	}

	public String getSettlementReportPassword() {
		return this.settlementReportPassword;
	}

	public void setSettlementReportPassword(String settlementReportPassword) {
		this.settlementReportPassword = settlementReportPassword;
	}

	public Timestamp getDateGenerated() {
		return this.dateGenerated;
	}

	public void setDateGenerated(Timestamp dateGenerated) {
		this.dateGenerated = dateGenerated;
	}

	public Timestamp getSettlementFromDate() {
		return this.settlementFromDate;
	}

	public void setSettlementFromDate(Timestamp settlementFromDate) {
		this.settlementFromDate = settlementFromDate;
	}

	public Timestamp getSettlementToDate() {
		return this.settlementToDate;
	}

	public void setSettlementToDate(Timestamp settlementToDate) {
		this.settlementToDate = settlementToDate;
	}

}
