package com.fidypay.entity;

// Generated Sep 23, 2015 6:40:35 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * WalletTrxnType generated by hbm2java
 */

@Entity
//@Table(name = "WALLET_TRXN_TYPE")
@EntityListeners(AuditingEntityListener.class)
@Table(name = "WALLET_TRXN_TYPE", indexes = {
		@Index(name = "index_WALLET_TRXN_TYPE_ID", columnList = "WALLET_TRXN_TYPE_ID"),
		@Index(name = "index_TRANSACTION_TYPE_NAME", columnList = "TRANSACTION_TYPE_NAME"),
		@Index(name = "index_TRANSACTION_TYPE_DETAILS", columnList = "TRANSACTION_TYPE_DETAILS")
		})
public class WalletTrxnType implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "WALLET_TRXN_TYPE_ID")
	private long walletTrxnTypeId;
	
	@Column(name="TRANSACTION_TYPE_NAME", length = 20)
	private String transactionTypeName;
	
	@Column(name="TRANSACTION_TYPE_DETAILS", length = 20)
	private String transactionTypeDetails;

	public WalletTrxnType() {
	}

	public WalletTrxnType(long walletTrxnTypeId) {
		this.walletTrxnTypeId = walletTrxnTypeId;
	}

	public WalletTrxnType(long walletTrxnTypeId,
			String transactionTypeName, String transactionTypeDetails) {
		this.walletTrxnTypeId = walletTrxnTypeId;
		this.transactionTypeName = transactionTypeName;
		this.transactionTypeDetails = transactionTypeDetails;
	}

	public long getWalletTrxnTypeId() {
		return this.walletTrxnTypeId;
	}

	public void setWalletTrxnTypeId(long walletTrxnTypeId) {
		this.walletTrxnTypeId = walletTrxnTypeId;
	}

	public String getTransactionTypeName() {
		return this.transactionTypeName;
	}

	public void setTransactionTypeName(String transactionTypeName) {
		this.transactionTypeName = transactionTypeName;
	}

	public String getTransactionTypeDetails() {
		return this.transactionTypeDetails;
	}

	public void setTransactionTypeDetails(String transactionTypeDetails) {
		this.transactionTypeDetails = transactionTypeDetails;
	}

}
